### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by nandordudas** [laravel-enso/Enso#10]
I like Your work, but can You use one of the eslint rules [[standard](https://github.com/standard/standard/blob/master/docs/RULES-en.md)|[airbnb](https://github.com/airbnb/javascript)|.*] ([option](https://github.com/vuejs-templates/webpack/blob/develop/template/.eslintrc.js#L12)s in vue-cli)?
Have a nice day!

**Comment by aocneanu** [comment]
Sure, this would be constructive. At the next refactor (soon) I will act on this too.

Meanwhile, if you want to take a shot at it, don't hesitate :)

**Comment by nandordudas** [comment]
Ok, I pull it a sample on next week

**Comment by aocneanu** [comment]
This is great news :)

I suppose that we should go for standard rules.

I can also activate the eslint on https://www.codacy.com/app/laravel-enso and this will help with following the syntax change. Right now it's turned off for obvious reasons.
So when you decide to start on a package just let me know and I'll activate the codacy linter for it.

**Comment by aocneanu** [comment]
the config/rules/dependencies are now added via 9ca5e3fa54de6656582cdb8862390e800ac30cdd
