### ISSUE TITLE
Themes appears to be broken on 2.7.1

### ISSUE THREAD

**Issue by stevefrost** [laravel-enso/Enso#101]
This is  a **bug**.

### Prerequisites
* [x ] Are you running the latest version?
* [x ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x ] Did you check the documentation?
* [x ] Did you perform a cursory search?

### Description
Themes are no longer being applied

### Steps to Reproduce
Apply a new theme
Refresh the application

### Expected behavior
Selecting a new theme should apply the new theme

### Actual behavior
When you apply a theme, the href of the theme link is being set to undefined
When you refresh the application the chosen theme is not applied.

**Comment by aocneanu** [comment]
closed with https://github.com/laravel-enso/Core/commit/6bc31bfb0f72d1f6a7d8ccc1372423a8f5f75767
