### ISSUE TITLE
Postgres error on backticks

### ISSUE THREAD

**Issue by dbtinoyapp** [laravel-enso/Enso#103]
Support for Postgres database.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

### Description
Postgres is producing an error on backticks(`) escaping.

### Steps to Reproduce
Browsing Menu list

### Expected behavior
Menu list will display properly

### Actual behavior
Error encountered.

<img width="408" alt="screen shot 2018-05-28 at 9 53 04 am" src="https://user-images.githubusercontent.com/14541963/40593780-4f80c2e6-625d-11e8-8ff1-71181ed75cd7.png">

**Comment by aocneanu** [comment]
I just did a complete refactor of all the "reserved words" named columns - there were more than what you reported.

The change is breaking, so you can either start with git clone again, or follow the upgrade steps from the Changelog.

If you find any other problems with PostgreSQL please open another issue.

**Comment by dbtinoy-** [comment]
Hi @aocneanu thanks much. All your work is greatly appreciated!

**Comment by aocneanu** [comment]
If you really like Enso, or even parts, support it by starring.
