### ISSUE TITLE
Tutorial on how to create a package from scratch

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [laravel-enso/Enso#104]
Is there any tutorial on how to create a package from scratch, for example with a product registration related to suppliers

with the following fields:

Product Table

id int (11)
suppliers_id int (11)
product varchar (255)
price float (11.2)
total float (11.2)

Supplier Table
id int (11)
supplier varchar (255)

**Comment by aocneanu** [comment]
Hi,

If you are talking about creating a Laravel package there are a lot of useful step by step tutorials on the web.

Once you know how to create a Laravel package, to create a structure in Enso (routes, views, controllers, tables, forms etc) take the `laravel-enso/permissionmanager` as an example, look at the permission groups part (it's simpler) and replicate everything there.

**Comment by andersondeoliveiramachado** [comment]
Thanks for the answer. In case when I talk about a package, it's for Enso!
I will study laravel-enso / permissionmanager as indicated.
