### ISSUE TITLE
[Question] Help needed for diving into Enso?

### ISSUE THREAD

**Issue by bloggervista** [laravel-enso/Enso#107]
I am planning to deep dive into this package. And is there any suggestion from you where should I start?

Currently I have started from core. And I want to know should I go inside main laravel directory/app folder. Because I think everything is modular in enso  and everything is published? Should I go and dive into resource/assets folder also? It will be helpful if you have any tips etc .

Thanks  for this awesome stuffs . I hope I have known it sooner :)

**Comment by aocneanu** [comment]
Hi,

What's your goal?

If you just want to understand how Enso is working, I would suggest starting from the [docs](https://docs.laravel-enso.com) and then going through the packages, where you think that can be useful. Ask if you hit walls.

If you want to start developing fast, you can use everything that is created as example, and again, ask questions when you hit walls.

If you would give me some more details about what you are seeking I can give you a more precise answer.

P.S. Thank you for showing your appreciation.

**Comment by aocneanu** [comment]
P.S 2: Backpack is cool too ;)

**Comment by bloggervista** [comment]
Hi the goal is only to learn :) Yea learnt backpack already so wanted to learn more

**Comment by aocneanu** [comment]
Then start from the docs and than look at the packages one by one. Whenever you need support on something just ask. Don't forget to star what you like ;)

**Comment by bloggervista** [comment]
Yeah thanks :)

Will close it as it already fix many issues :)

**Comment by aocneanu** [comment]
thanks buddy ;)
