### ISSUE TITLE
Error at api/administration/users/getTableData

### ISSUE THREAD

**Issue by corientdev** [laravel-enso/Enso#109]
This is  a **bug.

### Prerequisites
* [ yes] Are you running the latest version?
* [yes ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ yes] Did you check the documentation?
* [ don't know] Did you perform a cursory search?

### Description

Error at api/administration/users/getTableData
{message: "Undefined property: LaravelEnso\Helpers\app\Classes\Obj::$meta",…}
exception
:
"ErrorException"
file
:
"/var/www/html/Enso/vendor/laravel-enso/helpers/src/app/Classes/Obj.php"
line
:
36
message
:
"Undefined property: LaravelEnso\Helpers\app\Classes\Obj::$meta"
trace
:
[,…]
### Expected behavior
It should work

### Actual behavior
Not getting data

**Comment by corientdev** [comment]
Sorry my nginx error didn't configured sub query.

You are wonderful keep going.

**Comment by aocneanu** [comment]
If you ecounter any other problems let us know.
And if you really like Enso support it with a star.m :)
