### ISSUE TITLE
Comments with user tags fail to post.

### ISSUE THREAD

**Issue by tylerjheslop** [laravel-enso/Enso#11]
Comments that are tagged fail to post when Pusher is set up and the user is outside of EU. I am in the US. Pusher returns a payload with a mismatched size. 

To fix this, I manually set the payload in /resources/assets/js/pages/enso/layout/navbar/Notifications.vue.

```
init() {
		this.Echo = new Echo({
		    broadcaster: 'pusher',
		    key: this.meta.pusher,
		    cluster: 'us2',
		    namespace: 'App.Events'
		});
	},
```

**Comment by aocneanu** [comment]
We need to move at least the cluster to a config file. Will do that soon

**Comment by aocneanu** [comment]
fixed. you need to add in broadcasting.php the cluster if you don't have it yet.

https://pusher.com/docs/clusters
