### ISSUE TITLE
Error in Composer Install

### ISSUE THREAD

**Issue by xerk** [laravel-enso/Enso#112]
```
Problem 1
    - Installation request for laravel/horizon v1.3.1 -> satisfiable by laravel/horizon[v1.3.1].
    - laravel/horizon v1.3.1 requires ext-pcntl * -> the requested PHP extension pcntl is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.`
```
I got this error when i install composer `composer install`

**Comment by heyner29** [comment]
Hi, I had the same problem in windows. My only solution was to make:
composer install --ignore-platform-reqs
So far I have not noticed any malfunctions. Sorry for my English, use the Google translator :)

**Comment by aocneanu** [comment]
@xerk , did you try @heyner29 's solution?

**Comment by aocneanu** [comment]
closing due to the inactivity of the OP

**Comment by henryingsis** [comment]
yarn build command does not work on windows

problem console

enso@ build C:\xampp\htdocs\enso-master\client
rm -rf ../public/{js,themes,themes-rtl,images} && vue-cli-service build --no-clean --modern
"rm" no se reconoce como un comando interno o externo,

**Comment by heyner29** [comment]
Have you tried using a different console than CMD?  `Git Bash` or `Cmander` alternatives

**Comment by evgenia-lenti** [comment]
> Hi, I had the same problem in windows. My only solution was to make:
> `composer install --ignore-platform-reqs`
> So far I have not noticed any malfunctions. Sorry for my English, use the Google translator :)

Thank you so much! It worked for me!

**Comment by ajitirto** [comment]
thank you for this information

**Comment by facesses** [comment]
> Go php.ini file and find ;extension=zip
> 
> remove ;

it works. Thank you.
