### ISSUE TITLE
Modify view

### ISSUE THREAD

**Issue by eo22** [laravel-enso/Enso#114]
Can you help me, how can I modify the view. I want to add new language but I cannot add the flag for that language. I've downloaded the image for new language and put it on flags img folder, call it on code but it's not displayed again! I want to add new line on footer, how can I modify?

**Comment by aocneanu** [comment]
Don't skip the issue template, than read the documentation, and than ask specific questions if you hit walls

**Comment by eo22** [comment]
Sorry I don't understand your response, it's not clear to me. I've added new <p> line on AppFooter.vue but it's not displayed?!

**Comment by aocneanu** [comment]
This is the issue template that you skipped:

![image](https://user-images.githubusercontent.com/16073274/42868084-16542c5c-8a7a-11e8-97c3-de1cfce84af6.png)

In the issue template this is the relevant part for this topic:

![image](https://user-images.githubusercontent.com/16073274/42868120-2f03f44e-8a7a-11e8-9e2a-41600b6a110e.png)

In the docs you will find everything needed for adding a language.

**Comment by eo22** [comment]
This is  a request**.


### Prerequisites
* [+ ] Are you running the latest version?
* [+ ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [+ ] Did you check the documentation?
* [ +] Did you perform a cursory search?

### Description


### Steps to Reproduce


### Expected behavior


### Actual behavior

**Comment by aocneanu** [comment]
>[+ ] Did you check the documentation?

Here the answer is NO.

Go to the link below

https://docs.laravel-enso.com/#localisation

**Comment by eo22** [comment]
What about the line of code on footer that is not displayed?!

**Comment by aocneanu** [comment]
Did you compiled after editing the footer file?

**Comment by eo22** [comment]
Can you help me with these errors?

ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./resources/assets/sass/flags.scss
Module not found: Error: Can't resolve '../../../node_modules/flag-icon-css/flags/4x3/sq.svg' in '/Applications/XAMPP/xamppfiles/htdocs/Enso/resources/assets/sass
