### ISSUE TITLE
How can I create and configure multiple users

### ISSUE THREAD

**Issue by eo22** [laravel-enso/Enso#115]
This is  a  request**.

### Prerequisites
* [ +] Are you running the latest version?
* [ +] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ +] Did you check the documentation?
* [ +] Did you perform a cursory search?

### Description
I want to ask you how can I create multiple users who can login and assign to them some of menus etc.?
Thanks a lot!

**Comment by gandesc** [comment]
Considering you don't want to have all your users accessing all menus, you should:
- create the desired roles
- configure the roles, assigning menus and permissions
- create owners as required, assign them the proper roles (such as the ones created above)
- create the needed users, assign them to the proper owner and role.

All of the above can be achieved through the interface.

Your new users will receive password reset emails, allowing each one to set a password.

**Comment by eo22** [comment]
I've added new role and assign menus and permissions to it. When I create new user, there's no field for password and user didn't receive any email with password or so. What should I do?
Thanks a lot for your advance!

**Comment by gandesc** [comment]
Just as a test, you could use tinker to manually set each user a password, or create a mechanism, migration, etc.

Outside of tests, you need to ensure the password reset email gets sent - make sure that your dev environment is able to send email, that you have your queue  listener started and that your .env config is ok, especially regarding the queue driver and email.

**Comment by aocneanu** [comment]
@eo22 Do you have `QUEUE_DRIVER=sync` in your `.env`?

Is the email service configured, also in  `.env`?

**Comment by eo22** [comment]
How can I add new extra field in creating new user? I can't understand the structure of files yet.
Thanks a lot for your support...
