### ISSUE TITLE
Base prefix for url's

### ISSUE THREAD

**Issue by zcwilt** [laravel-enso/Enso#117]
This is  a **feature request**.

### Prerequisites
* [+] Are you running the latest version?
* [+] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [+] Did you check the documentation?
* [+] Did you perform a cursory search?

### Description

Currently Enso does not have a prefix, so going to some url like http://enso.test triggers the login and all other url's are based on this.
What I want is for Enso to use http://enso.test/dashboard as a base for all urls.

**Comment by aocneanu** [comment]
I'm a little confused. I guess that you want to use Enso as a control panel for an existing system / site.

If so, I think that the cleanest way to do this would be having a subdomain of your original domain pointing to the Enso instance. So instead having `yourproject.com/admin` you would have to do `admin.yourproject.com`.

**Comment by zcwilt** [comment]
Hi,
First should say that what you are doing is awesome.
Yes, I have a frontend application that is a mixture of standard laravel and some vue components, but not an spa, and want to use Enso as the backend admin

Hadn't thought of using a subdomain, and  that would definitely work, although I would think that others might want a system where '/' accesses their frontend and '{prefix}/' accesses Enso.
again thanks for all the work, especially the CLI Structure stuff, saved me a lot of work. :)

**Comment by aocneanu** [comment]
Glad that the CLI helped you.

If you really like Enso, or even parts of it, you can show your support by giving a star or two ;)

**Comment by zcwilt** [comment]
Will Do.
