### ISSUE TITLE
Teams

### ISSUE THREAD

**Issue by stevefrost** [laravel-enso/Enso#118]
Hi Adi

I see you have added team management which is brilliant, as it's a feature I will need shortly, I just wanted to check what the current functionality is and what your future intentions are?

**Comment by aocneanu** [comment]
Hi Steve,

You can check the current functionality on the [demo](https://www.laravel-enso.com).

Currently it's simple implementation where you have the ability to define teams as group of users.

Regarding relationships you can do both:

`$user->teams` and `$team->users` (many to many).

And this will be a good fit for the `next-gen` packages that we are working on (discussions, a better documents manager etc)
