### ISSUE TITLE
DataImporter has unexpected behavior around capitalization and spaces in json template

### ISSUE THREAD

**Issue by csajedi** [laravel-enso/Enso#119]
This is  a **bug**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description

The title gives a rough idea of the problem, the DataImporter is supposed to infer certain camelcase, spaces-to-underscore conversions and in that functionality it has unexpected behavior around capitalization and spaces in json template, i get errors in my json template for capitalization mismatch between the xls sheets and column titles and I confirmed that this is not to be expected.

**Comment by aocneanu** [comment]
I did a thorough analysis on this and the conclusion is that we want the template to be written in a consistent syntax.

Regarding the column titles for example, I don't see any benefit in allowing the dev to write the json templates in a non standard way, where he can have:

`First Name` == `first_name` == `first  NAME`.

So we'll stay with the enforced snake case for templates. I do see an advantage giving the actual user the liberty to name its columns like above, and convert everything under the hood to snake case for validations and import (what the package is doing now)

The obvious conclusion would be that the package documentation needs to be greatly improved, and we will work on that ( @gandesc ).
