### ISSUE TITLE
[Feature Request] Can we add tailwind support?

### ISSUE THREAD

**Issue by shirshak786** [laravel-enso/Enso#121]
Feature Request.

After seeing Laravel Nova I think this project also can use tailwind making the look better :)

Current UI is awesome but there are some beautiful theme like Tabler UI which I think can really put some interest in people?

What do you say :)

**Comment by aocneanu** [comment]
I'm open to it, of course.

I admit that I'm not sold on tailwind's approach, but also not particularly educated with it. When I will have some spare time I will play more with the framework.

I also believe that there's a lot more space left to be filled with Bulma, in terms of UI. And I like Nova visually too. I plan to use it as inspiration and soon do a refresh to the current Enso state.

If you want to collaborate on this, maybe you can start a wishlist issue where we can track all the components that need refresh, what's missing now and so on.

**Comment by shirshak786** [comment]
Ok for that I will create dedicated issues :)

Thanks
