### ISSUE TITLE
Password reset problem

### ISSUE THREAD

**Issue by eo22** [laravel-enso/Enso#122]
This is  a request.

### Prerequisites
* [ +] Are you running the latest version?
* [ +] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ +] Did you check the documentation?
* [ +] Did you perform a cursory search?

### Description

I've problem with password reset from "forgot password" on login page. I've changed config in .env file. When I write the email for password reset it show red line and x.
I've checked some issues that might be the same like mine, but I didn't find any solution. There are some errors on console. I hope you can help me with this problem and I want to thank you for your help!

![123](https://user-images.githubusercontent.com/37216194/43467667-7f64084e-94e2-11e8-9c3a-2a45f68b6835.png)

![222](https://user-images.githubusercontent.com/37216194/43467723-a90b9cb6-94e2-11e8-891b-c2350a6ce16e.png)

![screen shot 2018-07-31 at 16 40 47](https://user-images.githubusercontent.com/37216194/43466750-828d359c-94e0-11e8-881e-5aee3ddfa037.png)

**Comment by gandesc** [comment]
Can you also post your `laravel.log` error trace, for this issue?

**Comment by eo22** [comment]
@gandesc, after composer update and compiling now I can reset email password. Thank you for your respond!
:)
