### ISSUE TITLE
hot / hmr doesn't compile Vue at all?

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Enso#124]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

When changing something in a .vue file; neither `hot` nor `hmr` seems to be compiling the `.vue` files, as those changes are not shown; not even initially...

I can see webpack correctly recompiling once I make a change & save; I see a network call to localhost `enso.css` & `enso.js` that both complete successfully (`200 OK`)

### Steps to Reproduce
1. Follow steps in the [_Try it up_ section](https://docs.laravel-enso.com/#try-it-up) (I ran `dev` at least once before the next step)
2. Start the `hot` sever & make changes to a `.vue` file (f.e. a `test` in the `<div class="column"...`-tag at `resources/assets/js/pages/dashboard/Index.vue`)

### Expected behavior
See `test` appear at the top of the columns (as would happen when compiling via `dev`)

### Actual behavior
Nothing changes; even stopping, restarting & refreshing doesn't change anything; except with an `npm run dev` -- which isn't a hot replace

**Comment by aocneanu** [comment]
I believe that it's something related to your local env. Never had this problem.

Does your Chrome console shows you that you are in HMR mode?

**Comment by jlsjonas** [comment]
It doesn't; I'm guessing it's related to [when vue-loader is disabled automatically](https://vue-loader-v14.vuejs.org/en/features/hot-reload.html#disabling-hot-reload) somehow; but I'm basically just using the master branch (with modified `.env`).

My current company works with windows pc's though (could be related)
I'm still investigating and I'll definitely update this issue if I found a fix (though I'm starting to run out of ideas here 😅 )

p.s.: thanks for the amazing response times; a lot of Open-Source projects could _learn_ from you :)

**Comment by aocneanu** [comment]
Does hmr work in other projects?

**Comment by jlsjonas** [comment]
Yes it does; including with _frameworks_ like Nuxt.js.

I just confirmed and followed the steps as per [_Try it up_](https://docs.laravel-enso.com/#try-it-up) in a clean environment and hmr will not activate. (note that I do get a network request to fetch enso.js & .css from the webpack-dev-server; **only right after pageload**)
![image](https://user-images.githubusercontent.com/932193/43784102-9c08a85c-9a63-11e8-96ac-c662cfad9078.png)


Caveats:
I had to run `composer install --ignore-platform-reqs` instead of `composer install` (this _only had to do with laravel/horizon including pcntl, which isn't available on windows.

**Comment by aocneanu** [comment]
No idea, I have 0 experience with Windows.

**Comment by jlsjonas** [comment]
For anyone stumbling upon this in the near future:

in `webpack.mix.js` you can add the following ([source](https://github.com/JeffreyWay/laravel-mix/issues/1483#issuecomment-366685986)):
```js
Mix.listen('configReady', (webpackConfig) => {
    if (Mix.isUsing('hmr')) {
    // Remove leading '/' from entry keys
        webpackConfig.entry = Object.keys(webpackConfig.entry).reduce((entries, entry) => {
            entries[entry.replace(/^\//, '')] = webpackConfig.entry[entry];
            return entries;
        }, {});

        // Remove leading '/' from ExtractTextPlugin instances
        webpackConfig.plugins.forEach((plugin) => {
            if (plugin.constructor.name === 'ExtractTextPlugin') {
                plugin.filename = plugin.filename.replace(/^\//, '');
            }
        });
    }
});
```

This will basically remove the first `/` of every path (if you look closely they all start with `//`
this fixed the issue for me on Windows

(not sure if only an upstream issue though; but definitely related to https://github.com/JeffreyWay/laravel-mix/issues/1483; feel free to close if only upstream)

**Comment by aocneanu** [comment]
Cool! Let's leave this open for a while.
