### ISSUE TITLE
Adding new input/field in create user form

### ISSUE THREAD

**Issue by eo22** [laravel-enso/Enso#126]
This is  a request

### Prerequisites
* [ +] Are you running the latest version?
* [ +] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ +] Did you check the documentation?
* [+ ] Did you perform a cursory search?

### Description
I want to add new field for password in creating user- form, but when I add it to user.json file than create user doesn't work at all.

![screen shot 2018-08-10 at 14 59 24](https://user-images.githubusercontent.com/37216194/43959128-1276f056-9cae-11e8-8ca7-162eb8b01471.png)

![screen shot 2018-08-10 at 15 00 45](https://user-images.githubusercontent.com/37216194/43959167-2dcaa32a-9cae-11e8-8d63-11beed1d076e.png)

![screen shot 2018-08-10 at 15 04 14](https://user-images.githubusercontent.com/37216194/43959326-b2bca5d8-9cae-11e8-9d81-e1c6fe625504.png)

**Comment by aocneanu** [comment]
Update in `config/enso/forms.php` the `validations` key to match your `APP_ENV` value.

Now the validator will let you know that `"type": "password"` does not exist in this package. Then go read the [docs](https://docs.laravel-enso.com/packages/form-builder.html) about `"type"` attribute and what it is used for.

**Comment by eo22** [comment]
Can I add this "type: password" on this package and if yes can you help me how?

Thanks a lot.

**Comment by aocneanu** [comment]
You really don't like reading docs right?

![image](https://user-images.githubusercontent.com/16073274/43963763-e7c898bc-9cc3-11e8-9895-c430c6875a74.png)

for password you need to use "type": "input"

**Comment by eo22** [comment]
Yes, I've read the doc in fact but I thought it was like "input type="something..", that's why I've asked you. Now I'm going to try/prove this.

Thanks again.
