### ISSUE TITLE
Error while installing on windows

### ISSUE THREAD

**Issue by tahiriqbalnajam** [laravel-enso/Enso#132]
I tried to install on windows10, wamp with PHP7.2 and got error while running "composer install"

Your requirements could not be resolved to an installable set of packages.

====================================
  Problem 1
    - Installation request for laravel/horizon v1.3.1 -> satisfiable by laravel/horizon[v1.3.1].
    - laravel/horizon v1.3.1 requires ext-pcntl * -> the requested PHP extension pcntl is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - A:\wamp64\bin\php\php7.2.9\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
=====================================

As checked on google, pcntl is not supporting windows environment, so can we change this extension to any alternative?

**Comment by heyner29** [comment]
Hi, when I tried to install on windows I had the same problem. I solved it with `composer install --ignore-platform-reqs`.

Maybe it's not exactly the solution you're looking for, but it's a good option to start.  In the time that I use it on windows I did not have any problem installing it in that way.

**Comment by aocneanu** [comment]
Can we close this?

**Comment by tahiriqbalnajam** [comment]
sure,
But now facing another problem :)
as I clicked on public to load the app, its always trying to load the view with blank white page, nothing happened even after half an hour.
As was trying to learn Veu with Laravel, have already knowledge with Laravel but not with Veu.
I checked even with developer tool, there is no call response.
So where should I check.

**Comment by aocneanu** [comment]
I really don't understand what you're facing from your description, but what I can tell you is:

**-open one issue per identified problem, don't transform this into chat**
**-use the issue template, it's not optional; follow its guidelines too**
**-make sure that the problems are related to Enso, not Vue or Laravel**

**Comment by emailsample24** [comment]
hello I am getting the same error, have you guys figured out how to fix this?

**Comment by DKWLB** [comment]
Up! Seems it is unreal to install on Windows without headache(

**Comment by jlsjonas** [comment]
> Hi, when I tried to install on windows I had the same problem. I solved it with `composer install --ignore-platform-reqs`.

This works just fine, I'm using the framework on windows (production-part is on Linux servers though, as is 90+% of the web)

`pcntl` is a requirement of one of the core Laravel packages, so no there's no way to not use it.

This is one of the reasons why Laravel provides a homestead for "hassle-free" usage.

That being said, it works just fine for development when adding `-ignore-platform-reqs` whenever using composer.

If you encounter any specific issues with the framework feel free to open an issue for it and I'll help fixing it; though I haven't discovered framework-related issues for running on windows anymore (the few I encountered were patched several months ago)
