### ISSUE TITLE
ROLE Description not persisting to database

### ISSUE THREAD

**Issue by corepay** [laravel-enso/Enso#134]
This is  a **bug**.

### Prerequisites
* [X ] Are you running the latest version?
* [X ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [X ] Did you check the documentation?
* [X ] Did you perform a cursory search?

### Description

`/system/roles/` ROLE Description is not persisting data

Create or edit role from list and add/edit description.  Toast pops up saved.  Return to List and Role Description is not changed.  Edit again and blank or old value remains.

![image](https://user-images.githubusercontent.com/37046197/44938774-bf19e600-ad4e-11e8-9171-2963a30c27a7.png)

### Steps to Reproduce
1. Create or Edit existing Role
2. Add or Change Description
3. Save
4. View List column did not change or empty on create
5. Edit Role and Old value or blank on new role

### Expected behavior

Description should persist when created or edited

### Actual behavior

Role Description does not persist

**Comment by aocneanu** [comment]
>Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)

No, you're not. This issue belongs to the [rolemanager](https://github.com/laravel-enso/RoleManager)
