### ISSUE TITLE
composer update error

### ISSUE THREAD

**Issue by emailsample24** [laravel-enso/Enso#137]
Hi, Iam geting this error white running the composer update
![image](https://user-images.githubusercontent.com/42670610/45119225-62bf2800-b18d-11e8-8de5-8b946029dbdd.png)

here are the things I've done befire submitting this issur ( toubleshooting)

-tried 7.1xampp version
-added extension=php_fileinfo.dll in php.ini

pleasse help

**Comment by aocneanu** [comment]
Closed due to inactivity
