### ISSUE TITLE
How to add new CRUD with new table and menu

### ISSUE THREAD

**Issue by epilim200** [laravel-enso/Enso#139]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

I already create new menu and set permission to new menu, and also create route and vue file for view but when I click the new menu it go to root link, never go to link I already add with new menu. I try to go manually to the new link that I just create, it show error 404 not found

Thanks.

**Comment by aocneanu** [comment]
Did you used the [StructureManager](https://docs.laravel-enso.com/packages/structure-manager.html#features) ?

**Comment by aocneanu** [comment]
Make sure you have v2.2.43 for structure manager (run a composer update to get it)

**Comment by aocneanu** [comment]
I’m asshming that you run `php artisan:migrate` after creating the structure from cli

**Comment by epilim200** [comment]
After generate using StructureManager, I copy route given to api, run artisan migrate, run npm run dev, and click new menu just created title show undefined and page is blank. Here is full log from laravel.log

[2018-09-09 02:00:37] local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'admin' for key 'roles_name_unique' (SQL: insert into `roles` (`description`, `display_name`, `menu_id`, `name`) values (Administrator role. Full featured., Administrator, 1, admin), (Supervisor role., Supervisor, 1, supervisor)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'admin' for key 'roles_name_unique' (SQL: insert into `roles` (`description`, `display_name`, `menu_id`, `name`) values (Administrator role. Full featured., Administrator, 1, admin), (Supervisor role., Supervisor, 1, supervisor)) at /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'admin' for key 'roles_name_unique' at /Applications/MAMP/htdocs/Enso/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:144, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'admin' for key 'roles_name_unique' at /Applications/MAMP/htdocs/Enso/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:142)
[stacktrace]
#0 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('insert into `ro...', Array, Object(Closure))
#1 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\\Database\\Connection->run('insert into `ro...', Array, Object(Closure))
#2 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\\Database\\Connection->statement('insert into `ro...', Array)
#3 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2541): Illuminate\\Database\\Connection->insert('insert into `ro...', Array)
#4 /Applications/MAMP/htdocs/Enso/database/seeds/RoleSeeder.php(17): Illuminate\\Database\\Query\\Builder->insert(Array)
#5 [internal function]: RoleSeeder->run()
#6 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#7 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#9 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#10 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Database/Seeder.php(122): Illuminate\\Container\\Container->call(Array)
#11 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Database/Seeder.php(42): Illuminate\\Database\\Seeder->__invoke()
#12 /Applications/MAMP/htdocs/Enso/database/seeds/DatabaseSeeder.php(10): Illuminate\\Database\\Seeder->call('RoleSeeder')
#13 [internal function]: DatabaseSeeder->run()
#14 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#15 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#17 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#18 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Database/Seeder.php(122): Illuminate\\Container\\Container->call(Array)
#19 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(63): Illuminate\\Database\\Seeder->__invoke()
#20 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php(122): Illuminate\\Database\\Console\\Seeds\\SeedCommand->Illuminate\\Database\\Console\\Seeds\\{closure}()
#21 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(64): Illuminate\\Database\\Eloquent\\Model::unguarded(Object(Closure))
#22 [internal function]: Illuminate\\Database\\Console\\Seeds\\SeedCommand->handle()
#23 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#24 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#25 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#26 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#27 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#28 /Applications/MAMP/htdocs/Enso/vendor/symfony/console/Command/Command.php(251): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#29 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#30 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Console/Command.php(198): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#31 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(78): Illuminate\\Console\\Command->call('db:seed', Array)
#32 [internal function]: Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#33 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#34 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#35 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#36 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#37 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#38 /Applications/MAMP/htdocs/Enso/vendor/symfony/console/Command/Command.php(251): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#39 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#40 /Applications/MAMP/htdocs/Enso/vendor/symfony/console/Application.php(886): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#41 /Applications/MAMP/htdocs/Enso/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Database\\Console\\Migrations\\MigrateCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#42 /Applications/MAMP/htdocs/Enso/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#43 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#44 /Applications/MAMP/htdocs/Enso/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#45 /Applications/MAMP/htdocs/Enso/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#46 {main}
"}

**Comment by aocneanu** [comment]
This error does not have anything to do with what you're reporting. I mean, this error is thrown from the RoleSeeder...

Clear the log and try again.

**Comment by epilim200** [comment]
Sorry, after I logout and login again, now its working...I dont know why this happen.

**Comment by aocneanu** [comment]
Np
