### ISSUE TITLE
Info for ERP

### ISSUE THREAD

**Issue by cerelli** [laravel-enso/Enso#140]
Excuse me, I did not know where to write for information.
I have to create a small CRM with the possibility of making invoices, then master and details on the same page.
Is it possible with enso?
Thank you.

**Comment by aocneanu** [comment]
Yes, of course.

**Comment by cerelli** [comment]
Thanks. 
what is the best practice to change contacts? I want more emails and more phone numbers for single contact.

**Comment by aocneanu** [comment]
I'm not sure what you're expecting. Look into the contacts package, and extend it as you wish / need.
