### ISSUE TITLE
Settings directory deleted

### ISSUE THREAD

**Issue by scottasmith** [laravel-enso/Enso#141]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
The settings directory was deleted `resources\js\core\structure`

### Expected behavior
Works

### Actual behavior
Doesn't :)

**Comment by aocneanu** [comment]
It was renamed to ‘menu’ please read the changelog

**Comment by scottasmith** [comment]
And you can find `Settings.vue` in the `menu` directory can you?

Please try a brand new clean install and tell me it works!

**Comment by scottasmith** [comment]
Sorry I didn't mean to be offensive there 😔

**Comment by aocneanu** [comment]
Ah I see..

**Comment by aocneanu** [comment]
that's strange.. run `php artisan vendor:publish --tag=enso-assets` or `composer update` (will run the same command in post-update-cmd)

**Comment by aocneanu** [comment]
fixed in the main repo too ( 7ef28b3c )

**Comment by scottasmith** [comment]
Thankyou, I will have to try this when I get back to work tomorrow.

On another note the `yarn.lock` was looking for a fortawesome package from `npm.fortawesome.com` hence having to delete the lock file to prevent yarn install  throwing a 401 exception.
