### ISSUE TITLE
Dashboard/home page broken (blank page)

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Enso#143]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

> Also note that after overriding the function in app\User to failover (to 0) dashboard only seemed to load with `<App>` & `<Progressbar>` visible in the vue devtools (without any errors, that is; neither client nor server-side)
> VueX mutations are being ran correctly btw
>
>_Originally posted in https://github.com/laravel-enso/Core/issues/67#issuecomment-423159592_

Meanwhile checked and it's not related to the different authentication provider; no matter what I do I keep getting a blank page with seemingly no components available (except for `<ProgressBar>`) with the last version

All VueX data seems to be correct and haven't changed the dashboard/related items yet since _starting from scratch_ (as a debug step from having weird issues)

![image](https://user-images.githubusercontent.com/932193/45820970-5cca5a80-bce8-11e8-95e1-a1e10a6d9d00.png)

### Steps to Reproduce
1. Log in
2. Note a blank page

### Expected behavior

Dashboard to show

### Actual behavior

Blank page with only `<App>` and `<ProgressBar>` when inspecting, Vuex mutations correctly being triggered as far as I can see

**Comment by aocneanu** [comment]
- did you carefully read the changelog?
- did you clear the existing preferences?
- did you publish the new preferences.json?

**Comment by jlsjonas** [comment]
I did, but I didn't upgrade as I was experiencing issues on the profile page & there were more significant changes in the changelog than in the code I had at that point, I followed the original installation instructions (and carefully merged in the changes I did where still applicable)
Just realized I didn't check the .env file though, but afaik it wasn't mentioned in the changelog either

**Comment by jlsjonas** [comment]
Just checked, the cause was indeed the settings file; somehow the layout line got removed while merging my shelved changes in (weird...)

Sorry for the disturbance.
