### ISSUE TITLE
The user password for the demo no longer works

### ISSUE THREAD

**Issue by heyner29** [laravel-enso/Enso#144]
This is  a **bug**.

### Description
Sure someone changed the user password and that is why it is not possible to enter with the credentials of the demo.
`admin@laravel-enso.com` & `password`

**Comment by aocneanu** [comment]
I was wondering when this will happen :). Fixed

**Comment by heyner29** [comment]
Yes, I also found it strange that they did not do it :)
I already managed to login with the demo credentials but it seems that updates are being applied and they present some bugs.
![captura de pantalla de 2018-09-21 06-32-34](https://user-images.githubusercontent.com/12703614/45879052-b70b0000-bd68-11e8-82ac-eaaf63616b30.png)
![captura de pantalla de 2018-09-21 06-33-05](https://user-images.githubusercontent.com/12703614/45879058-ba05f080-bd68-11e8-984f-aedb95aecffd.png)

By the way, was the inspiring message removed after login true?.Thank you again for being attentive to all the issues that I report

**Comment by aocneanu** [comment]
It was a problem with the admin's avatar
