### ISSUE TITLE
2.11.5+ CHANGELOG missing upgrade steps?

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Enso#145]
This is  a _**bug**_.

### Prerequisites
* [ ] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

CHANGELOG.md doesn't contain upgrade steps for most versions after 2.11.5

### Steps to Reproduce
N/A

**Comment by aocneanu** [comment]
2.11.9 has something, for the rest composer update and compile. Not all upgrades have to break something :D

**Comment by jlsjonas** [comment]
:D ok, just wanted to be sure as I didn't see the default upgrade path anywhere
