### ISSUE TITLE
Should really consider linking to the extended App\User everywhere

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Enso#149]
This is a **bug / feature request** (both, in a way? 😅).

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(Enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Any extension to the User model (including changing the fullName format) breaks stuff cascadingly over the place; especially with recent updates which rely even more on the User class.

As the separate packages already _break_ insulation by using classes only indirectly required; I really think you should reconsider linking to `\App\User` instead of `\LaravelEnso\Core\app\Models\User`

Right now, because of minor changes to the User model I have to copy tests/controller into Enso directly; just to modify the use. Which also means that with future updates all these files will have to be checked too.

It's a great framework; and it already assumes you'll extend the User model by providing the file in `\app`.

So I really think the advantages of assuming `\app\user` exist & is _enso-compatible_ greatly outweigh any encapsulation that might be broken (after all; the framework is already depending on _itself_ in several places; and even future decoupling would still need something similar and/or changes to the way it's `use`'d anyway.

EDIT: also, by default \App\User is extending _EnsoUser_ already; so it doesn't negatively impact anyone who doesn't want/need to extend User

**Comment by aocneanu** [comment]
>Any extension to the User model (including changing the fullName format) breaks stuff cascadingly over the place; especially with recent updates which rely even more on the User class.

Again you're not providing specifics. If something is wrong with `fullName` we should fix it at the framework level.

>As the separate packages already break insulation by using classes only indirectly required; I really think you should reconsider linking to \App\User instead of \LaravelEnso\Core\app\Models\User

?

This is the n'th discussion you're raising on this subject and I'm still waiting for clear examples of your integration where you face problems. If you would provide such examples maybe I could provide solutions. Until now you're scared of all sorts of "potential problems" for which you have an *easy solution*, but the proposed direction is not where we want to be heading.

Please take a look on #150

**Comment by jlsjonas** [comment]
> Again you're not providing specifics. If something is wrong with `fullName` we should fix it at the framework level.

I just gave you an example, `including changing the fullName format`
Also note that the core issue is just the fact that everything is expecting a `LaravelEnso\Core\app\Models\User` and receiving an `App\User`, which is a (default-provided) extension of the `LaravelEnso\Core\app\Models\User` model already.

f.e.:
- changing fullName() from `firstname lastname` to `firstname lastname (role)` -- breaks tests.
- adding an extra field to the User model -- breaks tests & certain parts where the user object is expected

There's a couple other cases that I can't think of right now; either way, **nearly all of them are fixed just by replacing `use LaravelEnso\Core\app\Models\User;` with `use App\User;` (in applicable Controllers, Responses & tests)

This isn't because of a potential issue; it never was. It's because of issues I'm actually dealing with while extending the framework.

regarding #150, looks promising indeed; however it would not solve our requirement for a username as loginbase (everyone is used to it when dealing with other LDAP/AD-connected systems)

**Comment by aocneanu** [comment]
>I just gave you an example, including changing the fullName format

So the example is `fullName` customisation? A very clean approach would be a config option where we could define a template. See, problem -> solution. Not applicable anymore because we won't have this structure in the new version, as stated in #150.

>however it would not solve our requirement for a username as loginbase.

With the new structure you will be able to publish the migration / form / table template and add remove fields as you desire.

Regarding fillable we could add a config option for user `fillable`, or change in the `User` model `$guarded = ['password']`

In the end `fillable =[* except pass]` `===` `guarded = ['password]`, matching what we have now. 

But don't you need validation on the username? What happens when somebody creates a new user with an invalid username?!

Any other angles?

**Comment by jlsjonas** [comment]
>But don't you need validation on the username? What happens when somebody creates a new user with an invalid username?!

Validation is done by [adldap2](https://github.com/Adldap2/Adldap2-Laravel), creation will only happen by bulk import (from M$ NAV) or by login (with default roles/owners that prevent _unauthorized_ access; showing a page to contact an admin for permissions instead)

Can't wait to see how #150 turns out in that case; I hope it solves all the issues (without creating new ones; or too many joins slowing things down on every request; as we have an imported _`user_data`_ coming from NAV too)

**Comment by aocneanu** [comment]
>creation will only happen by bulk import

So you don't event use the forms/controllers for creating users. You can get around the fillable in all sorts of ways when importing (I can think of 2-3 from the top of my head).

...
