### ISSUE TITLE
Upcoming changes in Enso

### ISSUE THREAD

**Issue by aocneanu** [laravel-enso/Enso#150]
We're working on a new version that will bring lots of changes, one of the most important being changing the way users are handled in Enso.

The new version will introduce a `people` structure that will be responsible with all the person's personal details.

The `User` model will have less attributes (moved in `Person` model) and will `belongTo` a `Person`. Not all people will have users.

The `owners` structure caused lots of confusion in the past, so we decided to rename to `user_groups` (what it is, in fact).

We will introduce also a `parties` concept. Every `Person` will `belongTo` to a `Party`. The new concept will allow having multiple entities in one application such as `Person`, `Company`, `Organisation`, `Public Administration` each belonging to a party. This will make possible all sorts of `partyRelations` where the relevant entities can interact.

With the new implementation a `Person` could have a `User`, and/or be a `Contact`, `Employee`, `Client` or anything else in a relationship with other entities from the app.

The new release will allow publishing the users' & persons' migration/form/table template which will give the possibility to add/customize fields for these structures.

The `teams` structure will be extracted from `Core` and moved to a dedicated package.

A `Companies` package will be created.

Will update this ticket with more info on the way...

Updates:

- an upgrade command will be provided to ensure smooth migrations in existing apps. We will test and improve this command on our applications, so probably you shouldn't hurry...

- `first_name` / `last_name` columns and the `fullName` getter from `User` will be dropped in favor of `name` and `appellative` in `Person`. `appellative` will replace the deprecated `first_name` (FE, emails, tags etc).

**Comment by jlsjonas** [comment]
(as mentioned in #149)
As you're going to abstract the user I'd recommend allowing multiple `Person`s per `User`.

#### possible implementation method: 
We added a dropdown in the navbar to switch between the different _`Person`s_ matching the `User` in our custom implementation; which can be smartly hidden if there's only a single relationship.

As for preformance/usability you could add a config flag to enable the `belongsToMany` with a `->person` => `belongsTo` & `->persons` => `belongsToMany`.
`Person`s (according to the description above) will already be a mtm so the added complexity would be minimal.

**Comment by aocneanu** [comment]
Please eloborate on the need for having multiple persons per user.

In our current WIP implementation we cannot do mtm because we decided to store the user's email in the users table and manage the link to the person's email "by hand"

**Comment by gandesc** [comment]
I agree that having multiple persons per user is a smell of sorts.

It might be that the current decision to have multiple persons per user will go away once the new structure is up, or we're missing something out of that picture.

**Comment by jlsjonas** [comment]
>because we decided to store the user's email in the users table and manage the link to the person's email "by hand"
Why though?
also it sounds that this would make our username-based approach a lot harder (the email is only known during login (stored in LDAP/AD only); not when provisioning data)

>or we're missing something out of that picture.

we have (a limited set of) users who are part of multiple _user_groups_; they log in using the same credentials but have different access levels depending on the _country_ (owner/user_group).
We're also dealing with different teams (regions) within each country, so I don't think the changes would elevate that need.

But even more generally, a _super admin_ (which it kind-of is; but more granular) could benefit from this approach too.

Either way I'd definitely link using known methods (based on id's) instead of doing it _by hand_; to avoid confusion + more indexing mess

**Comment by aocneanu** [comment]
We have a functional beta version up, tomorrow the changelog and upgrade steps will be ready.
