### ISSUE TITLE
404 on install

### ISSUE THREAD

**Issue by NettSite** [laravel-enso/Enso#151]
This is  a **help request**.

### Prerequisites
* [* ] Are you running the latest version?
* [* ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [* ] Did you check the documentation?
* [* ] Did you perform a cursory search?

### Description

I have just installed Laravel Enso following the instructions carefully which I found on "https://github.com/laravel-enso/Enso"  and when I tried Steo 5 (Login into the project with user: admin@laravel-enso.com, password: password) I got a 404 error.

1. First Step
Install Laravel & Enso according to instructions
2. Second Step
Navigate to the new app on my local PC using Chrome.
3. and so on...

I have created a domain in my "hosts" file for the app. I am getting a beautiful Laravel 404 message, so the hosts file is being effective.

### Expected behavior
I expected a login page

### Actual behavior
I got a 404

**Comment by aocneanu** [comment]
Hi,

Try to install a [fresh laravel](https://laravel.com/docs/5.7#installation) project just to see if it's something specific to you development environment or not.

**Comment by NettSite** [comment]
This is a completely fresh install, into an empty folder, as instructed. 

> Download the project with git clone https://github.com/laravel-enso/Enso.git
>
> Run in the project folder composer install
> 
> Configure the .env file. Run php artisan key:generate
> 
> Run php artisan migrate --seed
> 
> Login into the project with user: admin@laravel-enso.com, password: password

Several other Laravel projects on the same box work fine.

**Comment by aocneanu** [comment]
Ah ok.

Meanwhile I cloned Enso and it worked without problems.

Could you run phpunit to see if the tests pass?

**Comment by NettSite** [comment]
Stupid mistake on my part, I am sorry to waste your time! I forgot to restart Apache after creating the virtual server.

While you are here, I am going to try Enso with HYN Tenancy, to build a multi tenant app - do you think it will work, or is there a better approach?

**Comment by aocneanu** [comment]
NP :)

I don't see any limitations in adding HYN to Enso. Maybe you could share your experience once you move forward with it.

**Comment by NettSite** [comment]
Will do, thanks!
