### ISSUE TITLE
Upgrade steps description -- Address (& others)

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Enso#152]
This is  a **bug | feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

>To upgrade, manually replace the provided type property where the front-end component is used, replacing the old alias with the mapped class from the addresses.php config. Afterwards, remove the addressable key from the config.

Is pretty unclear; I can't find any changes in the Enso repo that indicate what changed either. Could you provide a code example or reference to a diff on what has to be changed exactly?

Thanks.

**Comment by aocneanu** [comment]
Sure, [new](https://github.com/laravel-enso/Enso/blob/master/resources/js/pages/administration/companies/Edit.vue#L10) vs [old](https://github.com/laravel-enso/Enso/blob/48817e02997c40981d22c66313e15339769469c0/resources/js/pages/administration/owners/Edit.vue#L10)

**Comment by jlsjonas** [comment]
Thanks 🙇  _updates docs to include link to https://github.com/laravel-enso/Enso/commit/be5743c80bf028468ae5dbf30956b5c87d30c634#diff-c55ea2ae73bcf4f5d68ad75da15d5546

**Comment by jlsjonas** [comment]
Related note: (don't want to polute the repos with 3 identical issues for such a small fix)
![image](https://user-images.githubusercontent.com/932193/46719756-07da8e00-cc6f-11e8-84fa-fcb8ba2d4508.png)
looks like there are still a couple references to user.name (across Team, Comments & Discusion) although `name` now resides under `user.person.name` instead

**Comment by aocneanu** [comment]
Can we close this?
