### ISSUE TITLE
Faulty vendor:publish command

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Enso#153]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

![image](https://user-images.githubusercontent.com/932193/46674458-7ae6f480-cbdc-11e8-8909-0d71ea98cbe9.png)

### Steps to Reproduce
1. Upgrade to 11.12[.2]
2. Follow CHANGELOG.md upgrade steps (maybe related to #152? couldn't find anything to change as we didn't extend applicable packages yet; except for core usage of them)
3. Log in, note a blank menu & above errors

### Expected behavior

App to work

### Actual behavior

Enso-part of app mostly non-functional (blank menu, notification menu broken, ...)

**Comment by jlsjonas** [comment]
Also note that (as documented in the changelog) every instance of `isActive` was replaced with `ActiveState`; I don't see any discrepancies there though
![image](https://user-images.githubusercontent.com/932193/46677050-19298900-cbe2-11e8-918f-ab2a73151374.png)
![image](https://user-images.githubusercontent.com/932193/46677111-3f4f2900-cbe2-11e8-8ec8-fe68e0adfbef.png)

**Comment by jlsjonas** [comment]
50% solved, `:is-active` had to be replaced with `:active-state` too!

now the only remaining issue seems to be `Notification.Vue` not being updated correctly somehow (I force-published enso-assets multiple times which didn't update Notification.Vue; any reason for the cause of this?

**Comment by aocneanu** [comment]
Sorry, changing the contact from is-active to active-state was not intended. I will fix this.

**Comment by aocneanu** [comment]
@jlsjonas I just checked, it seems that you replaced all instances of `IsActive` without taking in consideration the (letter) casing...

![image](https://user-images.githubusercontent.com/16073274/46716053-2179d680-cc6b-11e8-8eb8-c1c7ccfa9c09.png)

The resources from [Contacts](https://github.com/laravel-enso/Contacts/blob/master/src/resources/js/components/enso/contacts/Contact.vue#L6) are fine

**Comment by aocneanu** [comment]
>now the only remaining issue seems to be Notification.Vue not being updated correctly somehow (I force-published enso-assets multiple times which didn't update Notification.Vue; any idea what's the cause of this?

try to manually delete the file from your project (resources) and republish without force and see what happens

>missing required prop ActiveState & missing routes after 11.12 upgrade

What routes?

**Comment by jlsjonas** [comment]
>try to manually delete the file from your project (resources) and republish without force and see what happens

Will try & report back

>What routes?

The notification-related ones (as they're renamed)

**Comment by jlsjonas** [comment]
> it seems that you replaced all instances of IsActive without taking in consideration the (letter) casing...

I did check match casing... but I see in the git logs that PHPStorm messed up apparently 😅 

Is it possible that there are no matches then in a _reasonably default_ project?

> try to manually delete the file from your project (resources) and republish without force and see what happens

```bash
php artisan vendor:publish --tag='enso-assets'
Publishing complete.
```
Nothing happened (neither with --force); file didn't come back

**Comment by jlsjonas** [comment]
I tried publishing notification-assets instead; but upon further investigation there's no `.Vue` file in the publishable resources
![image](https://user-images.githubusercontent.com/932193/46718682-3d31ac80-cc6c-11e8-88e7-719a37d08968.png)

**Comment by jlsjonas** [comment]
![image](https://user-images.githubusercontent.com/932193/46718771-87b32900-cc6c-11e8-9795-c4c8658b6399.png)
publishing core-assets manually (no force) did work
enso-assets missing a core reference? or maybe doing some weird pathing?

**Comment by jlsjonas** [comment]
I found the publishing issue... the CLI should **NOT** have quotes (which explains why the composer update-included publish often didn't work as expected
![image](https://user-images.githubusercontent.com/932193/46719072-5424ce80-cc6d-11e8-9177-9bb9e535729e.png)

Thanks to [this](https://stackoverflow.com/a/48569497/620141) SA answer

**Comment by aocneanu** [comment]
Can we close this?

**Comment by jlsjonas** [comment]
It was waiting for that PR... so yes we can now
