### ISSUE TITLE
Enso doesn't always realize session expiry

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Enso#157]
This is  a **bug**. (for sure, for once 😇 )

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

When the session is expired (example: leaving a tab open overnight), if you try to continue browsing you receive blank pages. when inspecting the network traffic the api get's back with a `Call to a member function cannot() on null` which originates from
```php
...
        return auth()->user()
            ->cannot('access-route', $route);
    }
```

When refreshing the page, you are redirected to the login screen.

### Steps to Reproduce
1. Log in & leave the tab open
2. Wait for session expiry
3. click on a menu item (in my case, a `.index` route => table)

### Expected behavior

redirect to login screen

### Actual behavior

blank pages & api errors (see Description)

**Comment by jlsjonas** [comment]
Note: it seems that resizing the window triggered a call to api/meta which (correctly) redirected to login.

**Comment by aocneanu** [comment]
unable to replicate
