### ISSUE TITLE
Want to contribute Dutch localisation, but I need advice

### ISSUE THREAD

**Issue by llevering** [laravel-enso/Enso#16]
For Laravel Enso I would like to contribute a Dutch(NL) translation. However I am a bit confused as where I  can contribute.

Core(/Enso) -> Contains translations but not the migration for the localisation table, so making a PR with the translations + migration(insert) will give migration errors for user that do not use the localisation logic
Localisation -> Contains the migrations, however not the translation files

I can split the addition of the translation in two seperate PR's for the Localization and Core repositories, however that might create a mismatch when not both of them are pulled at once.

For me all options work though, I would just like to know your preference and I will adjust my PR(s).

**Comment by mauthi** [comment]
I would like to do the same in German (DE)...

**Comment by aocneanu** [comment]
Hi, that's great news, thank you both :)

@llevering you make a good point. I suppose that we could move the translations from core to localisation and keep everything related to localisation in one package. It feels more natural and does not break anything.

This means that the localisation service provider will publish everything related to translations.
 
Right now the core package contains the following for each language:

- 1 json file for laravel, in the root of lang folder
- 4 laravel lang files (auth, pagination, passwords, and validation), under the language folder
- 1 json file for datatables, under the dt-lang folder

All of the above should be moved to the localisation package.

In the future we will address flatpickr, but we're not 100% sure that we will stick with this library for calendar.

And of course, if you want, you can make a PR for this.

**Comment by aocneanu** [comment]
So, I moved everything and updated the main project.

You can go on with the localisation addition.

Cheers
