### ISSUE TITLE
PostgreSQL does not have IF(), use CASE instead

### ISSUE THREAD

**Issue by paulmaessen** [laravel-enso/Enso#161]
This is  a bug.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
When using PostgreSQL as the database for Laravel Enso an error occurs when trying to show the contents of the people-table: 

SQLSTATE[42883]: Undefined function: 7 ERROR:  function if(boolean, integer, integer) does not exist
LINE 1: select people.*, people.id as "dtRowId", if(users.id is null...

### Steps to Reproduce

Set Postgresql as the default database.
Open the people-list.

### Expected behavior
Instead of using IF() you should use the SQL-standard CASE

### Actual behavior
No people-records are visible in the table

**Comment by aocneanu** [comment]
Can you open a PR for this?

**Comment by paulmaessen** [comment]
Sorry I am not really familiar with PR's.

I can describe what you can do to fix it:

In the Person management dependency-repo you need to change in the following file: 

app/Http/Controllers/PersonTableController.php

Change:

    public function query()
    {
        return Person::select(\DB::raw(
                'people.*, people.id as "dtRowId", if(users.id is null, 0, 1) as user'
            ))->leftJoin('users', 'people.id', '=', 'users.person_id');
    }

Into:

    public function query()
    {
        return Person::select(\DB::raw(
                'people.*, people.id as "dtRowId", CASE WHEN users.id is null THEN 0 ELSE 1 END as user'
            ))->leftJoin('users', 'people.id', '=', 'users.person_id');
    }
