### ISSUE TITLE
demo site login page broken since 2.13.11

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Enso#166]
This is  a **bug**.

### Prerequisites
N/A

### Description

![image](https://user-images.githubusercontent.com/932193/48335233-6b385100-e65d-11e8-86ba-d2676732354a.png)

### Steps to Reproduce
1. go to laravel-enso.com

### Expected behavior

proper styling

### Actual behavior

broken css links

**Comment by aocneanu** [comment]
you just have to login once and toggle the themes. It's not broken, it's just your local storage pointing to the old theme.

**Comment by aocneanu** [comment]
fixed. It was something related to our deploy process
