### ISSUE TITLE
Is possible to publish the core models?

### ISSUE THREAD

**Issue by albertosgz** [laravel-enso/Enso#167]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
I want to integrates multi tenancy in Enso project, but I don't how to get the models published in order to customized them.
I know how to look for them through the vendor directory, but if I copy them I'm worry that colision with the vendor ones (other than is not elegant).
My idea is to use https://laravel-tenancy.com/ (https://github.com/hyn/multi-tenant/tree/5.x). If you know other suites, ideas are more than welcomed.
Thanks!

### Steps to Reproduce
After install Enso project and get last version, how to publish the models?

### Expected behavior
Some artisan command to publish them.

### Actual behavior
I don't know how to do it.

**Comment by aocneanu** [comment]
Why don’t you extend them?

**Comment by albertosgz** [comment]
It's a nice idea! 
So, other than extend models, I would need to change route and controllers (or extend them too) to make use of new models, right?

**Comment by aocneanu** [comment]
The clean way would be extending and adding routes and controllers for extra actions.

If you need total customization then override all the routes and create your own local structure (model, controllers, formbuilder, tablebuilder, validations etc)

**Comment by albertosgz** [comment]
I will try first to extend models, and try to use the same structure. Maybe I have to change controllers and some routes, but I hope is easy.
If I have more problems I will open new issue.
I think I can close this thread. 
Thank you Adrian.
