### ISSUE TITLE
How to safe update an Enso Environment?

### ISSUE THREAD

**Issue by elysiopires** [laravel-enso/Enso#170]
This is a question... How is the safest way to maintain your Enso Application updated?
I comparing the latest composer.json with mine and have huge changes on it, especially the laravel-framework version to 5.7

Is it safe to replace the package.json and composer.json and then composer update/yarn
or will be some breakchanges?

### Prerequisites
* [ ] Are you running the latest version? 5.6
* [ ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

**Comment by aocneanu** [comment]
[docs](https://docs.laravel-enso.com/guide/usage.html#updates)

When you are upgrading follow **always** the notes from the [changelog](https://github.com/laravel-enso/Enso/blob/master/CHANGELOG.md)

For easier tracking you can add the Enso version to the commit comment

**Comment by aocneanu** [comment]
Can we close this?
