### ISSUE TITLE
Laravel Enso as a backend API?

### ISSUE THREAD

**Issue by NinioDev** [laravel-enso/Enso#172]
Hello!
I'll be happy for your suggestion here.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Hi, I have a small question where I need your input:
I have a website which built with this awesome ENSO system, this website have a backend API (which is should not be connected to the front-end ENSO system), we are connecting and grabbing data from external servers to our db.

We wonder if we should develop this backend (complicated, with many files, including many horizon jobs and auto-scaling) API ONLY over the ENSO system, or, we should work with external Laravel API system (such as Laravel APITO etc), which means, different servers with different code.

What do you think? I'm appreciate your help here.

**Comment by aocneanu** [comment]
From a technical point of view, having Enso already in place for the website, you could easily supplement the backend routes / controllers / resources with the one needed for your api. If you do that make sure that you apply the appropriate middleware & middleware groups over these routes (eg: you won't need Enso's `core` middleware group). You will also have to tackle the api auth.

You should take this path if the business logic / resources between the website and the api are "interpolating". But probably if they were completely separate there would be no question in the first place.

**Comment by NinioDev** [comment]
It was very helpful, Thank you @aocneanu
