### ISSUE TITLE
Installed latest version. But I can't create users... How can I enable that?

### ISSUE THREAD

**Issue by elysiopires** [laravel-enso/Enso#173]
This is a question about Enso Users creation...
Installed the latest version. But I can't create users... How can I enable that?

When I try to access the address http://myip/administration/users/create I receive 404.

### Prerequisites
* [X] Are you running the latest version? Yes
* [X] Are you reporting to the correct repository? Yes
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [X] Did you check the documentation? Yes
* [X] Did you perform a cursory search? Yes

**Comment by 1988114** [comment]
I believe you have to do it from the people menu, select a person on the people index and then select the option to create a user of the selected person.

**Comment by elysiopires** [comment]
Thx @1988114
