### ISSUE TITLE
Incorrect `date-fns` version in package.json

### ISSUE THREAD

**Issue by br3athein** [laravel-enso/Enso#174]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
Latest release, which is [2.13.7](https://github.com/laravel-enso/Enso/commit/635bc5489159a3483a64172fba2e1e05cab37914), aims to update [date-fns](https://github.com/date-fns/date-fns) to the latest version, but dependencies in `package.json` appear to be broken while using `npm` to manage dependencies. I'm not that familiar w/ `npm` and `yarn` as package managers, but I've figured that `hu` locale that was introduced in `laravel-enso@2.13.7` is not present in `date-fns@2.0.0-alpha.7` - it was introduced in version [2.0.0-alpha.18](https://gist.github.com/kossnocorp/a307a464760b405bb78ef5020a4ab136#v200-alpha18), thus the current `package.json` requirement is invalid.

### Steps to Reproduce
as the [upgrade guide](https://github.com/laravel-enso/Enso/blob/635bc5489159a3483a64172fba2e1e05cab37914/CHANGELOG.md#21317) states,
> * update in your package.json `"date-fns": "^2.0.0-alpha.7"`
> * run `yarn install`

(though the actual command was `npm install` since we're using `npm`)

### Expected behavior
`npm run dev` rebuilds the frontend part properly

### Actual behavior
`npm run dev` fails to succeed, claiming that it is impossible to find `hu` locale in the current installation of `date-fns` package:
`Module not found: Error: Can't resolve 'date-fns/esm/locale/hu' in '.../web/resources/js/modules/enso/plugins/date-fns'`

**Comment by aocneanu** [comment]
I think there's a mistake in the Changelog.

Run `npm list | grep date-fns` and check that the version is above alpha.7, it probably isn't

Run `npm update`, recompile and report back.

Thanks

**Comment by br3athein** [comment]
from a fresh checkout, I've issued `npm install` - that installed `date-fns@2.0.0-alpha.7`, which was the output of `npm list | grep date-fns` - `npm run dev` failed to compile:
`Module not found: Error: Can't resolve 'date-fns/esm/locale/hu' in '...web/resources/js/modules/enso/plugins/date-fns'`

later on, `npm update` fixed the issue by installing `date-fns@2.0.0-alpha.26`, but it had a quite heavy impact on a `package-lock.json`:
```
npm WARN prosemirror-utils@0.6.7 requires a peer of prosemirror-tables@^0.6.5 but none is installed. You must install peer dependencies yourself.
npm WARN img-loader@3.0.1 requires a peer of imagemin@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ animate.css@3.7.0
+ flag-icon-css@3.2.1
+ css-element-queries@1.1.1
+ bulmaswatch@0.7.2
+ chart.js@2.7.3
+ cross-env@5.2.0
+ eslint-plugin-vue@4.7.1
+ babel-eslint@8.2.6
+ bulma-extensions@2.2.2
+ date-fns@2.0.0-alpha.26
+ highlight.js@9.13.1
+ laravel-echo@1.5.2
+ lodash@4.17.11
+ pusher-js@4.3.1
+ tooltip.js@1.3.1
+ popper.js@1.14.6
+ flatpickr@4.5.2
+ raven-js@3.27.0
+ v-tooltip@2.0.0-rc.33
+ laravel-mix@2.1.14
+ vue-router@3.0.2
+ vue@2.5.21
+ video.js@7.4.1
added 69 packages from 79 contributors, removed 496 packages, updated 229 packages, moved 7 packages and audited 12562 packages in 22.015s
found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```

I've tried upgrading `date-fns` precisely w/ `npm install date-fns` - `npm run dev` responded w/ a really long [error log (attached)](https://github.com/laravel-enso/Enso/files/2737283/npmrundev.log)

although the `npm update` solves the problem locally, I think it would be better to have the `package-lock.json` updated and commited to upstream and prevent the (potentially project-breaking in a long term) ceremony of updating the project w/ `npm update` before one is able to spin it up :slightly_smiling_face:

**Comment by jlsjonas** [comment]
[They already seem to be doing this](https://github.com/laravel-enso/Enso/commit/635bc5489159a3483a64172fba2e1e05cab37914) (as they use yarn)

Food for thought:
Note that I was using npm too but decided to switch our stack to yarn recently as some _npm weirdness_ caused a dependency of a dependency not to be updated; which broke the dependency's update and thus in turn the entire project. A clean install worked fine while an update consistently broke (although the respective package.json's all seemed correct, pointing to a semver-matching _updatable_ version) yarn didn't have any issues with this when given the same situation.

**Comment by br3athein** [comment]
@jlsjonas thanks for the input :slightly_smiling_face:
 
then it appears that `package-lock.json` is there only to confuse people, since that's commonly used by `npm` - especially if that lock is outdated. IMO, having two different lockfiles generated by a similar-purpose package managers is quite dangerous - @aocneanu, maybe you should stick to single one instead?

N.B.: we were just thinking about switching to `yarn` the other day - seems like we're gonna give it a try :cat:

**Comment by aocneanu** [comment]
I guess we can close this.
