### ISSUE TITLE
Vue & vue-template-compiler mismatch (caused by dependencies?)

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Enso#176]
This is  a **bug**.

### Prerequisites
* [ ] Are you running the latest version? (upgrading to latest)
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

This issue only occurs after an npm update/yarn upgrade (at first I thought it was npm-specific)
clearing out `node_modules` and then again running `npm install` or `yarn` mitigates this issue.
Meaning there must be some _internal dependency battle_ happening.

### Steps to Reproduce
1. Start out from previous version (I was coming from 2.13.16)
2. execute 2.14.0 upgrade steps, specifically `yarn upgrade` followed by `yarn run dev`
3. above error on a lot of files, f.e. `ERROR in ./resources/js/components/enso/bulma/toastr/Notification.vue`

### Expected behavior

no version mismatch

### Actual behavior

```bash
Module build failed: Error:

Vue packages version mismatch:

- vue@2.5.22
- vue-template-compiler@2.5.21

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
```

possibly related to discussions in #174

**Comment by jlsjonas** [comment]
🤔 further inspecting the yarn.lock it is stating both packages under version `2.5.22`; yarn & npm bug after all?

**Comment by aocneanu** [comment]
in a few days we'll start ignoring the compiled assets and we will start building in the deployment process.
