### ISSUE TITLE
php artisan make:enso:structure not working

### ISSUE THREAD

**Issue by bleeuwen** [laravel-enso/Enso#178]
Would like to use the CLI-command make:enso:structure, but I get an error.
Do I have to install this feature separately??

I refer to: 
_The CLI is done. After updating to the latest version use `php artisan make:enso:structure` to generate all the needed files for a new structure.

_Originally posted by @aocneanu in https://github.com/laravel-enso/Enso/issues/110#issuecomment-403211964__

**Comment by aocneanu** [comment]
we have an issue template

**Comment by bleeuwen** [comment]
I used the template. Do you want my output?

**Comment by aocneanu** [comment]
this is the template

![image](https://user-images.githubusercontent.com/16073274/51523504-787b7400-1e34-11e9-9153-440ee5457914.png)

please also read all the instructions from the template

**Comment by aocneanu** [comment]
also look at other open issues...

**Comment by jlsjonas** [comment]
@bleeuwen go to https://github.com/laravel-enso/Enso/issues/new, he's referring to the issue template.

Regarding his comment on the referenced issue: you can perfectly work on windows for development, however for the composer install & update steps you have to add `--ignore-platform--reqs`
This also means that horizon won't be fully functional (but for development you have this set to sync by default)

**Comment by bleeuwen** [comment]
Hi

I am impressed by the Laravel Enso package. I no quite somethings of Symfony and Laravel.

But I get stuck in creating an own table above the Enzo package.

I use the StuctureManager CLI and created my objects, but then I get lost.

Is there somewhere a tutorial that covers this issue completely??

Beste regards

Bart van Leeuwen
>

**Comment by jlsjonas** [comment]
I personally recommend using git to track changes, that way you can see what files got created and what's in each of them.
notably: `ModelTable.php`, `ValidateModelRequest.php`, the database migrations, the snipped shared via console to add to `api.php` & the .json models (in `app\forms` & `app\table`)
Referencing existing versions of those files along with the documentation to comprehend how everything works together
