### ISSUE TITLE
When I transfer my files to server I got this error "View [themes.enso] not found." when try to export to excel

### ISSUE THREAD

**Issue by elysiopires** [laravel-enso/Enso#179]
This is  a **bug **.

### Prerequisites
* [ ] Are you running the latest version?No 2.13.15
* [ ] Are you reporting to the correct repository?Yes
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ ] Did you check the documentation? Yes
* [ ] Did you perform a cursory search? Yes

### Description
When I try to export data on index route using the button Excel I receive the folowing error:
`{
    "message": "View [themes.enso] not found.",
    "exception": "InvalidArgumentException",
    "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php",
    "line": 137,
    "trace": [
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php",
            "line": 92,
            "function": "findInPaths",
            "class": "Illuminate\\View\\FileViewFinder",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php",
            "line": 76,
            "function": "findNamespacedView",
            "class": "Illuminate\\View\\FileViewFinder",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/View/Factory.php",
            "line": 130,
            "function": "find",
            "class": "Illuminate\\View\\FileViewFinder",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Mail/Markdown.php",
            "line": 64,
            "function": "make",
            "class": "Illuminate\\View\\Factory",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php",
            "line": 97,
            "function": "render",
            "class": "Illuminate\\Mail\\Markdown",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php",
            "line": 63,
            "function": "buildView",
            "class": "Illuminate\\Notifications\\Channels\\MailChannel",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php",
            "line": 144,
            "function": "send",
            "class": "Illuminate\\Notifications\\Channels\\MailChannel",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php",
            "line": 103,
            "function": "sendToNotifiable",
            "class": "Illuminate\\Notifications\\NotificationSender",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php",
            "line": 19,
            "function": "Illuminate\\Notifications\\{closure}",
            "class": "Illuminate\\Notifications\\NotificationSender",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php",
            "line": 105,
            "function": "withLocale",
            "class": "Illuminate\\Notifications\\NotificationSender",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php",
            "line": 77,
            "function": "sendNow",
            "class": "Illuminate\\Notifications\\NotificationSender",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php",
            "line": 39,
            "function": "send",
            "class": "Illuminate\\Notifications\\NotificationSender",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php",
            "line": 18,
            "function": "send",
            "class": "Illuminate\\Notifications\\ChannelManager",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel-enso/vuedatatable/src/app/Jobs/ExcelExport.php",
            "line": 89,
            "function": "notify",
            "class": "LaravelEnso\\Core\\app\\Models\\User",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel-enso/vuedatatable/src/app/Jobs/ExcelExport.php",
            "line": 43,
            "function": "notify",
            "class": "LaravelEnso\\VueDatatable\\app\\Jobs\\ExcelExport",
            "type": "->"
        },
        {
            "function": "handle",
            "class": "LaravelEnso\\VueDatatable\\app\\Jobs\\ExcelExport",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php",
            "line": 29,
            "function": "call_user_func_array"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php",
            "line": 87,
            "function": "Illuminate\\Container\\{closure}",
            "class": "Illuminate\\Container\\BoundMethod",
            "type": "::"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php",
            "line": 31,
            "function": "callBoundMethod",
            "class": "Illuminate\\Container\\BoundMethod",
            "type": "::"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Container/Container.php",
            "line": 572,
            "function": "call",
            "class": "Illuminate\\Container\\BoundMethod",
            "type": "::"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php",
            "line": 94,
            "function": "call",
            "class": "Illuminate\\Container\\Container",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 116,
            "function": "Illuminate\\Bus\\{closure}",
            "class": "Illuminate\\Bus\\Dispatcher",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 104,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php",
            "line": 98,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php",
            "line": 49,
            "function": "dispatchNow",
            "class": "Illuminate\\Bus\\Dispatcher",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php",
            "line": 83,
            "function": "call",
            "class": "Illuminate\\Queue\\CallQueuedHandler",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php",
            "line": 42,
            "function": "fire",
            "class": "Illuminate\\Queue\\Jobs\\Job",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php",
            "line": 184,
            "function": "push",
            "class": "Illuminate\\Queue\\SyncQueue",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php",
            "line": 160,
            "function": "pushCommandToQueue",
            "class": "Illuminate\\Bus\\Dispatcher",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php",
            "line": 73,
            "function": "dispatchToQueue",
            "class": "Illuminate\\Bus\\Dispatcher",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php",
            "line": 112,
            "function": "dispatch",
            "class": "Illuminate\\Bus\\Dispatcher",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php",
            "line": 16,
            "function": "__destruct",
            "class": "Illuminate\\Foundation\\Bus\\PendingDispatch",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel-enso/vuedatatable/src/app/Traits/Excel.php",
            "line": 23,
            "function": "dispatch",
            "class": "LaravelEnso\\VueDatatable\\app\\Jobs\\ExcelExport",
            "type": "::"
        },
        {
            "function": "excel",
            "class": "App\\Http\\Controllers\\Administration\\Operators\\OperatorTableController",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
            "line": 54,
            "function": "call_user_func_array"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
            "line": 45,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 219,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 176,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 682,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 30,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel-enso/localisation/src/app/Http/Middleware/SetLanguage.php",
            "line": 18,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "LaravelEnso\\Localisation\\app\\Http\\Middleware\\SetLanguage",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel-enso/permissionmanager/src/app/Http/Middleware/VerifyRouteAccess.php",
            "line": 20,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "LaravelEnso\\PermissionManager\\app\\Http\\Middleware\\VerifyRouteAccess",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel-enso/impersonate/src/app/Http/Middleware/Impersonate.php",
            "line": 19,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "LaravelEnso\\Impersonate\\app\\Http\\Middleware\\Impersonate",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel-enso/actionlogger/src/app/Http/Middleware/ActionLogger.php",
            "line": 19,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "LaravelEnso\\ActionLogger\\app\\Http\\Middleware\\ActionLogger",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel-enso/core/src/app/Http/Middleware/VerifyActiveState.php",
            "line": 20,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "LaravelEnso\\Core\\app\\Http\\Middleware\\VerifyActiveState",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php",
            "line": 41,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php",
            "line": 43,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "Illuminate\\Auth\\Middleware\\Authenticate",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php",
            "line": 75,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php",
            "line": 49,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "Illuminate\\View\\Middleware\\ShareErrorsFromSession",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php",
            "line": 63,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "Illuminate\\Session\\Middleware\\StartSession",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php",
            "line": 37,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php",
            "line": 66,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\EncryptCookies",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 104,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 684,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 659,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 625,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 614,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 176,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 30,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/fideloper/proxy/src/TrustProxies.php",
            "line": 57,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "Fideloper\\Proxy\\TrustProxies",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 31,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 31,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
            "line": 62,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 151,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 104,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 151,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/home/myproject/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 116,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/home/myproject/public/index.php",
            "line": 55,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        }
    ]
}`

### Expected behavior
Generate the Excel File

### Actual behavior
Received error:
"message": "View [themes.enso] not found.",
    "exception": "InvalidArgumentException",

**Comment by elysiopires** [comment]
I figured out how to solve the problem the mail templates inside /resources/views/vendor are missing on my server.

I found another error too related to the size of telescope content field. I had to change it to MEDIUMTEXT.

After that everything is good! 👍

**Comment by aocneanu** [comment]
Glad I could help :))

(jk)
