### ISSUE TITLE
Theming the Enso Project

### ISSUE THREAD

**Issue by elysiopires** [laravel-enso/Enso#180]
This is  a **Question**.

### Prerequisites
* [ ] Are you running the latest version?No 2.13.15
* [ ] Are you reporting to the correct repository? Yes
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ ] Did you check the documentation? Yes
* [ ] Did you perform a cursory search? Yes

### Description
What is the guidelines to theme an enso project, change colors, create themes?

**Comment by aocneanu** [comment]
Are you looking to add a new theme besides the light / dark or just change the existing?

**Comment by elysiopires** [comment]
I tried to change the existing without success.

I would like to know both create a theme and change the exists one :)

Thx in advance!

**Comment by aocneanu** [comment]
To change an existing one you can overwrite `resources/sass/themes/light.scss` (or dark)

Customization should be according to Bulma's guide (https://bulma.io/documentation/customize/)

Note that on every composer update your changes will be overwritten so you will have to overcome this on your own.

@gandesc we will post add a section in `core`'s documentation with a convenient way to manage customized assets... soon

**Comment by jlsjonas** [comment]
FYI: the way we currently manage customizations:
in composer.json, we added a few extra steps to the `post-update-cmd`: (relying on git for a cleaner overview)
```json
            "git add .",
            "git commit -m \"composer/Enso upgrade\"",
            "cp -f -r resources/customized/* resources/",
            "echo amend commit with customized changed"
```
in explanatory: 
- add all items to git & commit them locally (this commits all upstream changes, **without** any of our overridden customizations)
- copy all customized resources in place (every time we customize an item we copy it into the same structure under the _customized_ directory, f.e. `resources/sass/themes/light.scss` would go into `resources/customized/sass/themes/light.scss`)
- at this point we compare our working directory with the newly created commit above, to see if any of the upstream changes have to be included into our version
- when finished, we amend the above commit with the resulting files, ending with a single "upgrade" commit indicating all actual changes

**Comment by aocneanu** [comment]
Yes, of course.

**Comment by aocneanu** [comment]
Can we close this?
