### ISSUE TITLE
[Vue warn]: Missing required prop: "path"

### ISSUE THREAD

**Issue by lsosa3** [laravel-enso/Enso#181]
This is  a **bug**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

### Description

Hi guys, i used the Structure Manager to add a new CRUD, the list works fine, but i encounter this issue when i edit the json template file, can you guide me to solve this please.

[Vue warn]: Missing required prop: "path"

found in

---> <VueForm> at resources/js/components/enso/vueforms/VueForm.vue
       <Create> at resources/js/pages/personal/Create.vue
         <Router> at resources/js/core/Router.vue... (1 recursive calls)
           <Default> at resources/js/core/layouts/Default.vue
             <Root> 

Great project by the way!!!

**Comment by aocneanu** [comment]
1. Are you running the latest version?

2. Are you reporting to the correct repository (No, the correct repo should be StructureManager)

...
Please open a new ticket on the dedicated package, fill the issue template and also post the content of the `Create.vue` file that causes this problem

**Comment by jlsjonas** [comment]
You likely forgot to paste the resource details in api.php; had this exact error when I forgot it on one of the created structured today ;-)
