### ISSUE TITLE
Build stuck at 70%

### ISSUE THREAD

**Issue by lsosa3** [laravel-enso/Enso#183]
This is  a **bug | feature request**.

### Prerequisites
* [y] Are you running the latest version?
* [y] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [y] Did you check the documentation?
* [y] Did you perform a cursory search?

### Description

Hi, i download the latest version of laravel-enso to make sure about the [Vue warn]: Missing required prop: "path" issue, but now i encounter this one, my building process get stuck at 70%, i check out that the webpack.mix.js file is diferent but i don't know where to look to fix this. 
Any guide please

### Steps to Reproduce

Clone laravel-enso
composer install
npm install
php artisan serve
php artisan enso:make:structure (Perform all the steps needed)
npm run dev

### Expected behavior

build app

### Actual behavior

Get stuck at 70% build
![seleccion_001](https://user-images.githubusercontent.com/14814335/51723765-c0ff8100-2030-11e9-83ac-7a4395d0de33.png)

**Comment by aocneanu** [comment]
what laravel-mix / webpack are you using?

**Comment by aocneanu** [comment]
also what yarn / node versions?

**Comment by lsosa3** [comment]
└─┬ laravel-mix@4.0.14
  └── webpack@4.29.0 

node  v9.11.2

**Comment by lsosa3** [comment]
> I lost half of yesterday with this issue.

Yeah been there...


Thank you, now everything works fine and the '[Vue warn]: Missing required prop: "path"' error is gone too
