### ISSUE TITLE
reduced build times... or not?

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Enso#184]
This is  a **bug | question**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

2.15.1 changelog states
>In this version we focused on greatly improving the assets compiling process. With the new configuration build times dropped by ~ 75% for production.

While I do fully understand this is focussed on production build times, it seems that dev build times actually slowed down by about 20% during 2 tests. Is this known/intended?

### Expected behavior

same or faster dev build times

### Actual behavior

slower dev build times

**Comment by aocneanu** [comment]
Can we close this?

**Comment by jlsjonas** [comment]
🤔 you have 16sec dev compile times? is that a hot or cold compile time?
I'm was looking at about a minute cold-compile (& thus ~76s now)
might just be the fact that it's _only_ an i5 + windows in my work laptop though

**Comment by aocneanu** [comment]
lol? what's hot / cold?

i7@4.5 with 16GB Ram

![image](https://user-images.githubusercontent.com/16073274/51822592-807c5d80-22e5-11e9-9b25-ada63da58c4d.png)


I guess I exaggerated :D

**Comment by aocneanu** [comment]
so can we close this? :D

**Comment by jlsjonas** [comment]
hot = 2nd compile after `yarn hot`, cold is it's first compile or `yarn dev` compile time
I suppose we can indeed close this.

**Comment by aocneanu** [comment]
mbp pro 2018.

hot module replacement init (cached)
![image](https://user-images.githubusercontent.com/16073274/51823592-86c00900-22e8-11e9-99f9-21ab694a28b8.png)

average recompile time after changes
![image](https://user-images.githubusercontent.com/16073274/51823658-b242f380-22e8-11e9-9695-4e627fa94e18.png)
