### ISSUE TITLE
[Vue warn]: Error in data(): "Error: Route: route "xx" is not found in the route list"

### ISSUE THREAD

**Issue by bleeuwen** [laravel-enso/Enso#185]
This is  a **bug **.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
[Vue warn]: Error in data(): "Error: Route: route "administration.generalcodes.initTable" is not found in the route list"

### Steps to Reproduce
1. Installed Laravel/Enso conform instructions
2. created generalcodes conform laravel artisan:enso:make;structure
3. pasted the given routes in app.js
4. performed a migration
5. added a row to the table via MySql
6. php artisan route:list shows the route administration.generalcodes.initTable

### Expected behavior
contents of table generalcodes is showing

### Actual behavior
Get a blank screen with only the title.
F12 and console log shows:

[Vue warn]: Error in data(): "Error: Route: route "administration.generalcodes.initTable" is not found in the route list"

found in

---> <Index> at resources/js/pages/administration/generalcodes/Index.vue
       <Router> at resources/js/core/Router.vue... (2 recursive calls)
         <Default> at resources/js/core/layouts/Default.vue
           <Root> vue.common.js:612
Error: "Route: route "administration.generalcodes.initTable" is not found in the route list"
	validate webpack-internal:///639:86:15
	buildDomain webpack-internal:///639:41:7
	buildUrl webpack-internal:///639:35:17
	Route webpack-internal:///639:24:16
...... [complete output not shown)

**Comment by aocneanu** [comment]
When configuring the CLI did you:

1 - configured the permission group to `administration.generalcodes`
2 - selected the permissions for the table? (`initTable => ✗`, `tableData => ✗`)
when using the CLI did you selected all the needed files?
3 - configured the menu `General Codes`
4 - selected the appropriate files? `model, migration etc

After the above steps the configuration status should look like:

![image](https://user-images.githubusercontent.com/16073274/51784481-ec2dc180-2151-11e9-85bb-909d26640daf.png)

After pressing the 5 - Generate you should run `php artisan migrate`, compile and make sure you reload the page (F5) for the new routes to take effect on you role.

**Comment by aocneanu** [comment]
In Enso we use named routes and permission === route->name.

Can we close this now?

**Comment by bleeuwen** [comment]
Can be closed
