### ISSUE TITLE
Bookmark of current page missing if you reload page

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/Enso#187]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
Bookmark bar is empty if you reload page (via browser reload)

### Steps to Reproduce
1. Login
2. Reload page (CMD + R)

### Expected behavior
<img width="328" alt="screenshot 2019-02-01 09 02 47" src="https://user-images.githubusercontent.com/7204559/52110212-399da900-2600-11e9-81b7-4518c85dd3cb.png">

### Actual behavior
<img width="328" alt="screenshot 2019-02-01 09 02 59" src="https://user-images.githubusercontent.com/7204559/52110218-3efaf380-2600-11e9-9935-35ebb3a9fd40.png">

**Comment by aocneanu** [comment]
Yeah, it's a "known" bug :)

**Comment by aocneanu** [comment]
fixed in v3.
