### ISSUE TITLE
Public facing pages

### ISSUE THREAD

**Issue by curtisdelicata** [laravel-enso/Enso#188]
This is  a **feature request**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description
What would be the best approach to public facing pages? Should I copy the home page method? Middleware modification for the roles?

I have successfully created a form and table for administrators to publish properties and want to display properties on a public page.

**Comment by aocneanu** [comment]
You should add a route with a guest middleware and display that page, and probably change the home route to something like `app.io/admin`.

Why do you need roles for public pages?

**Comment by bleeuwen** [comment]
How can I change the home route??
I am a little confused between the standard Laravel settings and Enso settings

**Comment by aocneanu** [comment]
What do you mean by "change the home route"?

**Comment by bleeuwen** [comment]
Hi Adrian

You said in this topic:
You should add a route with a guest middleware and display that page, and probably change the home route to something like `app.io/admin`.

Therefore I asked you: how can I change the home route.

I see on different places in the code that a home route is set and I get the impression that login is the default home-route.

So this is the reason of my question.

My case is that I would like to show an introductionpage with a login button.
The introductionpage tells what the site is about and gives some instructions.

**Comment by aocneanu** [comment]
You can overwrite the route by defining in your project's `api.php` routes file a route with the same name.

**Comment by bleeuwen** [comment]
Too bad there is not a forum so that I can bring this up to be discussed.
I get too mixed up in routes, required routes in the route-table of Enso, to get this done.

Read a lot of tutorials, but Enso is set up differently.

So please is not there an explanation to set up something simple as a Welcome page?

**Comment by aocneanu** [comment]
@bleeuwen please open a new issue and explain what you tried to do and didn't work, and what's the expected result. Please be as explicit as you can, you can paste code, attach screen shots, whatever will help us give you a straight and clear answer. Thanks.

**Comment by bleeuwen** [comment]
I did: opened issue 197

**Comment by curtisdelicata** [comment]
Thank you Adrian.

Kind regards,
Curtis
