### ISSUE TITLE
Writing own login

### ISSUE THREAD

**Issue by bleeuwen** [laravel-enso/Enso#189]
This is  a ** feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

I want to add some aspects in the login procedure, but I do not want to tweak in the Laravel/Enso configuration. (People can login with a name and number, and the credentials are validated by calling an API with another website)

How can I fix that my own login procedure is executed in stead of the Laravel/Enso function??

Seems that I have to set some config parameters,  but can not find exactly how.

### Expected behavior

People enter their name and number. 
Via an API with another website I get the data belonging to that number and validate the given name.
When correct the user is authenticated the regular way, else I show a error-message.

**Comment by bleeuwen** [comment]
Another way to realise this is to change the fallback path to my own login procedure.
But how do I set the fall back path.

**Comment by aocneanu** [comment]
I think that the most easy way to achieve this is to update the projects `app/Http/Controllers/Auth/LoginController` according to your needs and also overwrite Enso's auth routes to point to the local controller

```
|        | POST          | api/login                                                | login                                   | LaravelEnso\Core\app\Http\Controllers\Auth\LoginController@login                                 | web,guest                                        |
|        | POST          | api/logout                                               | logout                                  | LaravelEnso\Core\app\Http\Controllers\Auth\LoginController@logout                                | web                                              |
|        | POST          | api/password/email                                       | password.email                          | LaravelEnso\Core\app\Http\Controllers\Auth\ForgotPasswordController@sendResetLinkEmail           | web                                              |
|        | POST          | api/password/reset                                       | password.reset                          | LaravelEnso\Core\app\Http\Controllers\Auth\ResetPasswordController@attemptReset                  | web
```

**Comment by bleeuwen** [comment]
Overwriting the routes did the trick
