### ISSUE TITLE
After Session has expired redirect back to old page after re-login

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/Enso#19]
It would be nice if you get back after re-login to last route you accessed and not to dashboard

**Comment by aocneanu** [comment]
closed with laravel-enso/core@4b893ae4a146627ba70694441b8c4232d8bc73e2

**Comment by mauthi** [comment]
can you check this again pls?
I published your new files (php artisan vendor:publish --tag=core-assets) but doesn't work... :(

**Comment by aocneanu** [comment]
Hi,

Did you published using the ‘—force’ flag? After publishing, did you compiled? ‘npm run dev’

**Comment by mauthi** [comment]
yes and yes

**Comment by aocneanu** [comment]
Ok, I’ll look into it.
