### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/Enso#191]
This is  a **question**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
I use an own custom theme. In general everything works like expected but I have 2 questions:
1. How is the default theme for login choosen? I deleted/commented every occurence of light/dark theme in code but still the light theme and not my default is choosen (after deleting cache and everything). If I log in and out my custom theme is choosen for login screen. I also set the theme in `index.blade.php`
2. What's the source for theme selector (` ...mapState('layout', ['themes']),`). The light/dark selector is shown in my app (what means that more than one theme is available)

**Comment by heyner29** [comment]
With the command `php artisan enso:preferences:clear` clean all preferences.
And in the views folder there is a preferences.json file I think you should put your custom theme.

**Comment by mauthi** [comment]
I did both before - no success

**Comment by jlsjonas** [comment]
Did you clear your local storage? If available it is used to set the default theme

Themes are set in `resources/js/store.js`, with data from `/api/core/home` (AppState.php).

Check your `config/enso/themes.php`.

**Comment by mauthi** [comment]
I cleared the local storage and tested with incognito browser window too.
In `config/enso/themes.php` the only valid entry is my theme.

> Themes are set in `resources/js/store.js`, with data from `/api/core/home` (AppState.php).
Here I get 3 themes but I don't know why:
`"themes": {
        "light": "/themes/light/bulma.min.css",
        "dark": "/themes/dark/bulma.min.css",
        "netwerker": "/themes/netwerker/bulma.min.css"
    },`

**Comment by aocneanu** [comment]
>1. How is the default theme for login choosen? I deleted/commented every occurence of light/dark theme in code but still the light theme and not my default is choosen (after deleting cache and everything). If I log in and out my custom theme is choosen for login screen. I also set the theme in `index.blade.php`

In Auth layout (login, reset) the theme is `light` by default. Once a user sets `dark` this is remembered in the localStorage and used in the future.

from layout.js

![image](https://user-images.githubusercontent.com/16073274/52421507-dbd7f800-2afc-11e9-9e1d-a60639b3e5fd.png)

>2\. What's the source for theme selector (` ...mapState('layout', ['themes']),`). The light/dark selector is shown in my app (what means that more than one theme is available)

The source is the `LaravelEnso\Core\app\Enums\Themes` Enum, that is correlated with `config/enso/themes.php`

**Comment by mauthi** [comment]
@1) How can I change this? I can't see `light` in your example code?

@2) This is my file:
![image](https://user-images.githubusercontent.com/7204559/52424565-91557c00-2afa-11e9-9f19-bd2673fea07c.png)
But in `this.themes`in Settings.vue I get all 3 themes?

**Comment by aocneanu** [comment]
You have a really old file - [current](https://github.com/laravel-enso/Enso/blob/master/config/enso/themes.php)

[This](https://github.com/laravel-enso/Core/blob/master/src/resources/views/index.blade.php#L8) is how the light is applied as default.

To change the default I guess we can add an option to the config and change the above tine to use the value from the config.

**Comment by mauthi** [comment]
> You have a really old file - [current](https://github.com/laravel-enso/Enso/blob/master/config/enso/themes.php)
I know, but the content is the same (I compared those 2 files during merge)

> To change the default I guess we can add an option to the config and change the above tine to use the value from the config.
That would be nice - thx.

But I still don't know why I get all 3 themes in `Settings.vue`.

**Comment by aocneanu** [comment]
The themes are built [here](https://github.com/laravel-enso/Core/blob/master/src/app/Http/Responses/AppState.php#L42)

Debug it.

**Comment by mauthi** [comment]
Found - the config from package gets merged with my app's config.

So we need a possibility to remove core themes from config via app config.
Suggestions?

**Comment by aocneanu** [comment]
I'm not sure that this is what we need. Tell me what you want to achieve, and maybe I can suggest a solution.

**Comment by mauthi** [comment]
From core package I get light and dark theme and as app developer I'm not able to disable them in my local config (if I want to disable default themes and use my own theme).
I think this is a general use case if somebody wants to build an app based on Enso?

**Comment by mauthi** [comment]
Thx
