### ISSUE TITLE
Have Multiple Layouts

### ISSUE THREAD

**Issue by soumilgada** [laravel-enso/Enso#192]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Need to have multiple layout as per URLs requested.

Created a new file in layouts and initialised in App.vue.
Also have a route which allow URL to execute with guestGuard:true inside meta

![screen shot 2019-02-07 at 4 09 14 pm](https://user-images.githubusercontent.com/664784/52406032-be9e2c00-2af2-11e9-9a69-b0771af6703d.png)

How do I switch based on URL and component selection ?
Layout being triggered is Auth instead of newly created

Would appreciate if you can guide me with steps to create, initiate new layout for set route.

Regards
Soumil Gada

**Comment by aocneanu** [comment]
[This](https://github.com/laravel-enso/Core/blob/master/src/resources/js/core/App.vue#L6) is where the layouts are set.

You will have to figure your own approach, as it has little to do with Enso.
