### ISSUE TITLE
Yarn.lock shouldn't point to fontawesome's pro repo

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Enso#193]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

https://github.com/FortAwesome/Font-Awesome/issues/12609#issuecomment-455647694
if you try to yarn install after cloning the current Enso:master you will receive an unexpected error from npm.fontawesome.com unless you have a pro key in your .npmrc

#123 is related but shouldn't be required as it could interfere with the integrity when in-between updates f.e.

### Steps to Reproduce
1. Clone enso master
2. yarn install without having a fontawesome pro api key

### Expected behavior

installation to succeed

### Actual behavior

npm.fontawesome.com 401

**Comment by aocneanu** [comment]
PR :)

**Comment by jlsjonas** [comment]
I can make a PR for the change Monday, however, it'll most likely require a local config change on your end (~/.npmrc) to avoid it being reflected on the next update again 😉

**Comment by aocneanu** [comment]
fixed
