### ISSUE TITLE
HMR is broken in laravel-mix 3.0

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/Enso#194]
This is  a **bug | feature request**. (upstream bug, so a feature request?)

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

laravel-mix 3.X is having major issues with HMR (been debugging all day, either the connection works but the script errors out, or updates ain't happening whatsoever); after more googling it seems that it's an issue with laravel-mix 3.0; which was introduced fairly recently (end of january).
This was fixed in a 4.X release (https://github.com/JeffreyWay/laravel-mix/issues/1834)

### Steps to Reproduce
1. yarn hot
2. go to the site, HMR not active or causing errors

### Expected behavior

HMR

### Actual behavior

![image](https://user-images.githubusercontent.com/932193/52412781-0b2c3c00-2ae0-11e9-8a15-2ca472c0f699.png)

**Comment by aocneanu** [comment]
unfortunately it won't work

https://laravel-mix.com/docs/4.0/upgrade

search for dynamic imports

**Comment by aocneanu** [comment]
https://github.com/laravel-enso/Enso/issues/183

**Comment by jlsjonas** [comment]
F... (I remember seeing that now that you link it 😅 )

back to 70 sec cycles via `yarn dev` for now, I guess (as the code no longer seems to be compatible with 2.1.11 which did work with HMR until then)

Just to verify, is HMR broken for you too? Or is it a ^#$^$%# windows issue again?

**Comment by aocneanu** [comment]
windows for sure.

**Comment by jlsjonas** [comment]
Great 😅 
well... thanks for the confirmation

**Comment by jlsjonas** [comment]
FYI: issue is related to [Vendor Extraction (`.extract`)](https://laravel.com/docs/5.7/mix#vendor-extraction)

tracking in https://github.com/JeffreyWay/laravel-mix/issues/1991 

workaround:
in `webpack.mix.js` replace the `resources/js/enso.js` definition with:
```js
if (Mix.isUsing('hmr')) {
    mix.js('resources/js/enso.js', 'public/js');
} else {
    mix.js('resources/js/enso.js', 'public/js')
        .extract([
            '@fortawesome/fontawesome-free', '@fortawesome/fontawesome-svg-core',
            '@fortawesome/free-brands-svg-icons', '@fortawesome/free-regular-svg-icons',
            '@fortawesome/free-solid-svg-icons', '@fortawesome/vue-fontawesome', 'accounting-js',
            'axios', 'chart.js', 'chartjs-plugin-datalabels', 'css-element-queries', 'date-fns',
            'dropzone', 'file-saver', 'flatpickr', 'laravel-echo', 'lodash', 'popper.js',
            'pusher-js', 'quill', 'raven-js', 'textarea-caret', 'tiptap', 'tiptap-commands',
            'tiptap-extensions', 'tooltip.js', 'v-click-outside', 'v-tooltip', 'vue',
            'vue-quill-editor', 'vue-router', 'vuedraggable', 'vuex',
        ]);
}
```
**this will return 404 errors for `manifest.js` & `vendor.js` during HMR** (as they don't get generated without `.extract`, however this will not affect you otherwise)
