### ISSUE TITLE
Editable not works

### ISSUE THREAD

**Issue by novusfederico** [laravel-enso/Enso#195]
This is  a bug .

### Prerequisites
 [# ] Are you running the latest version? 
 [#] Are you reporting to the correct repository? 
(enso is made of many specialized packages: https://github.com/laravel-enso)
 [# ] Did you check the documentation? 
 [#] Did you perform a cursory search? 

### Description
This are the value that you describe into documentation
` "meta": ["searchable", "sortable", "sort:ASC", "sort:DESC", "translatable", "boolean", "slot", "rogue", "editable", "total", "customTotal", "date", "icon", "clickable", "notExportable", "nullLast"],`

but if i set editable not work, into documentatio you describe all value, but not the editable

![screenshot2](https://user-images.githubusercontent.com/45257537/52440331-1a31df00-2b1e-11e9-8107-de1821f07267.png)
ou have skipper the editable into description. Please see the attachments

**Comment by aocneanu** [comment]
Use the issue template, it there for a reason. (also READ the issue template).

`editable` is a leftover from a very incipient version of the vue datatable package, when we did not have slots. You can easily achieve editable behaviour with `slot`.

**Comment by mauthi** [comment]
Btw. - is there an example for an editable slot for a boolean column (checkbox)?
