### ISSUE TITLE
Create a welcome page for guests

### ISSUE THREAD

**Issue by bleeuwen** [laravel-enso/Enso#197]
This is  a ** feature request**. 

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
Creation of a Welcome page for guests fails

### Steps to Reproduce
Added a controller: WelcomeController.php (in App\Http\Controllers
Added to api.php (in routes):
Route::middleware(['guest'])
    ->group(function () {
        Route::get('/welcome', 'WelcomeController@index')->name('welcome');
    });
Added an Index.vue  to resources\js\pages\welcome;
(mostly copied from activityLog/Index.vue)
<template>
    <div class="wrapper">
        <div class="welkom">
            <h1>WELCOMETEXT</h1>
        </div>
        <div class="has-text-centered"
            v-if="!ready && loading">
            <h4 class="title is-4 has-text-centered">
                {{ __('Loading') }}
                <span class="icon is-small has-margin-left-medium">
                    <fa icon="spinner"
                        size="xs"
                        spin/>
                </span>
            </h4>
        </div>
        </div>

</template>

<script>

export default {

    data: () => ({
        ready: false,
        loading: false,
        message: 'this is my message',
        path: route('welcome'),
        axiosRequest: null,
        feed: [],
        offset: 0
    }),
    methods: {
        fetch() {
            this.loading = true;

            if (this.axiosRequest) {
                this.axiosRequest.cancel();
            }
            this.axiosRequest = axios.CancelToken.source();
            axios.get(route('welcome'), {
                params: { offset: this.offset },
                cancelToken: this.axiosRequest.token,
            }).then(({ data }) => {
                this.loading = false;
                this.ready = true;
            }).catch((error) => {
                if (axios.isCancel(error)) {
                    this.axiosRequest = null;
                    return;
                }
                this.handleError(error);
            });
        },
        reload() {
            this.fetch();
        },
    },
};
</script>

<style lang="scss">
</style>

in resource/routes I created welcome.js with:
const WelcomeIndex = () => import('../pages/welcome/Index.vue');

export default {
    name: 'welcome',
    path: '/',
    component: WelcomeIndex,
    meta: {
        breadcrumb: 'index',
        title: 'Welcome',
    },
};

### Expected behavior
Showing: WELCOMETEXT

### Actual behavior
Empty screen, the log says: 
TypeError: route is undefined[Meer info] vendor.js line 346 > eval:1142:7
addRouteRecord vue-router.esm.js:1141
createRouteMap/< vue-router.esm.js:1114
forEach self-hosted:262:13 
.......1

**Comment by bleeuwen** [comment]
It appeared to work out well after all. I made a mistake with file auth.js

**Comment by bleeuwen** [comment]
After all it did not work out at all.

I adopted the Laravel-enso package because of its nice CRUD functionality, and when you only follow the track it is OK.

But if you want to add things you have to be too much a Laravel and Vue expert to get things done. 
Just addng a simple welcom-page was the straw that broke the camels back.

I think I go back to Drupal 8 to get my things done.

**Comment by aocneanu** [comment]
Sorry to hear that you didn't got it working.

Just wanting to say that apparently the problems were not (at least not only) related to understanding how Enso works, but to (also to) core concepts of Laravel and Vue (routing / router). To be efficient with Enso you have to be comfortable with those, first.

**Comment by bleeuwen** [comment]
That's just the problem.
There is an avalanche of solutions, but all still require deep knowledge if you want somthing extra.
Problems are also that the packages sometimes follow their own principles, so that additions are hard to implement.

The advantage of frameworks and CMSes are that you can start wirking and building up immedeatly.
