### ISSUE TITLE
[Feature Request] Can we add RTL support

### ISSUE THREAD

**Issue by YacoubBelaoura** [laravel-enso/Enso#198]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version? 2.16.2
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

if possible adding  RTL support 
![rtl](https://user-images.githubusercontent.com/18699402/52707031-099ec000-2f87-11e9-844b-12d9e3364be5.png)

and Thanks for this Awesome project. it helped me a lot to get started.
i used Enso from v2.10.4

**Comment by aocneanu** [comment]
I would welcome a PR for this.

**Comment by YacoubBelaoura** [comment]
Ok thanks, i will prepare one on a clean enso project, and send a PR 
i will close this issue.
