### ISSUE TITLE
Can I display content for non authenticated users

### ISSUE THREAD

**Issue by albertosgz** [laravel-enso/Enso#202]
This is  a **feature request**.

### Prerequisites
* [*] Are you running the latest version?
* [*] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [*] Did you check the documentation?
* [*] Did you perform a cursory search?

### Description
I would like to display a table for non authenticated users (guests). This table could be a new one to avoid to change any of current permissions. I don't know if is possible to add a kind of guests permissions and change some middleware of vue files in order to do it.

### Steps to Reproduce
1. Before log into the system.

### Expected behavior
Display a particular table in a particular route, like public/items.

### Actual behavior
Only supported the logged in browsing.

**Comment by albertosgz** [comment]
If is not possible, the other solution I came up with is to change default route login, in order to display a custom component, leaving the auth component in a sidebar or navbar, and in case the user is logged in, start all of the current process.
What do you think? what's the easiest solution?

**Comment by boing6000** [comment]
I had a particular case that had to display a table for both logged-in and public user.

In the route file i did this:

let isAuth = localStorage.getItem('isAuth');

`export default {
    name: 'my.route.name',
    path: '/my-url',
    component: Component,
    meta: {
        breadcrumb: '',
        title: '',
        route: 'my.route.name',
        guestGuard: isAuth === null || isAuth === 'false' ? true : false,
 };`

And in the file in middleware/before/allow.js

add the name of your route to the exceptions array:
`const exceptions = ['notFound', 'unauthorized', 'my.route.name']`

And with doing this I got the same route working for both logged in and public users.

**Comment by albertosgz** [comment]
I was not able to do it. It always redirects to login page.
To help to dig into the code, could you give me the point where to start from?
I am try to understand the flow of the router to know to set a new route.

**Comment by albertosgz** [comment]
I found it!
Following the routes, I've end up in `resources/js/pages/auth/Login.vue`. So all I have to do is edit it, or change the component to open by default in the route file `resources/js/middleware/before/guest.js`, and use the login form component within the new one.
Thanks!
