### ISSUE TITLE
enso development

### ISSUE THREAD

**Issue by moosavimaleki** [laravel-enso/enso#203]
Hello
I read the documentation and guides
But there was nothing about the right development method with enso
How to make a new crud?
What if I do not use the enso permissions system?
Create new theme....?
and ...
and ...

thank...

**Comment by aocneanu** [comment]
We'll try to write some tutorials about this in the future...

**Comment by gaabora** [comment]
Stream with commentary and record on youtube would be perfect tho, I found one but it's only 20 seconds long T_T

**Comment by jihadismail8** [comment]
could you please make some kind of documentation ? the package seems wonderful , but kind of hard to start with it with out a good documentation .

**Comment by aocneanu** [comment]
Did you check docs.laravel-enso.com ?..

**Comment by aocneanu** [comment]
New section in docs https://docs.laravel-enso.com/guide/development.html

**Comment by ariefbudiyono** [comment]
great, thanks for new docs but i've failed  node dependencies yarn after git clone , 

![error](https://user-images.githubusercontent.com/1271131/58609367-82751e00-82d1-11e9-8fa7-16488c824a95.png)


i try to direct  follow to your new development guide and succes login to admin then play with enso cli... but there is warning on console "[vue-router] Route with name 'vehicles.motorized.cars.index' does not exist", and my cars menu is blank



thanks

**Comment by gandesc** [comment]
Hi,

Upon reading your message I just made another Enso clone locally to see if I could reproduce the patch issue - and I encountered no issues.

The only thing that comes to mind is that there must be something related to your dev environment: I see you're using Windows while we're all using Linux and MacOS.

As per the other issue, with the route, can you double check that:
- if running `php artisan migrate` there's nothing to migrate
- if running `php artisan route:list` there are no errors and can see your routes
- in `resources/js/routes/.../cars` you do have the `index.js` file
- you do have the `vehicles.motorized.cars.index` permission

You can check the existence of the permission, by navigating to: 
System -> Permissions -> paste the permission name in the search box

The fact that you have that warning in the console suggests that the menu has been created with the proper route name, but the front end doesn't find that route.
