### ISSUE TITLE
Should I start a new project on v3.x?

### ISSUE THREAD

**Issue by ebgreen** [laravel-enso/Enso#206]
This is  a **bug | feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

**Comment by ebgreen** [comment]
I am starting a new project and it will be in beta for awhile.  I wanted you opinion on whether to use 3.0 to start since it will obviously be improved to start or 2 and upgrade later. 

My concern is the amount of work to upgrade from 2 to 3 versus starting on 3 and dealing with bugs.

One benefit I can see with using 3 to start is I will find bugs for you too fix possibly.

**Comment by aocneanu** [comment]
You should definitely go for 3.0.

We have over a dozen production / staging projects on 3.0 or in the upgrading process so probably we will find most of the bugs before your project will be shaped.

Not to mention that for 2.x the support will eventually be stopped.

**Comment by ebgreen** [comment]
Awesome thanks I was leaning that way.  If I have a few question about vuedatatables I'm going to post there.
