### ISSUE TITLE
Not recieving notifications

### ISSUE THREAD

**Issue by bytebuddha** [laravel-enso/Enso#209]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [ ] Are you reporting to the correct repository? I'm not sure about this one :frowning_face: 
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
I'm using laravel-websockets instead of pusher to broadcast notifications. Currently i'm only using the CommentTagNotification from the CommentsManager. The comments manager creates the notification with 'notifiable_type' field set to LaravelEnso\Core\Models\User. I assume this is because that is the actual user model it users to create the notification. But when i actually fetch the notifications(from a cloned Enso repository), I am using the Enso\App\User model so no notifications are received. I have been able to fix this by removing App\User and only using LaravelEnso\Core\Models\User in my app but this seem's substandard in case in the future i need to modify App\User.

### Steps to Reproduce

1. Clone Enso repository
2. install laravel websockets following [guide](https://docs.beyondco.de/laravel-websockets/1.0/getting-started/installation.html)
3. Change the Laravel Echo code too point to websocket server instead of pusher
4. Do something that sends a notification. I am testing with the CommentTagNotification from LaravelEnso\CommentsManager

### Expected behavior
This should just work like it does when using pusher

### Actual behavior
No notifications are recieved upon checking the database i see that 'notifiable_type' is set to 'LaravelEnso\Core\Models\User'. Using laravel debugbar i notice that the query where using to get the notifications is: 
```
select * from `notifications` where `notifications`.`notifiable_id` = 1 and `notifications`.`notifiable_id` is not null and `notifications`.`notifiable_type` = 'App\User' order by `created_at` desc limit 200 offset 0
```
If I use LaravelEnso\Core\Models\User in my app instead of App\User everything works as expected.

I'd like to submit a PR to help out with this but i'm fairly new to laravel and im not sure what the best way to fix it would be.

**Comment by aocneanu** [comment]
It has nothing to do with websockets.

You shouldn't have to use in your local app the core User. The tagging functionality is contained into the commentsManager package. The package only knows how to work with the core User, and that's ok. Whenever a notification is pushed for the core user the apps user will received it as well.

Could you provide the code and context that you are using for getting the comment tag notifications?

**Comment by bytebuddha** [comment]
Sure thing upon looking though my git log it seems i made less changes then i though.

The only relevent change is in config/broadcasting.php i added the 'host', 'port' and 'schema' to the pusher config
```php
    'connections' => [
        'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
              'cluster' => env('PUSHER_APP_CLUSTER'),
              'encrypted' => true,
              'host' => '127.0.0.1',
              'port' => 6001,
              'schema' => 'http'
            ],
        ],
```
I mispoke didn't actually have to change the laravel echo code. Both the 'initEcho' functions of resources/js/core/structure/navbar/IO.vue and resources/js/core/structure/navbar/IO.vue are unchanged. Here is there current form
```vue
        initEcho() {
            this.echo = new Echo({
                broadcaster: 'pusher',
                key: this.meta.pusher,
                cluster: this.meta.pusherCluster,
                namespace: 'App.Events',
            });
        },
```

After doing this i am unable to recieve notifications. They appear in the database but it always shows as no notifications in the navbar as well as in the Notifications index page.

I changed these files to use Core\Models\User instead of App\User.
config/auth.php
```php
        'users' => [
            'driver' => 'eloquent',
            // TODO: change this back to App\User after speaking to the laravel enso people.
            'model' => LaravelEnso\Core\app\Models\User::class,
        ],
```
config/services.php
```php
        // TODO: change this back to App\User after speaking with the laravel enso people.
        'model' => LaravelEnso\Core\Models\app\User::class,
        'key' => env('STRIPE_KEY'),
        'secret' => env('STRIPE_SECRET'),
```
app\Http\Controllers\Auth\RegisterController.php & app\Http\Controllors\Dashboard\UserStatController.php I simply imported LaravelEnso\Core\Models\User instead of App\User

**Comment by bytebuddha** [comment]
After reading laravel documentation all morning i was able to find a better work around for this.

Reverting the changes above and adding this to AppServiceProvider is a much better solution.
```php
        Relation::morphMap([
          'LaravelEnso\Core\app\Models\User' => 'App\User'
        ]);
```

But the problem still remains if i don't use morphMap. I do not recieve any notifications.

**Comment by jlsjonas** [comment]
Great discovery @bytebuddha, that line might help with certain edge-cases I've been having to deal with :)

I'm using laravel-websockets myself but haven't had time to debug what you're experiencing (I don't use `CommentTagNotification` at this time).

@aocneanu Might be good to add that snippet to the introduction guide and/or default Enso _bundle_ (this repo) to improve the onboarding experience.

**Comment by bytebuddha** [comment]
I renamed this since aocneanu poointed out laravel-websocket is working as expected.

**Comment by aocneanu** [comment]
I’m sorry for causing a confusion :) I’m not 100% positive that websockets are working, because we’re using pusher and I don’t have the setup to test it. Ibelieve that @jlsjonas does. 
I only wanted to point out that the relationship issue is not related to the websockets provider.

**Comment by bytebuddha** [comment]
@aocneanu I can confirm websockets are working fine (for me atleast). I was confused thinking the notification's in the Header were being sent through them, but as you pointed out they are not.

> The package only knows how to work with the core User, and that's ok. Whenever a notification is pushed for the core user the apps user will received it as well.

Can i ask how this is possible? When laravel-enso/Notification's sends a notifications it set 'notifiable_type' equal to 'LaravelEnso\Core\Models\User' and when laravel-enso\Enso searches for notifications with notifiable_type 'App\User'. How can this work? Maybe i'm missing something?

**Comment by aocneanu** [comment]
Wow @bytebuddha,

So sorry, I just got my head around what you were saying from the very beginning. I was really reading between the lines, but thank you for being persevering :)

It seems that 6 months ago when we entered the people structure I was careless on the refactor and instead of using `config('auth.providers.users.model')` I changed to the core's user.

Fixed now.

**Comment by jlsjonas** [comment]
> instead of using config('auth.providers.users.model') I changed to the core's user.
We should check the entire framework for this as I'm pretty sure this also occurs in other places,
a quick search gave me Avatar, Role & Login Models being directly tied to the core's user. Although they should have less of an impact in theory.
