### ISSUE TITLE
Mix manifest missing on fresh installation

### ISSUE THREAD

**Issue by kplgr** [laravel-enso/Enso#211]
This is  a **bug**.

### Prerequisites
* [x ] Are you running the latest version?
* [ x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ x] Did you check the documentation?
* [ x] Did you perform a cursory search?

### Description

On a fresh installation, I get this error message on the very first try to open the webpage:
"The Mix manifest does not exist. (View: /home/vagrant/code/Enso/vendor/laravel-enso/core ▶"
I think its looking for a file at /home/vagrant/code/Enso/public/mix-manifest.json that just doesn't exist!

I am using a freshly installed homestead box with vagrant, with just the laravel-enso SPA and nothing else installed.

### Steps to Reproduce

Follow through the steps 1-5, **_precisely_**, as described on https://docs.laravel-enso.com/guide/getting-started.html#installation-steps and then just try to open the site

### Expected behavior

I expected the installation instructions to work but maybe I am missing something so obvious that it's not in the instructions? 

### Actual behavior

They don't work!

**Comment by aocneanu** [comment]
Since we have moved the FE to npm, steps 6-8 are no longer optional :)

I just updated the docs.

**Comment by kplgr** [comment]
OK, I see!  Sorry if that was obvious, but I had no idea..

New issue then:

Upon trying Step 6, using yarn, I ge the following error message:
error An unexpected error occurred: "EPROTO: protocol error, symlink '../../../parser/bin/babel-parser.js' ->'/home/vagrant/code/Enso/node_modules/@babel/core/node_modules/.bin/parser'".

Then everything stops, and of course I cant do yarn dev or yarn hot.

Same thing happens if I try npm install, with error
npm ERR! EPROTO: protocol error, symlink '../@babel/parser/bin/babel-parser.js' -> '/home/vagrant/code/Enso/node_modules/.bin/parser


Am I missing something again...?

**Comment by aocneanu** [comment]
`git clone https://github.com/laravel-enso/enso ./ testing && cd testing && composer install && yarn install && yarn run dev` works every single time on my end.

Maybe you have an old version of yarn / npm ?
