### ISSUE TITLE
 feature request : Tailwindcss theme

### ISSUE THREAD

**Issue by YacoubBelaoura** [laravel-enso/enso#215]
This is  a **feature request**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description

tailwindcss theme
![output](https://user-images.githubusercontent.com/18699402/56470539-16380c80-643f-11e9-8228-58945a80986a.gif)

a clone of the current bulma theme using tailwind

this theme is using TailwindCss V1.0.0-beta4, so it will be ready for the final verstion
with this configurations, only to keep the look

this is only a mockup using Vue and tailwindcss to divide it for each enso component, so it will be easy to add it.
```JavaScript
const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
  theme: {
    // Some useful comment
    extend: {
      colors: {
        white: {
          default: "#ffffff",
          smoke: "#f5f5f5"
        },
        gray: {
          ...defaultTheme.colors.gray,
          290: "#4a4a4a",
          480: "#7a7a7a",
          860: "#dbdbdb"
        },
        blue: {
          ...defaultTheme.colors.blue,
          450: "#3273dc"
        },
        green: {
          ...defaultTheme.colors.green,
          450: "#23d160"
        }
      },
      fontFamily: {
        enso: ["Montserrat", "sans-serif"]
      },
      height: {
        13: "3.25rem"
      },
      inset: {
        13: "3.25rem"
      },
      boxShadow: {
        bnavbar: "0 1px 1px rgba(10, 10, 10, 0.35)",
        bbookmarks: "0 1px 1px rgba(10, 10, 10, 0.2)",
        bsidebar: "0 2px 3px rgba(10, 10, 10, 0.35)"
      }
    }
  },
};

```
if there is an other idea for a different theme, i can change it.
if its ok, i can start merging it with enso and make a PR.

ps: there is no :bug: https://github.com/laravel-enso/Enso/issues/125#issue-348854265

**Comment by aocneanu** [comment]
That's great. Let's focus on merging the RTL first and then we'll move on with tailwind.

Thanks!

**Comment by YacoubBelaoura** [comment]
ok that's great thanks.

**Comment by aocneanu** [comment]
@YacoubBelaoura If you have the time I guess it would be great if you could start working on this.

**Comment by YacoubBelaoura** [comment]
ok, i will start working on it.
but i think it will require a new package(s) so there will be 2 theme 
 * bulma 
 * tailwind
and there may be a need refactor, to set the renderless components as  separate packages.
or just add it to the current one.
i will see when i am done with it.

**Comment by aocneanu** [comment]
@YacoubBelaoura we should use the existing ui packages. Each package that is framework dependent has a bulma folder. The reason for this is that we can add tailwind/bootstrap/etc folders in the future.

The idea is to reuse the existing renderless components.

In fact, this is the main reason for the whole FE rewrite.

**Comment by YacoubBelaoura** [comment]
so all themes will be packed in one package. 
this is great ,so the only change will be on `enso.js` and `webpack.mix.js` so that they both read `THEME` variable from `.env` and  compile  desired theme.

**Comment by aocneanu** [comment]
The only change should be this line, because the whole (local) app should be written in the same CSS framework

https://github.com/laravel-enso/enso/blob/master/resources/js/enso.js#L5

**Comment by YacoubBelaoura** [comment]
yes that's what i was talking about but there will be other compiled files that are not required.
for example if one used tailwind. the bulma css will be compiled and added to index.blade.php and there will be conflict. so what i was thinking about is :         .*"i didnt test it yet"*
* add a new `.env` variable called `THEME=tailwind `  or `THEME=bulma` 
* use it in `index.blade.php` to add only the required css.
* on `enso.js` using dynamic `import()` like this
```javascript
require('dotenv').config();
...
const App = () =>  import('@enso-ui/ui/${process.env.THEME}';
...
```
* and the same for `webpack.mix.js` so that it  compile only the required `THEME` packages.

and with that the user only change `THEME` and run `yarn dev`

**Comment by jlsjonas** [comment]
Definitely +1 on adding it the flag in `webpack.mix.js` to keep compile times down

**Comment by YacoubBelaoura** [comment]
sorry to say this but i got some urgent business that will hold me a little bit for around 10-12 days. 
so this may take a little bit longer. 

but its going good so far. there is only some things i found that need some attention. 
![Screenshot from 2019-05-26 12-59-06](https://user-images.githubusercontent.com/18699402/58381557-1d11ec00-7fb6-11e9-8a71-b7525a193131.png)
* the menu sidebar on the "collapsed state" menu-item and label are not on the same level  when scrolling.
  * s1: change it to grow on hover
  * s2: make the label stick to middle on screen or top of menu.
*  changed the notification count to be more easy to read and notified.
*  the search bare on top overlap with the other nav items .(for now i changed to grow and take all the space left.
  * s1: add drop-down icon that indicate "there are some items hidden under"
  * s2: change the search bar to a button that when clicked.
     * s1: show a popup
     * s2: overlap all the nave bare as a search input. and "Esc" to exit.
* there is no search bar on mobile S size. add a button for that ?.

**Comment by YacoubBelaoura** [comment]
@aocneanu . i have a question. regarding future upgrades and if there will be themes for other framework. 

*  i am almost (85% 'i was really busy with work lately ') to finish tailwind, and i found a problem regarding current enso features, "Cli, Forms, Tables" they are all configured for bulma, i did make some tailwind classes to imitate the current configs, but if there is future upgrades to match that first idea for other framework. 

for enso-ui i am using this idea

> yes that's what i was talking about but there will be other compiled files that are not required.
> for example if one used tailwind. the bulma css will be compiled and added to index.blade.php and there will be conflict. so what i was thinking about is : ._"i didnt test it yet"_
> 
>     * add a new `.env` variable called `THEME=tailwind `  or `THEME=bulma`
> 
>     * use it in `index.blade.php` to add only the required css.
> 
>     * on `enso.js` using dynamic `import()` like this
> 
> 
> ```js
> require('dotenv').config();
> ...
> const App = () =>  import('@enso-ui/ui/${process.env.THEME}';
> ...
> ```
> 
>     * and the same for `webpack.mix.js` so that it  compile only the required `THEME` css.
> 
> 
> and with that the user only change `THEME` and run `yarn dev`

i can use the same idea for  **`stub`** pages files for the tailwind theme too

**Comment by aocneanu** [comment]
Yeah, a busy period on my part too.

I guess there might be other css frameworks supported in the future, why not.

We can add a cli config where we can define the theme used for generating the files.

For forms & tables we should use separate template files built around the renderless ones for tailwind instead of reusing the bulma templates with mocked tailwind classes.

Ugrading the framework pages could be as easy as doing a search&replace for `@enso/forms/bulma` to `@enso/forms/tailwind`, the same for the other components.

What do you think?

**Comment by k33n** [comment]
@aocneanu any movement on this?

**Comment by curtisdelicata** [comment]
Is this still being worked on?
