### ISSUE TITLE
Language Portuguese (Brazil) 

### ISSUE THREAD

**Issue by boing6000** [laravel-enso/Enso#217]
This is  a **bug**.

### Prerequisites
* [ y] Are you running the latest version?
* [ y] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [y ] Did you check the documentation?
* [y ] Did you perform a cursory search?

### Description
Fresh install of enso when change language to Portuguese (Brazil) the flag rtl is checked.

### Steps to Reproduce

1. clone enso in a new dir and database
2. after login change language to portuguese.

![image](https://user-images.githubusercontent.com/3080041/57100852-4fe9fc80-6cf6-11e9-9ac6-b9af9d90b76b.png)

### Expected behavior
language is not rtl

### Actual behavior
language is set as rtl

**Comment by aocneanu** [comment]
From language seeder

```php
['name' => 'br', 'display_name' => 'Brazilian Portuguese', 'flag' => 'flag-icon flag-icon-br', 'is_rtl' => false, 'is_active' => true],
```

In the above pic from the form 

![image](https://user-images.githubusercontent.com/16073274/57126178-b4f42f80-6d94-11e9-9cea-b535be267af9.png)

Could you investigate on your end?

**Comment by boing6000** [comment]
the file from git clone yesterday:
![image](https://user-images.githubusercontent.com/3080041/57136906-9dad4600-6d84-11e9-837f-5558e0481d6b.png)

i changed not only the rtl but the name to 'pt-br' because the vue-calendar doesn't have br language and in the locale.js in '@enso-ui/datepicker/src/locale'  changed to 'pt-br': Portuguese,

**Comment by boing6000** [comment]
The patch for the @enso-ui/datepicker
[@enso-ui+datepicker+1.0.11.zip](https://github.com/laravel-enso/Enso/files/3142058/%40enso-ui%2Bdatepicker%2B1.0.11.zip)

**Comment by aocneanu** [comment]
In the current version the LanguageSeeder is not upgraded to the latest version. Will publish a new realease soon.

**Comment by aocneanu** [comment]
done
