### ISSUE TITLE
Patch package error Windows Docker

### ISSUE THREAD

**Issue by curtisdelicata** [laravel-enso/enso#218]
This is  a **bug**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description
Installing using Docker on Windows. Patch package causes error. I had to manually apply patch using PHP Storm and then remove patch-package from package.json

### Steps to Reproduce
1. yarn install or npm install

### Expected behavior
Patched the RTL files.

### Actual behavior
**ERROR** Failed to apply patch for package bulma-rtl

  This happened because the patch file patches\bulma-rtl+0.7.1.patch could not be parsed.

  If you just upgraded patch-package, you can try running:

    cd patches\bulma-rtl+0.7.1.patc
    patch -p1 -i h
    npx patch-package bulma-rtl
    cd ../..

**Comment by curtisdelicata** [comment]
The only difference I found was that everything is now RTL. Unless the patch didn't apply correctly?

**Comment by aocneanu** [comment]
@curtisdelicata are you still experiencing problems with this?
