### ISSUE TITLE
pcntl Windows

### ISSUE THREAD

**Issue by curtisdelicata** [laravel-enso/Enso#219]
This is  a **bug**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description
PCNTL required but Windows doesn't support this. Manually override and no issues. I fixed by modifying composer.json to include:

    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true,
        "platform": {
            "ext-pcntl": "7.3",
            "ext-posix": "7.3"
        }
    },

### Steps to Reproduce
1. composer install

### Expected behavior
Error

### Actual behavior
Error

**Comment by jlsjonas** [comment]
This is a limitation of `laravel/horizon`, we don't directly require it.

Ignoring this will not cause issues for Enso itself, but does prevent Horizon from working correctly.

also see https://github.com/laravel/horizon/issues/170#issuecomment-433040421 & https://github.com/laravel/horizon/issues/154#issuecomment-366712260 for a _workaround_

An error during install here helps pointing this out, but it's fine to `--ignore-platform-reqs ext-pcntl ext-posix` for development purposes on windows.
Feel free to suggest a documentation change of the installation steps to clarify this.

**Comment by idrisalshikh** [comment]
> Feel free to suggest a documentation change of the installation steps to clarify this.

yes please point out in a big font in horizon documentation that horizon will not work in windows it works only in Linux, it will save people's time.
