### ISSUE TITLE
Docker Windows mysql hostname

### ISSUE THREAD

**Issue by curtisdelicata** [laravel-enso/Enso#220]
This is  a **bug**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description
artisan works using 127.0.0.1 or localhost but application requires setting hostname to enso-mysql (the containers name)

**Comment by jlsjonas** [comment]
Setting `DB_HOST=enso-mysql` in your `.env` file should be all you need to change for the docker-based set-up.
Can you give reproducible steps please?

**Comment by curtisdelicata** [comment]
It does work when setting to enso-mysql but I didn't see that in the documentation.

**Comment by jlsjonas** [comment]
Docker support was a recent contribution by a member, however the [steps to use](https://docs.laravel-enso.com/guide/getting-started.html#steps-to-use) under Docker do state
>Rename .env.example to .env and fill out the appropriate variables.

As the current (localhost) .env.example still makes sense for most I believe this is correct.

Feel free to contribute to the documentation to highlight this.

p.s.: note that even the _default_ [installation steps](https://docs.laravel-enso.com/guide/getting-started.html#installation-steps) point this out
> edit the database configuration information
