### ISSUE TITLE
Overwrite vue component (e.g. AppFooter)

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/Enso#221]
This is  a **question**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

I would like to overwrite a component for my app - in the specific case "AppFooter.vue".
In the changelog I found the following info: locally create your own version of the component and change the imports to use your local component

My question:
- How can I do this? Since AppFooter is imported in DefaultLayout so I need to overwrite this as well?

Thx in advance for your help.
(if this issue is in the wrong package please tell me which package is the right for such issues)

**Comment by stotes** [comment]
You need to create a ```patch-package``` using yarn/npm.

https://www.npmjs.com/package/patch-package

```
# modify enso's appFooter 
nano node_modules/@enso-ui/ui/src/bulma/components/AppFooter.vue
 
# run patch-package to create a .patch file 
yarn patch-package @enso-ui/ui
```

Keep in mind if ```AppFooter.vue``` ever gets changed from Enso's end you will have to remake your patch file.

**Comment by mauthi** [comment]
@stotes works for me - looks good.
