### ISSUE TITLE
Offline app

### ISSUE THREAD

**Issue by boing6000** [laravel-enso/enso#224]
This is  a **question**.

### Prerequisites
* [ v] Are you running the latest version?
* [v ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ v] Did you check the documentation?
* [v ] Did you perform a cursory search?

### Description
Is possible to create offline app using enso, if yes how would be the best approach?

**Comment by aocneanu** [comment]
By offline app you mean a PWA?

**Comment by boing6000** [comment]
When internet offline save locally end synchronize when internet is back.

**Comment by aocneanu** [comment]
All over Enso the content (actual data) for every page is fetched by server requests. You would have to overwrite this behaviour to store locally what you need, and add some sort of a shim on axios to decide on each resource that needs data if a request should be made or the data in localStorage will be used.
