### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by lsosa3** [laravel-enso/enso#226]
This is  a **bug | feature request**.

### Prerequisites
* [ x] Are you running the latest version?
* [x ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x ] Did you check the documentation?
* [x ] Did you perform a cursory search?

### Description

i ran npm install and got this
webpack-cli@3.3.2 requires a peer of webpack@4.x.x but none is installed. You must install peer dependencies yourself.

check package.json and webpack version should be the 3, am i doing something wrong?
### Steps to Reproduce

Download the project with git clone https://github.com/laravel-enso/Enso.git

Run in the project folder composer install

Configure the .env file. Run php artisan key:generate

Run php artisan migrate --seed

npm install
### Actual behavior

![Selección_062-2](https://user-images.githubusercontent.com/14814335/57964394-e297b780-7902-11e9-807f-6ef9c0dd93db.jpg)
then runing enso
![Selección_064](https://user-images.githubusercontent.com/14814335/57964537-b846f980-7904-11e9-8406-94cc87bd93eb.png)

**Comment by aocneanu** [comment]
I'll release v3.3.0 today or tomorrow, if you'll still encounter problems reopen this issue
