### ISSUE TITLE
Missing 3.3 upgrade step(s?), composer dump-autoload

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/enso#229]
This is  a **bug**.

### Prerequisites
3.3.0 upgrade

### Description

![image](https://user-images.githubusercontent.com/932193/58259674-4859c880-7d75-11e9-83da-32f0c660e2a1.png)

### Steps to Reproduce

1. Follow the upgrade steps, removing `laracasts/generators` as requested.
2. Try to rename-migrations

### Expected behavior

command to run

### Actual behavior

error

**Comment by jlsjonas** [comment]
This specific error was related to (automated) `bootstrap` caching
However, manually clearing the cache directory surfaces a similar issue...
![image](https://user-images.githubusercontent.com/932193/58260124-30367900-7d76-11e9-9134-df4ce900bbbd.png)

Further inspection roots the cause to the following (auto-generated after clearing in the previous step)
![image](https://user-images.githubusercontent.com/932193/58260259-6f64ca00-7d76-11e9-80d5-ca3afc16e8f4.png)

It seems that some Laravel naming convention was ignored, causing this?
As I can confirm that's the block that was generating the error (removing it gives an error aboud activitylog instead, which is the following block.

**Comment by jlsjonas** [comment]
looks like a `composer du` fixed it for me (https://github.com/laravel/framework/issues/21626 helped figure out potential workarounds)
might not work for everyone this way though, seeing the thread

**Comment by aocneanu** [comment]
`composer dump-autoload` should solve it for everyone who hits this. We didn't on any of our projects.

**Comment by jlsjonas** [comment]
Will keep it open for now, maybe add a note to the changelog on the next update that involves Enso?

**Comment by aocneanu** [comment]
I's strange that you encountered this because one of the first steps of the upgrade is `composer update`. This automatically calls dump autoload after finishing with updating the dependencies.

**Comment by jlsjonas** [comment]
🤔
I guess that happens after patches then...
We had a failing composer patch which presumably prevented du from running
