### ISSUE TITLE
(3.3) enso:upgrade is missing index drop

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/enso#230]
This is  a **bug**.

### Prerequisites
3.3 upgrade

### Description

![image](https://user-images.githubusercontent.com/932193/58261246-3af20d80-7d78-11e9-80f4-8027bd775281.png)
`Upgrading company person relationship` seems to _forget_ to drop the index first, erroring it out.

### Steps to Reproduce
`enso:upgrade` (using a SQL Server back-end)

### Expected behavior

upgrade

### Actual behavior

See screenshot

**Comment by jlsjonas** [comment]
Same applies for `people_company_id_index` (before dropping `company_id`)

**Comment by aocneanu** [comment]
please make a pr for this.

On mysql `dropForeign` seems to be enough.

**Comment by jlsjonas** [comment]
Weird, it usually doesn't create indexes out of the blue, however it did also do this on a new environment so it's not related to old code. Will look for a PR tomorrow.
