### ISSUE TITLE
3.3: es6 support changed?

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/enso#232]
This is  a **bug | question**.

### Prerequisites
3.3 upgrade

### Description

Quite obscure...was anything changed to ES6 support?
I moved my (laravel-websockets-related) patch from IO/Notifications.vue to the new `websockets.js`, however webpack seems to error on the es6 destructuring that's happening there.

Apologies if not related to Enso itself

```bash
 WARNING  Compiled with 1 warnings                                                                                            09:45:07

 warning  in ./node_modules/@enso-ui/ui/src/modules/store/websockets.js

Module parse failed: Unexpected token (21:16)
You may need an appropriate loader to handle this file type.
|                 key: state.pusher.key,
|                 cluster: state.pusher.cluster,
|                 ...state.pusher.options.host && {
|                     wsHost: state.pusher.options.host,
|                     httpHost: state.pusher.options.host,

 @ ./node_modules/@enso-ui/ui/src/modules/store nonrecursive .*\.js$
 @ ./node_modules/@enso-ui/ui/src/modules/store.js
 @ ./resources/js/store.js
 @ ./resources/js/enso.js
 @ multi (webpack)-dev-server/client?http://webtools.test:3030 webpack/hot/dev-server ./resources/js/enso.js ./resources/sass/enso.scss ./node_modules/@enso-ui/themes/bulma/light.scss ./node_modules/@enso-ui/themes/bulma/dark.scss ./resources/sass/print.scss
```

### Steps to Reproduce
1. Add a destructured object in `node_modules/@enso-ui/ui/src/modules/store/websockets.js`'s `new Echo`
2. yarn dev/hot

### Expected behavior

compilation to succeed

### Actual behavior

Parsing error, seemingly not being able to handle object destructuring (ES6) anymore

**Comment by aocneanu** [comment]
I was affected by this when I started @enso-ui.

https://github.com/JeffreyWay/laravel-mix/issues/1805

**Comment by aocneanu** [comment]
And by the way, I fixed it by refactoring the spread operator.

**Comment by jlsjonas** [comment]
🤔 interesting...
The issue makes sense, but it wasn't an issue before... presumably as it was within a `.Vue` file and thus still required transpiling.

>I fixed it by refactoring the spread operator.

You don't happen to have any code example? 😄

**Comment by aocneanu** [comment]
instead of doing `return  { ...obj, a: 5 }` just `obj[a] = 5; return obj`

**Comment by jlsjonas** [comment]
I'll have to write mine with if's 😬  will make do thanks
