### ISSUE TITLE
Separate frontend and backend API ?

### ISSUE THREAD

**Issue by anardil** [laravel-enso/enso#234]
Hello,

I wonder if it's possible to have the SPA frontend on a server and the backend API on a different server?

Thanks a lot.

Regards.

**Comment by aocneanu** [comment]
Should be something very easy to achieve. From Enso’s perspective I believe that you only need to set the global `baseUrl` for axios.

**Comment by anardil** [comment]
Even if the authentication use a statefull system without JWT token?

**Comment by aocneanu** [comment]
I guess this is related to Laravel rather than Enso. I suppose that you will have to handle CORS

**Comment by aocneanu** [comment]
Can we close this?
