### ISSUE TITLE
how does custom  fields work in the new version?

### ISSUE THREAD

**Issue by lsosa3** [laravel-enso/enso#235]
This is  a **bug | feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

**Comment by aocneanu** [comment]
It this issue for forms? If so please open it on that repo. And a short answer would be "the same".
