### ISSUE TITLE
I am unable to install node_modules due to fontawesome

### ISSUE THREAD

**Issue by tanthammar** [laravel-enso/enso#236]
Followed the installation instructions. But I get stuck on installing node dependencies.
Error: 401 Unauthorized on all fontawesome packages.

Tried to remove them from composer.json and .lock and yarn.lock to be able to complete the installation but the error comes back anyway.
There must be somewhere else in the code that tries to load the packages.

**Comment by jefrascasse** [comment]
Delete yarn.lock and try again. 
Had exactly the same problem and failed to use the search *facepalm*

**Comment by aocneanu** [comment]
will make sure that the next version will not have this problem.

https://github.com/laravel-enso/enso/issues/123
