### ISSUE TITLE
Form-Builder Json not readable

### ISSUE THREAD

**Issue by carlosiv** [laravel-enso/enso#237]
This is  a **bug**.

### Prerequisites
* [/ ] Are you running the latest version?
* [ /] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [/ ] Did you check the documentation?
* [ /] Did you perform a cursory search?

### Description
cannot render create component, json not readable, using homestead/vagrant
### Steps to Reproduce

1. cloned and set up current repo
2. created structure using `php artisan enso:cli` (`php artisan enso:make:structure` does not work)
3. completed setup of structure, migrated
4. edited App/Tables/Builders files and showed table properly.
5. edit App/Forms/Builders but error occurred during render 

> " Json file is not readable /home/vagrant/code/enso/app/Forms/Builders/Administration/../../Templates/Administration/Sales.json"

**Comment by stotes** [comment]
This looks like a path issue or permission issue. 

Can you show your ```templatePath```? It looks like you have an extra parent directory ```../```.
 
``` /home/vagrant/code/enso/app/Forms/Builders/Administration/../../Templates/Administration/Sales.json ```

Example path 
```php
namespace App\Tables\Builders;

use LaravelEnso\Tables\app\Services\Table;
use App\Models\ExampleModel;

class ExampleTable extends Table
{
    protected $templatePath = __DIR__.'/../Templates/ExampleTable.json';
```

**Comment by carlosiv** [comment]
this is the one with a problem

`namespace App\Forms\Builders\Administration;

use App\Sales;
use LaravelEnso\Forms\app\Services\Form;

class SalesForm
{
    private const TemplatePath = __DIR__.'/.. /.. /Templates/Administration/Sales.json';

    private $form;

    public function __construct()
    {
        $this->form = new Form(self::TemplatePath);
    }
`

but this table builder works fine

`namespace App\Tables\Builders\Administration;

use App\Sales;
use LaravelEnso\Tables\app\Services\Table;

class SalesTable extends Table
{
    protected $templatePath = __DIR__.'/../../Templates/Administration/Sales.json';

    public function query()
    {
       `

**Comment by aocneanu** [comment]
@carlosiv,

if the error is `'Specified json file was not found :filename'` you have a problem with the template path.

if the error is 'Json file is not readable :filename' then the json file is not valid. Use a [json validator](https://jsonformatter.curiousconcept.com/) to fix your file.

**Comment by carlosiv** [comment]
@aocneanu This solve my problem. I missed a ``` , ``` in my json file. Thanks a lot.
