### ISSUE TITLE
PostgreSQL connection problem

### ISSUE THREAD

**Issue by VadimsTalapins** [laravel-enso/enso#238]
bug 

### Prerequisites
[*] Are you running the latest version?
[*] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
[*] Did you check the documentation?
[*] Did you perform a cursory search?

### Description
I have Ubuntu server with php v7.3.6-1+ubuntu16.04.1+deb.sury.org+1
I have install pdo drivers and php7.3-pgsql

php -i | grep -i pdo
/etc/php/7.3/cli/conf.d/10-pdo.ini,
/etc/php/7.3/cli/conf.d/20-pdo_mysql.ini,
/etc/php/7.3/cli/conf.d/20-pdo_pgsql.ini,
API Extensions => mysqli,pdo_mysql
PDO
PDO support => enabled
PDO drivers => mysql, pgsql
pdo_mysql
PDO Driver for MySQL => enabled
pdo_mysql.default_socket => /var/run/mysqld/mysqld.sock => /var/run/mysqld/mysqld.sock
pdo_pgsql
PDO Driver for PostgreSQL => enabled

The problem is I have success migrate database with seeds 
php artisan migrate --seed
In PostgreSQL tables is normally created with data, all ok.
Then I make login request a I have this error:
message | could not find driver (SQL: select * from "users" where "email" = admin@laravel-enso.com limit 1)
-- | --
exception | Illuminate\Database\QueryException
file | /var/www/dev.solcraft.eu/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php

In laravel log is the same problem:
[2019-07-08 11:37:06] local.ERROR: could not find driver (SQL: insert into "telescope_entries" 
at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 0): could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 0): could not find driver at /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)

**Comment by aocneanu** [comment]
set in your `.env` file `TELESCOPE_ENABLED=0` and try again. If it's telescope related check `config/telescope.php` or their github repo.

**Comment by VadimsTalapins** [comment]
After turning off the TELESCOPE, the errors associated with it were gone. But errors with authorization remained.
What was done to try to correct the error:
1) Updated PHP to 7.3.6
2) Updated Apache to 2.4.39
3) Composer update
4) PostgreSQL pdo drivers is installed and enabled
5) Reinstalled enso

What is most interesting in this situation, that migrations fall without problems, default values are also recorded (seed).
Also works command: php artisan migrate:fresh

It follows from this that the driver exists and works. But why does he stop working?

 I also created a simple request and received the same error:
php code:
`DB::table('users')->get()`
Error:
   Illuminate \ Database \ QueryException
   could not find driver (SQL: select * from "users")
Previous exceptions
    could not find driver (0)
    could not find driver (0)

/var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php
`        catch (Exception $e) {`
` !!!!664:Line           throw new QueryException(`
    `            $query, $this->prepareBindings($bindings), $e`
     `       );`
  `      }`
     `   return $result;`

**Comment by VadimsTalapins** [comment]
I have resolve this problem.
Problem is if I write php -v server show v7.3.6
And then I install pdo drivers I install this for php7.3.
Then I create sample php script to test postgresql and after this I receive Fatal error: Call to undefined function pg_connect().
Then I wrote phpinfo(); And I saw that version php 7.2 and this is my fetal fail!!!!
All guess check phpinfo().
