### ISSUE TITLE
Password form field not rendered

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/enso#241]
This is  a bug.

### Prerequisites
* [ 3.3.4 ] Are you running the latest version?
* [ x ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ x ] Did you check the documentation?
* [ x ] Did you perform a cursory search?

### Description
While trying to add a password form field for one of my models called "cluster", I see no field being rendered inside the edit form.
![image](https://user-images.githubusercontent.com/16973022/61315550-aa7bfa80-a807-11e9-99ad-127edd7b52bd.png)

Container is created:

![image](https://user-images.githubusercontent.com/16973022/61316178-0eeb8980-a809-11e9-9e53-6d33200697d2.png)

cluster.json:
```json
{
  "routePrefix": "models.clusters",
  "sections": [
    {
      "columns": 2,
      "fields": [
        {
          "label": "Name",
          "name": "name",
          "value": null,
          "meta": {
            "custom": false,
            "type": "input",
            "content": "text",
            "disabled": false
          }
        },
        {
          "label": "Hash",
          "name": "cluster_hash",
          "value": null,
          "meta": {
            "custom": false,
            "type": "input",
            "content": "text",
            "disabled": false
          }
        }
      ]
    },
    {
      "columns": 1,
      "fields": [
        {
          "label": "Description",
          "name": "description",
          "value": null,
          "meta": {
            "custom": false,
            "type": "textarea",
            "content": "text",
            "disabled": false,
            "rows": 2
          }
        }
      ]
    },
    {
      "columns": 2,
      "fields": [
        {
          "label": "HIDDEN",
          "name": "HIDDEN",
          "value": null,
          "meta": {
            "custom": false,
            "type": "input",
            "content": "text",
            "disabled": false
          }
        },
        {
          "label": "HIDDEN",
          "name": "HIDDEN",
          "value": null,
          "meta": {
            "custom": false,
            "type": "input",
            "content": "text",
            "disabled": false
          }
        }
      ]
    },
    {
      "columns": 2,
      "fields": [
        {
          "label": "Username",
          "name": "username",
          "value": null,
          "meta": {
            "custom": false,
            "type": "input",
            "content": "text",
            "disabled": false
          }
        },
        {
          "label": "Password",
          "name": "password",
          "value": null,
          "meta": {
            "custom": false,
            "type": "password",
            "disabled": false
          }
        }
      ]
    }
  ]
}
```

Index view is OK
![image](https://user-images.githubusercontent.com/16973022/61315981-9dabd680-a808-11e9-927d-c60bd8454cc7.png)

### Steps to Reproduce
1. Create CRUD using enso:cli for "cluster"
2. Define table structure
3. Define form structure

### Expected behavior
Password field should be rendered as a password field.

### Actual behavior
Missing field

**Comment by aocneanu** [comment]
The correct repo would be [forms](https://github.com/laravel-enso/forms)

from [user.json](https://github.com/laravel-enso/core/blob/master/src/app/Forms/Templates/user.json#L106)

```json
{
    "label": "New Password",
    "name": "password",
    "value": null,
    "meta": {
        "readonly": true,
        "type": "input",
        "content": "password",
        "hidden": true,
        "custom": true
    }
},
```

It should have a `"type": "input"`, `"content": "password"`.

You also have a problem with the validations if you did not receive an error with that template.

**Comment by robbykrlos** [comment]
> The correct repo would be [forms](https://github.com/laravel-enso/forms)
> 
> from [user.json](https://github.com/laravel-enso/core/blob/master/src/app/Forms/Templates/user.json#L106)
> 
> ```json
> {
>     "label": "New Password",
>     "name": "password",
>     "value": null,
>     "meta": {
>         "readonly": true,
>         "type": "input",
>         "content": "password",
>         "hidden": true,
>         "custom": true
>     }
> },
> ```
> 
> It should have a `"type": "input"`, `"content": "password"`.
> 
> You also have a problem with the validations if you did not receive an error with that template.

1st - sorry for the miss-report in the incorrect project.
2nd - maybe a small documentation mistake? - because i tried to follow the documenation therefore, when type is password, there is no content needed as it is only required for type input:

![image](https://user-images.githubusercontent.com/16973022/61321420-24b27c00-a814-11e9-879f-069545d96782.png)

Thank you help and for your quick replys.

**Comment by gandesc** [comment]
updated docs
