### ISSUE TITLE
Minor Issue on New Fresh Install

### ISSUE THREAD

**Issue by wattsie** [laravel-enso/enso#242]
This is a minor issue...

### Prerequisites
* [YEP] Are you running the latest version?
* [YEP] Are you reporting to the correct repository?
* [YEP] Did you check the documentation?
* [YEP] Did you perform a cursory search?

### Description
30% building modules 169/243 modules 74 active 
...ules/@enso-ui/tabs/src/bulma/Tabs.vue{ parser: "babylon" } is deprecated; 
we now treat it as { parser: "babel" }.

### Steps to Reproduce
1. git clone
2. setup .env
3. composer install
4. yarn
5. yarn dev

### Expected behaviour
Work with no errors or warnings

### Actual behaviour
A minor warning is thrown

**Comment by aocneanu** [comment]
We currently rely on laravel-mix 3 / webpack 3. Couldn't upgrade to laravel-mix 4 because the need of using dynamic imports.

As we speak we are in the process of migrating to vue-cli, at that point the whole ecosystem will improve, and the mentioned warning will be solved.

**Comment by wattsie** [comment]
Cool, awesome project.
