### ISSUE TITLE
Minor Issue on New Fresh Install 2

### ISSUE THREAD

**Issue by wattsie** [laravel-enso/enso#243]
This is a minor cosmetic issue...

### Prerequisites
* [YEP] Are you running the latest version?
* [YEP] Are you reporting to the correct repository?
* [YEP] Did you check the documentation?
* [YEP] Did you perform a cursory search?

### Description
On loading the website the first time, there is no logo shown.
There is a "enso.svg" in the public/images, however, the page is requesting for "logo.svg"

### Steps to Reproduce
1. git clone
2. setup .env
3. composer install
4. yarn
5. yarn dev
6. open in browser

### Expected behaviour
See logo in the top left corner

### Actual behaviour
Errored image

PS: Copying enso.svg to logo.svg fixes the issue.

**Comment by aocneanu** [comment]
Right. In the next realease this will be addressed.

**Comment by wattsie** [comment]
Sounds good. Cheers.
