### ISSUE TITLE
Building New Apps

### ISSUE THREAD

**Issue by wattsie** [laravel-enso/enso#245]
This is a question.

### Prerequisites
* [YEP] Are you running the latest version?
* [YEP] Are you reporting to the correct repository?
* [Nearly All Of It] Did you check the documentation?
* [YEP] Did you perform a cursory search?

### Description
Do you have any documentation on actually modifying core components like dashboards? Or building new components, not just CRUD table etc...

ie. if I wanted to create my own dashboard, would I remove the "examples" modules, and then implement all the similar features directly within the app?

Still digging into the core code to understand.

Any pointers would be appreciated.

Also, how do I override core features without having to patch etc.
For example, as I host my systems within AWS Beanstalk, it will pull in all dependencies directly, so if I were to modify core code when I deploy it would not be kept.
Do you have options to "publish" parts of the modules back into the main app so they can be customised?

I apologise if I have not explained myself clearly.

Cheers.

**Comment by heyner29** [comment]
What I did for example with the dashboard was to create a component in `resources/js/pages/dashboard/Index.vue` and from there I customize or add what I need.
And in `node_modules/@enso-ui/ui/src/bulma/pages/dashboard/Index.vue` the code looks like this:
![code new](https://user-images.githubusercontent.com/12703614/61723885-78502880-ad32-11e9-9aaa-87693a4be9eb.png)

Then run the `yarn patch-package @enso-ui/ui` now my panel looks like this:
![Captura de pantalla de 2019-07-23 10-18-44](https://user-images.githubusercontent.com/12703614/61724312-54d9ad80-ad33-11e9-9172-63801835c091.png)

I'm not sure it's the right approach but for now it works for me.

**Comment by aocneanu** [comment]
You should rewrite the dashboard.js route file in your local project - just copy the one from the ui package, put it in your js/routes folder an point it to a local page.vue. If it’s no longer used you can also remove the examples package..

And btw your dashboardlooks promising

**Comment by aocneanu** [comment]
Regarding AWS, following pulling the deps a build script runs, right?


And sorry for the late reply...

**Comment by wattsie** [comment]
Thanks.

Just for my curiosity, why have 'the collective' you chosen to break up the project this way, instead of say modularising each component with all CSS, JS, Vue, Other Code bundled together. For example; calendar, control panel, menu or dashboard modules.

I would have thought, patching each time you upgrade would be prone to upgrade errors and would require more development/testing time each time a new release is available.

PS: I have been using 'nWidart/laravel-modules' as it makes it easy to move the module from composer (vendor) to a local modules folder and work on a locally modified version using the original as a template.
Then, I am able to keep all laravel code, vue, scss and all supporting docs etc wrapped up in a single module.

Being able to keep it in my local modules directory, or publish to GitHub, and including it via standard composer requires makes it a breeze to use in future projects

Many thanks for your help thus far. I do like what I have seen in this project.

Please keep up the great work.

**Comment by aocneanu** [comment]
>Just for my curiosity, why have 'the collective' you chosen to break up the project this way, instead of say modularising each component with all CSS, JS, Vue, Other Code bundled together. For example; calendar, control panel, menu or dashboard modules.

We had it like this before v3, and the only way we could customize the FE from such packages was by publishing their assets locally and managing manually the flow for upgrades -> publish -> local customizations. Having this in half a dozen projects was a mess, and was really keeping us from moving forward with new projects.

>PS: I have been using 'nWidart/laravel-modules' as it makes it easy to move the module from composer (vendor) to a local modules folder and work on a locally modified version using the original as a template.
Then, I am able to keep all laravel code, vue, scss and all supporting docs etc wrapped up in a single module.

We studied this option when we knew it was time to break the project in separate modules but we really couldn't see any advantage over using composer packages.

The current form of the project is pretty much dictated by our experience with having multiple custom projects on Enso and the needs that arise from that, maintainability being key here.
