### ISSUE TITLE
Menu editor not dynamically updating menu

### ISSUE THREAD

**Issue by wattsie** [laravel-enso/enso#246]
This is maybe a bug.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description
When editing the menus, if you do changes, they are not dynamically updated.

### Steps to Reproduce
1. Clone new and setup
2. Go to menu editor, select say "data Import" or "Logs" and change the parent to "System"
3. nothing

### Expected behaviour
Menu to dynamically update based on the new layout structure

### Actual behaviour
Nothing, the menu stays as original until a full page refresh is done.

**Comment by aocneanu** [comment]
It's not meant to reconfigure when you change the menus from the form.

I would also nerver recommend moving a menu from a parent to another, I guess you saw that all the routes / breadcrumbs are static

They will reconfigure if you reload the page.

But if you are looking for menu reodering you can do this:

![ScreenRecording2019-07-23at1](https://user-images.githubusercontent.com/16073274/61712764-bd3e8400-ad5f-11e9-964d-9c020b79c662.gif)
