### ISSUE TITLE
Register view

### ISSUE THREAD

**Issue by ybaddi** [laravel-enso/enso#247]
This is  a **bug | feature request**.

### Prerequisites
* [ + ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ + ] Did you check the documentation?
* [ ] Did you perform a cursory search?

### Description

How I can add the register view, so I can give to a user the right to subscribe

**Comment by aocneanu** [comment]
Not really related to Enso.
