### ISSUE TITLE
 Overwriting problem

### ISSUE THREAD

**Issue by VadimsTalapins** [laravel-enso/enso#248]
feature request

### Prerequisites
[Y] Are you running the latest version?
[Y] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
[Y] Did you check the documentation?
[Y] Did you perform a cursory search?

### Description
I'm trying to rewrite a class User, and nothing happens.

AppServiceProvider code:
```
...
use LaravelEnso\Core\app\Models\User as EnsoUser;
use app\override\Models\User;

class AppServiceProvider extends ServiceProvider
{

    public $bindings = [
        EnsoUser::class => User::class
    ];

.....
}
```
override User code I add "username" to fillable:

```
use LaravelEnso\Core\app\Models\User as EnsoUser;

class User extends EnsoUser
{
    protected $fillable = ['person_id', 'group_id', 'role_id', 'email', 'username', 'is_active'];

}
```

**Comment by aocneanu** [comment]
Please try again with v3.4.0 (we're releasing it very soon)
