### ISSUE TITLE
Cannot login after installation - PHP 7.2 private const - syntax error (with quick solution)

### ISSUE THREAD

**Issue by pongraczi** [laravel-enso/Enso#25]
Hi,

It seems there is a problem with using **private const** in the recent php 7.2 under debian 9.

`PHP 7.2.1-1+0~20180105151615.16+stretch~1.gbpd3910a (cli) (built: Jan  5 2018 15:16:17) ( NTS )`

Laravel-enso version: latest git at 13th of Jan, 2018 (1.2.19-119-g50eb02f)

**Error message:**

`[2018-01-13 23:40:53] local.ERROR: Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) at x/vendor/laravel-enso/core/src/app/Models/User.php:19)`

**Effect of this issue:** Cannot login into the application.

**Quick and dirty resolution:**  Removing the **private** from the definition.

```
--- /var/www/clients/client1/web2/web/vendor/laravel-enso/core/src/app/Models/User.php-original	2018-01-13 22:43:34.003908721 +0100
+++ /var/www/clients/client1/web2/web/vendor/laravel-enso/core/src/app/Models/User.php	2018-01-13 22:49:43.899935429 +0100
@@ -16,7 +16,7 @@
 {
     use Impersonate, IsActive, ActionLogger, Notifiable;
 
-    private const AdminRoleId = 1;
+    const AdminRoleId = 1;
 
     protected $hidden = ['password', 'remember_token'];

```

**Comment by aocneanu** [comment]
Hi,

I didn’t tested Enso with PHP 7.2 yet, but this will follow very soon.

It seems that it's a problem with the class constant visibility.
Starting with PHP 7.1.0, the language supports modifying visibility for class constants -
 http://php.net/manual/en/language.oop5.visibility.php

Can you check your PHP version again, with ‘phpinfo()’ maybe, just to be sure that 7.2 is running?

**Comment by pongraczi** [comment]
Sorry, it seems it is my fault, you were right. As I checked the phpinfo() it reported the 7.0.27.

I made a mistake, after I upgraded to 7.2, I did not remove the old version and I did not checked my ispconfig which is the default php version.

Sorry again, I switch to 7.2 and test them again.

Thank you!

**Comment by aocneanu** [comment]
No problem, glad you found the issue.

Cheers
