### ISSUE TITLE
Vapor/Composer Install

### ISSUE THREAD

**Issue by hirsty** [laravel-enso/enso#251]
This is  a **bug**.

### Prerequisites
* [x ] Are you running the latest version?
* [x ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ x] Did you check the documentation?
* [x ] Did you perform a cursory search?

### Description

On installation onto the Serverless Service Vapor, i receive the error:    UnexpectedValueException  : Invalid route action: [LaravelEnso\DataImport\app\Http\Controllers\Import\Index].

### Steps to Reproduce

1. Git clone enso adminlte branch
2. alter env file to match db
3. composer install
4: php artisan key:generate
5. php artisan migrate
6. vapor init
7. vapor deploy

### Expected behavior
Uploads and runs smooth as silk

### Actual behavior
Got the following:
   UnexpectedValueException  : Invalid route action: [LaravelEnso\DataImport\app\Http\Controllers\Import\Index].

  at .vapor\build\app\vendor\laravel\framework\src\Illuminate\Routing\RouteAction.php:89
    85|      */
    86|     protected static function makeInvokable($action)
    87|     {
    88|         if (! method_exists($action, '__invoke')) {
  > 89|             throw new UnexpectedValueException("Invalid route action: [{$action}].");
    90|         }
    91|
    92|         return $action.'@__invoke';
    93|     }

  Exception trace:

  1   Illuminate\Routing\RouteAction::makeInvokable("LaravelEnso\DataImport\app\Http\Controllers\Import\Index")
      .vapor\build\app\vendor\laravel\framework\src\Illuminate\Routing\RouteAction.php:46

  2   Illuminate\Routing\RouteAction::parse("api/import", ["LaravelEnso\DataImport\app\Http\Controllers\Import\Index", "LaravelEnso\DataImport\app\Http\Controllers\Import\Index"])
      .vapor\build\app\vendor\laravel\framework\src\Illuminate\Routing\Route.php:162

  Please use the argument -v to see more details.
Script php artisan package:discover handling the post-autoload-dump event returned with error code 1

**Comment by aocneanu** [comment]
Hi @hirsty,

We stopped supporting the admin lte version since ~ 2 year ago.

Sorry.

**Comment by hirsty** [comment]
Not a problem, bugs with the default too, little work around is I have told composer to not auto-discover the import module
