### ISSUE TITLE
How to add more filters to the table component?

### ISSUE THREAD

**Issue by rarify-experience** [laravel-enso/enso#252]
This is a **question or possible a feature request**.

### Prerequisites
* [X] Are you running the latest version? YES
* [X] Are you reporting to the correct repository? YES
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [X] Did you check the documentation? YES
* [X] Did you perform a cursory search? YES 

### Description
I would like to know the best way to implement more filters for the table component. 
Example:
I need to have a date range From date: FIELD To Date: FIELD

### Expected behavior
Add more filters to a table component

### Actual behavior
I could only search for any field but not possible to search for an interval or add more fields to process a search.

**Comment by aocneanu** [comment]
did you look at the [example page](https://www.laravel-enso.com/examples/table)?
