### ISSUE TITLE
People routes are not been imported in vue

### ISSUE THREAD

**Issue by boing6000** [laravel-enso/enso#253]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
People routes are not been imported in vue

### Steps to Reproduce
yarn dev and try to click in user in the menu.
in console log "vue-router.esm.js?fe87:16 [vue-router] Route with name 'administration.people.index' does not exist"

### Expected behavior
open people table

### Actual behavior
not happens

**Comment by aocneanu** [comment]
I cannot replicate this

**Comment by boing6000** [comment]
I removed node_modules and did yarn install / dev probably on update from 3.4.0 the yarn maybe not updated everything.
