### ISSUE TITLE
General problem with private const + PHP 7.2

### ISSUE THREAD

**Issue by pongraczi** [laravel-enso/Enso#26]
In general, to get Enso work after installation on debian 9 + PHP 7.2 (PHP 7.2.1-1+0\~20180105151615.16+stretch~1.gbpd3910a (cli) (built: Jan  5 2018 15:16:17) ( NTS )), I had to change all **private const** appearance to **const** in all php files.

After that, the situation is much better (charts appear etc.).

**Comment by aocneanu** [comment]
related to #25
