### ISSUE TITLE
Build fails in 3.7.1

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/enso#265]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

After updating to 3.7.1 I get the following errors after calling `yarn build`

![image](https://user-images.githubusercontent.com/7204559/69239605-e4d11c00-0b9a-11ea-959a-28b19d7baf04.png)

**Comment by aocneanu** [comment]
Run yarn upgrade/composer update and you will have 3.7.2 that @gandesc is releasing now

**Comment by aocneanu** [comment]
Dont’t forget to read the release notes once 3.7.2 is up (later today)
