### ISSUE TITLE
Customize theme in 3.7.x

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/enso#266]
This is  a **help request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Before update to 3.7.x I have had overwritten the theme.
It's stored now in client/src/sass/themes/light.scss and dark.scss

In old webpack config I added the 2 themes the following:
```
.sass('resources/sass/themes/light.scss', 'public/themes/light/bulma.min.css')
    .sass('resources/sass/themes/dark.scss', 'public/themes/dark/bulma.min.css')
```

How can I handle this in new version?    

Thx in advance for your help.

**Comment by aocneanu** [comment]
You can do a patch (using patch-package) on the `@enso-ui/src/modules/layout.js` and change

```js
const themes = themeImporter(require.context('@enso-ui/themes/bulma', false, /.*\.lazy\.scss$/));
```

to whatever you want. If you want to change the theme names make sure you sync this to the `themes.php` config file

**Comment by mauthi** [comment]
Hi @aocneanu,

thx for your help.

I created the patch like described above and the build was successful.
But the theme looks like your default theme and not like my overwritten theme before 3.7.x

How can I check if my theme is used?

**Comment by mauthi** [comment]
Sorry, my mistake.
`yarn build --watch` did not compile the changed theme.
Now I run `yarn build` and everything is fine.
