### ISSUE TITLE
Browser debug console errors after update to 3.7.2

### ISSUE THREAD

**Issue by adithewonderboy** [laravel-enso/enso#269]
This is  a **bug**.

### Prerequisites
* [ x] Are you running the latest version?
* [ x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ x] Did you check the documentation?
* [ x] Did you perform a cursory search?

### Description
![console_err_enso372](https://user-images.githubusercontent.com/58045802/69415158-c85ced00-0d1c-11ea-96bf-0e1322d6a067.png)

After login the following errors appear in debugger console. They seems to be related to the new vue-cli build..

### Steps to Reproduce

1. Update to Enso version 3.7.2
2. Build the resources using new vue-cli
3. Login to application and open browser debug console
4. Check the console for error messages

### Expected behavior
The debug console should not contain any errors regarding the build

### Actual behavior
The debug console shows a bunch of errors related probably to vue-cli build

**Comment by aocneanu** [comment]
I am unable to replicate this.

Do you have your websockets setup right?

**Comment by adithewonderboy** [comment]
Are there any extra changes on the enso 3.7.2 regarding sockets? I haven't
had this issue on 3.6.1
I mention that I run enso on windows with apache, if that matters.

Thanks

**Comment by adithewonderboy** [comment]
This is no longer an issue after we updated our code part. 
Thank you!
