### ISSUE TITLE
Help disable eslint checks

### ISSUE THREAD

**Issue by adithewonderboy** [laravel-enso/enso#270]
This is  a **help request**.

### Prerequisites
* [x ] Are you running the latest version?
* [ x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ x Did you check the documentation?
* [x ] Did you perform a cursory search?

### Description
The Eslint checks are giving us a lot of errors especially with line endings, curly braces, line length and so on.
Is there an easy way to disable eslint from doing this? .eslintignore file seems to be ignored.
Also modifying the eslint rules doesn't seem to do the trick either...

### Steps to Reproduce
1. Update to enso 3.7.2
2. Build the assets
3. Yarn watch
3. Change some .vue or .js files
4. In many cases eslint raises errors and the build crashes

### Expected behavior
We want to disable eslint and use our project code formatting.

### Actual behavior
Eslint complains about formatting and the builds are constantly crashing.

**Comment by mauthi** [comment]
You can call the linting with `--fix` - then most of the errors are fixed automatically.
(I had 1.300 errors and the --fix solved ~1.220 of them)

**Comment by adithewonderboy** [comment]
Yes, I already tried that, and the build is ok but when I run "yarn build--watch" and change one file, then is constantly crashing again.., even if I try also with "yarn build --watch --fix"

**Comment by mauthi** [comment]
I think it should be changed from errors to warnings - but I'm also beginner in this topic.

**Comment by adithewonderboy** [comment]
I already tried that in eslintrc file but it didn't work, because many
rules are  inherited from vue itself.

**Comment by aocneanu** [comment]
You will have to modify (in sync) both eslint files and setup your personal rules. The one in the root folder, used by editors, and the one in under the client folder used by vue cli service.

**Comment by aocneanu** [comment]
Regardin the rules inherited from vue, it was one of the main reasons why it took so long for us to migrate on vue cli. But eventually we conformed with them.

**Comment by adithewonderboy** [comment]
> You will have to modify (in sync) both eslint files and setup your personal rules. The one in the root folder, used by editors, and the one in under the client folder used by vue cli service.

Thanks for this explanation, I did not understand from the documentation which eslint file is used or not and for what purpose. Can you add this mention on documentation also? It can save a lot of time for any others that have these issues. I spent precious time trying to understand why my rules are working in some cases and not working in other ones

**Comment by aocneanu** [comment]
@gandesc please add a mention regarding this in docs.

**Comment by adithewonderboy** [comment]
Thank you!
