### ISSUE TITLE
Friendly reminder to update main Docs page

### ISSUE THREAD

**Issue by wbovela** [laravel-enso/enso#271]
This is  a reminder.

### Prerequisites
* [x ] Are you running the latest version?
* [x ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ x] Did you check the documentation?
* [x ] Did you perform a cursory search?

### Description
The "try it up" description is outdated. The steps are incomplete and do not lead to an up-and-running app in 5 minutes

### Steps to Reproduce
1. First Step
2. Second Step
3. and so on...

### Expected behavior
A working app. Possibly in 5 minutes.

### Actual behavior
running "yarn" leads to "package.json" not found.
running "php artisan migrate" leads to access error because no database present.
database is not seeded, so no user present.

**Comment by gandesc** [comment]
Hi @wbovela 

Thanks for the reminder, the page was updated
