### ISSUE TITLE
Spa and AppState flexibility

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/enso#272]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
If one wants to change a bit the behavior of Enso's permission system some changes might be needed inside the `src/app/Http/Responses/AppState.php`, but in order to do this there are some problems arising:, 
1.  Most methods are private, so inheritance and method overwrites do not work
2. Since AppState is instantiated with "new" inside Spa

```php
namespace LaravelEnso\Core\App\Http\Controllers;
...
class Spa extends Controller
{
    public function __invoke()
    {
        return new AppState();
    }
}
```
an additional bind has to be made on Spa class in order to instantiate AppState through "app" so that bind will work. Ex: `return app(AppState::class);`

My request is more into getting some flexibility on these 2 files, with minimal effort on your side, and better integration on everyone else's side:)

Let me know if this is something that you will accept, and I can do a PR on this change and take one of your back. Only if it goes well with your plans...

Thank you,

**Comment by robbykrlos** [comment]
Great. Thanks. Will do. Will keep you posted.

PS: maybe I'll make protected also the privates in the "menus/src/app/Services/TreeBuilder.php" which is also instantiated in AppState with "new".But this is in the Menus subproject, not core.

**Comment by robbykrlos** [comment]
Done.
Under:
https://github.com/laravel-enso/core/pull/127
https://github.com/laravel-enso/menus/pull/20

Thanks!

PS: I guess will close this after PR is done.

**Comment by aocneanu** [comment]
Why would we need to customize treebuilder?

**Comment by robbykrlos** [comment]
> Why would we need to customize treebuilder?

For the same reasons I've mentioned in the description of this issue - in case someone wants to change how the permission system works, or authentication TreeBuilder contains parts that are needed for such customizations
```php
protected function permissions(): self
    {
        $this->permissions = Auth::user()->role
            ->permissions()
            ->has('menu')
            ->get(['id', 'name']);

        return $this;
    }
```

Maybe the whole system of "User has role" is changed with "User has roles"

Therefore maybe something like this is needed:
```php
$this->permissions = Auth::user()->getRolesPermissions()->... 
```
Again, if you feel like it's not a good idea, reject the TreeBuilder PR.

My thinking was that if permission logic is defined inside the menus it needs to be flexible for inheritance...

Thank you.

**Comment by aocneanu** [comment]
We've refactored the tree builder a few times until recently. If we go this path it would be one more thing to consider in the future.

I guess with the other MR this case would be covered too. By resolving TreeBuilder from the container anybody could write their own logic for that. This service is used in the AppState exclusively, anyway.

**Comment by robbykrlos** [comment]
Couldn't agree more:)
