### ISSUE TITLE
unable to get it running.

### ISSUE THREAD

**Issue by nichter** [laravel-enso/enso#273]
This is  a **Mistake** | bug | feature request.

### Prerequisites
* [ x] Are you running the latest version?
* [x ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ x] Did you check the documentation?
* [ ] Did you perform a cursory search? **not possible**

First of all thank you very much for this excellent development that you have put to the community. I am contemplating using it as an **alternative** to a **boilerplate with themes with Vue** once the user has entered the system, through assets and blade, a compiled page would practically be used and incorporated as a theme.
**Your approach is different**, I would like to analyze it more. However, I must say that I am new to Vue and the associated compilation processes, I apologize.
Well now I want to launch this application locally, I have a PC with Windows 10, which apparently does not work for some horizon requirements and has a Linux like wsl per, virtual machine and a partition with Ubuntu. (I must boot separately)
I have carefully followed the instructions and I can compile the project well, without problems, only some warning, but when executing it, the green screen only appears.
I have followed in detail the installation procedure described on the main page.
Code is downloaded from repository indicated.
.Env.example file is used to generate .env according to point 3, key for app is created.
In client folder you change API_URL = http: // localhost: 80 /
Yarn && yarn build is used in development environment
Yarn serve is run and verified on host http: // localhost: 8080
if it helps the generated code is: 

<table>
<tr><td>

&lt;!DOCTYPE html&gt; &lt;html&gt; &lt;head&gt; &lt;meta charset=&quot;utf-8&quot;&gt; &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt; &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1&quot;&gt; &lt;link rel=&quot;icon&quot; type=&quot;image/png&quot; href=&quot;/images/favicon.png&quot;&gt; &lt;title&gt;Enso&lt;/title&gt; &lt;link href=&quot;/js/0.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/1.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/10.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/11.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/12.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/13.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/14.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/15.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/16.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/17.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/18.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/19.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/2.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/20.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/21.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/22.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/23.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/24.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/25.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/26.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/27.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/28.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/29.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/3.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/30.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/31.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/32.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/33.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/34.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/35.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/36.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/37.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/38.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/39.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/4.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/40.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/41.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/42.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/43.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/44.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/45.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/46.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/47.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/48.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/49.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/5.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/50.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/51.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/52.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/53.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/54.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/55.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/56.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/57.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/58.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/59.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/6.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/60.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/61.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/62.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/63.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/64.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/65.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/66.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/67.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/68.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/69.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/7.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/70.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/71.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/8.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/9.js&quot; rel=&quot;prefetch&quot;&gt;&lt;link href=&quot;/js/chunk-vendors.js&quot; rel=&quot;preload&quot; as=&quot;script&quot;&gt;&lt;link href=&quot;/js/main.js&quot; rel=&quot;preload&quot; as=&quot;script&quot;&gt;&lt;/head&gt; &lt;body&gt; &lt;noscript&gt; &lt;strong&gt;We're sorry but the frontend doesn't work properly without JavaScript enabled. Please enable it to continue.&lt;/strong&gt; &lt;/noscript&gt; &lt;div id=&quot;app&quot;&gt;&lt;/div&gt; &lt;!-- built files will be auto injected --&gt; &lt;script type=&quot;text/javascript&quot; src=&quot;/js/chunk-vendors.js&quot;&gt;&lt;/script&gt;&lt;script type=&quot;text/javascript&quot; src=&quot;/js/main.js&quot;&gt;&lt;/script&gt;&lt;/body&gt; &lt;/html&gt; 

</td></tr></table>

I would really appreciate if you can tell me where to correct the code or configuration to use so that I can run this demo locally.
I am using the following configuration
Development platform
- Ubuntu 18.04 LTS
- php -v 7.4.1
- npm –v 6.13.6
-yarn v1.21.1
- directly programmed, that means no docker, etc..
have tested windows config doesnt work
wsl config doesnt work.
virtual box + ubuntu  on windows same results as ubuntu OS.

Thanks 

Carlos

**Comment by raftx24** [comment]
Hi Nitcher.
did you run `php artisan serve` in the project root?
can you send console log too?

**Comment by heyner29** [comment]
Hi, did you do this step too?
`php artisan migrate --seed`

The Yarn serve step is optional, only if you want each one to make a change to be compiled automatically and reload the browser.

Finally, I have used it in Linux and in Windows.  Only for Windows you should use

`composer install --ignore-platform-reqs`

**Comment by nichter** [comment]
Hi raftx24
if i use "php artisan serve" on the browser i get the InvalidArgumentException
View [index] not found. Are you sure the view exists and is a .blade.php file?,,,, error says 
I didnt changed anything in the code.


![imagen](https://user-images.githubusercontent.com/30216755/72991323-ccaa9280-3dbf-11ea-88af-97bdd87d47ed.png)

regarding the question from Heyner, Sure i ran migrate and seed. The db is populated...

i trying to compile on windows on mean time...

**Comment by raftx24** [comment]
No, you need to run `php artisan serve`.
You can follow the below.
1. go to the project and run `php artsian server`
2. in another terminal go to `project-path/client` and run `yarn serve`
3. then you can run the application on localhost:8080

**Comment by nichter** [comment]
Thank you raftx24
oh .. i see:
well i opened 2 terminals
1) on the first i start php artisan serve --- and says Server (http://127.0.0.1:8000) started
2) on the second terminal i start yarn serve and says 
 App running at:   - Local:   http://localhost:8080/ 
3) note that are pointing to two differents ports (8000 and 8080). i tried o use the port 8080 for both
  if i ran php artisan serve --port=8080 and start yarn ..it says if starts on port 8081
  i is not possible to have both services pointing o the same port.   
  if i ran the browser on http://localhost:8080 i get problem from "view [index] not found
  if i ran the browser on http://localhos;8081 i see only the green page
4) i also tested running first yarn  which opens port 8080 and php artisan server with option --port=8080 it says is not possible because port is taken..

5) if i run the same proyect (without modifiing any option) on windows with the option "composer install --ignore-platform-reqs" i get a pink box with this error "
![imagen](https://user-images.githubusercontent.com/30216755/73002470-1ac89180-3dd2-11ea-95dc-fa77a5418cb9.png)
So.. now i have more questions... but i woud like to see it working
i have only a small mac to test the code and i dont thing i can put to much things on it.

**Comment by raftx24** [comment]
nitchter, no you don't need to set ports manually. 
`php artsian serve` should run on port 8000
and `yarn serve` should run on port 8080

**Comment by nichter** [comment]
Mr raftx24, thank for quick reply.
so as i mentioned before it doesn't work... i still receive the geen board even if i have two server running.
