### ISSUE TITLE
Question Nester Routes using EnsoTables

### ISSUE THREAD

**Issue by elysiopires** [laravel-enso/enso#276]
This is  a **Question**.

### Prerequisites
* [ ] Are you running the latest version? 3.7.2
* [ ] Are you reporting to the correct repository? yes
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ ] Did you check the documentation? yes
* [ ] Did you perform a cursory search? yes

### Description
I have on my side this scenario:

locations
and locations.operators

We are planning to use operators table inside Edit form using Slot.

My question is about the route, I made my changes like this:

`
 
    Route::middleware(['web', 'auth', 'core'])
    ->group(function () {

        Route::namespace('Locations')

            ->prefix('locations')->as('locations.')

            ->group(function () {
                Route::get('', 'Index')->name('index');
                Route::get('create', 'Create')->name('create');
                Route::post('', 'Store')->name('store');
                Route::get('{location}/edit', 'Edit')->name('edit');

                Route::patch('{location}', 'Update')->name('update');

                Route::delete('{location}', 'Destroy')->name('destroy');

                Route::get('initTable', 'InitTable')->name('initTable');
                Route::get('tableData', 'TableData')->name('tableData');
                Route::get('exportExcel', 'ExportExcel')->name('exportExcel');

                Route::get('options', 'Options')->name('options');
                Route::get('{location}', 'Show')->name('show');
                Route::get('{location}/uploads', 'Uploads')->name('uploads');
                Route::namespace('Operators')
                    ->prefix('operators')->as('operators.')
                    ->group(function () {

                        Route::get('{location}/', 'Index')->name('index');
                        Route::get('{location}/create', 'Create')->name('create');
                        Route::post('{location}/', 'Store')->name('store');
                        Route::get('{location}/{operator}/edit', 'Edit')->name('edit');

                        Route::patch('{operator}', 'Update')->name('update');

                        Route::delete('{location}/{operator}', 'Destroy')->name('destroy');

                        Route::get('{location}/initTable', 'InitTable')->name('initTable');
                        Route::get('{location}/tableData', 'TableData')->name('tableData');
                        Route::get('{location}/exportExcel', 'ExportExcel')->name('exportExcel');

                        Route::get('{location}/options', 'Options')->name('options');
                        Route::get('{location}/{operator}/show', 'Show')->name('show');

                    });
            });
    });
`

When I access /api/locations/operators/1/initTable

I'm getting the following error:

> Illuminate\Routing\Exceptions\UrlGenerationException
Missing required parameters for [Route: locations.operators.tableData] [URI: api/locations/operators/{location}/tableData].

What is the best way to get this working with Enso? 
When I enter: /api/locations/operators/1/initTable should get the operators only for location 1, this is the requirement...

### Steps to Reproduce
N/A

### Expected behavior
Enso Table works with nesters routes

### Actual behavior
Enso Table not working with nesters routes

**Comment by aocneanu** [comment]
>We are planning to use operators table inside Edit form using Slot.

You really got me confused here. Maybe you could post a screen shot of how this will turn out.

`vue-table` can receive a `path` prop where you can give it whatever you need

`vue-table :path="route('my.nested.route', { param: 1 })`

If you want to use the page route path

`vue-table :path="$route.path`

Is this what you're looking for?
