### ISSUE TITLE
Choosing Date/Datetime and number format 

### ISSUE THREAD

**Issue by pongraczi** [laravel-enso/enso#277]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [ ] Did you perform a cursory search?

### Feature request
It would be useful to be able to control formats inside the application UI instead of via config files.

### Expected behavior
User can choose his/her locale and preferred number/date format under his/her preferences.

### Actual behavior
At this moment the dateformat is forced by the relevant config file and system wide, it is not possible to control it via the frontend and even have different format for every user.  
I had to change the dateformat in 3 different config files and datetimeformat in 1 config file.

**Comment by aocneanu** [comment]
Hi @pongraczi 

Feel free to make a PR for this.

The reason you have to set the dateformat in 3 places is because forms and tables are standalone packages.

**Comment by pongraczi** [comment]
Thank you Adrian for the explanation, now it is more clear.
