### ISSUE TITLE
Can not find the reason for this message: "The menu's route does not match the configured permissions"

### ISSUE THREAD

**Issue by whizzly** [laravel-enso/enso#279]
I try to configure my first new object via cli.
But i ran always into the above message and can not find where i have a misconfiguration.

Could you please give me a hint where i have a search, what i have to do?
Tried different things, but no success ...
thx in advance

**Comment by whizzly** [comment]
i hope you can view the attached config video
![out-2](https://user-images.githubusercontent.com/24956733/75631950-94d10f00-5bf7-11ea-99db-3f82f9791e30.gif)

**Comment by aocneanu** [comment]
The problem is that you permission group is `cars` and the permissions are being generated with this prefix `cars.*`. For the menu you specified `administration.cars.index`.

You can either change the permission group to `administration.cars` or change the menu permission to `cars.index`

**Comment by whizzly** [comment]
hmm, i have tested now very much combinations. the key point is the route in the menu config:
the only way it works is to write "index", nothing else works. And i am not so experienced to say that this is okay. Maybe a bug? Or is that okay?:
Copy and paste the following code into your api.php routes file:
```

<?php

use Illuminate\Support\Facades\Route;

Route::middleware(['web', 'auth', 'core'])
    ->group(function () {
        Route::namespace('Administration\Dogs')
            ->prefix('administration/dogs')
            ->as('administration.dogs.')
            ->group(function () {
                
		Route::get('', 'Index')->name('index');
		Route::get('create', 'Create')->name('create');
		Route::post('', 'Store')->name('store');
		Route::get('{dog}/edit', 'Edit')->name('edit');

		Route::patch('{dog}', 'Update')->name('update');

		Route::delete('{dog}', 'Destroy')->name('destroy');

		Route::get('initTable', 'InitTable')->name('initTable');
		Route::get('tableData', 'TableData')->name('tableData');
		Route::get('exportExcel', 'ExportExcel')->name('exportExcel');

		Route::get('options', 'Options')->name('options');
		Route::get('{dog}', 'Show')->name('show');


        });
    });

```

**Comment by whizzly** [comment]
Thank you very much for your answer. All works like explained and expected ...
I might want to rewrite an open source project for veterinarians. Its a question of time ... and patience.
Have a nice week.
