### ISSUE TITLE
Why i can not see my new objects created with the cli?

### ISSUE THREAD

**Issue by whizzly** [laravel-enso/enso#280]
This is  a **bug request**.
* [* ] Are you running the latest version?
* [*] Are you reporting to the correct repository?
* [*** ] Did you check the documentation?
### Description:

There are many errors in the documentation. That should be known. It starts with the fact that, for example, it only becomes clear with the command "composer install" that PHP 7.4 is necessary.

The section for the cli has the first error at point 0. The documention says that backslashes have to be set, but you have to take forward slashes.
But all of that is not so bad.

The menu is a bit less clear then. That's why I asked the issue #279.
It only works if you write “index” on the route without anything else before or after index. Thought that was the solution. But ...

After that it says in the documentary you should see the new menus after the next "yarn build". Unfortunately, this is not the case. Is the reason now that I wrote something wrong in the menu / route or is the cli broken?
Too bad it takes a lot of time to search ...

### Steps to Reproduce
1. config the cli with a new object, for example Dog or Cat
2. yarn && yarn build
3. start the app in localhost:8080
### Expected behavior
new menus or tables or forms for dogs or cats
### Actual behavior
standard app without the new object

git status:
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	app/Dog.php
	app/Forms/
	app/Http/Controllers/Dogs/
	app/Http/Requests/
	app/Tables/
	client/src/js/pages/dogs/
	client/src/js/routes/dogs.js
	client/src/js/routes/dogs/
	database/migrations/2020_03_05_192933_create_dogs_table.php
	database/migrations/2020_03_05_192934_create_structure_for_dogs.php

which of the files do you need? i can upload

**Comment by whizzly** [comment]
Okay, it seems that the menu-link itself works, if i write that by hand. Also i did not respect the rest with the validation and the filling of templates for the tables and the forms. Here i was to fast.
But It rests also the permissions, they are not there ... and the menu topics in the surface ...
I will see this week. 
Maybe you could tell something in short to the two points.
thy a lot in advance
Dirk

**Comment by gandesc** [comment]
Hi @whizzly ,

I take it that you are missing the permissions? Perhaps you can clarify what is the current issue?

If that is indeed the case i.e. the permissions missing, please make sure that you reload the application (refresh the page) after running the migrations.

The reason for needing the reload is that the app permissions are loaded on startup.

Basically, after using the cli to create a structure what I usually do is:
- run the migrations (`php artisan migrate`)
- add the new routes
- check that the routes are fine by running, `php artisan route:list`, verifying that my new routes are in the list and that they point to the new controllers
- do a front-end build with `yarn build` or, if I was using serve, stop and re-run `yarn run serve`
- go into the browser, reload the page and check that the new menu is there
- open the menu, check that the table is loading and displays no results.

From this point on, I usually revert the migrations, and start modifying as required:
- add columns to the table by editing the create table migration
- add the new attributes to the model's $fillable
- add relationships if needed
- edit the table builder, update the select & include the new columns
- edit the table template & include the new attributes
- edit the form template & include the new attributes
- edit the request validation & add the new attributes
- re-run the migrations
- reload the page, go into the new menu, create a new model instance using the form
- go back, check that the new model is shown in the index table
- rinse & repeat

Yes, the documentation is slightly out of date, we're aware of this and it's on the to-do list. If you're so inclined, you can even make PRs for punctual updates :)

In the meantime, I hope I've helped and do let us know if you bump into other things

**Comment by whizzly** [comment]
hi gandesc,
thank you very much for the answer. I work on this in my free time and accordingly i can only answer when i am not at work. I will try to process the steps you recommended and when i have any other problem i open a new issue especially for that problem. At this place, i close this one.
nice weekend
