### ISSUE TITLE
add the new routes

### ISSUE THREAD

**Issue by whizzly** [laravel-enso/enso#281]
@gandesc 
you wrote in #280:
"
- run the migrations (php artisan migrate)
- add the new routes
- check that the routes are fine by running, php artisan route:list, verifying that my new routes are in the list and that they point to the new controllers
"
php artisan migrate works fine 
what exactly do you mean with "add the new routes"? Is that at the end from the cli-config, when is written "Copy and paste the following code into your api.php routes file:"?
[route_list.txt](https://github.com/laravel-enso/enso/files/4305486/route_list.txt)
 That is what i do.
Then there are only the api routes, no named routes. And the named routes point for example to "App\Http\Controllers\Vs\Dogs\Index" . And i had to write App/Dog at the model-Topic. So that seems to be right, but in the file system there is no directory App, only app (small letters). Is that really okay?

**Comment by gandesc** [comment]
> what exactly do you mean with "add the new routes"? Is that at the end from the cli-config, when is written "Copy and paste the following code into your api.php routes file:

Yes, that's exactly what I meant.

> but in the file system there is no directory App, only app (small letters). Is that really okay?

Yep, that's okay, and it's unrelated to the Enso cli, it's Laravel specific as you have this in the `autoload` section of `composer.json`

![image](https://user-images.githubusercontent.com/14071925/76196285-a798a480-61f2-11ea-85e9-e2f218450af3.png)

So, I take it that the new structure works? :)

**Comment by whizzly** [comment]
Until this point, yes. Thx for the answer. I just wasn't sure, because i did not find that entry, you showed me now.
Second point is - so i think - my docker config. I am playing around with some thing at the moment. enso requires a php 7.4 and in my local ubuntu-environment i only have 7.3. ...
docker works fine with postgresql and nginx 
but yarn has a bug in yarn serve in this constellation, only yarn build works
Normally i use npm ...

**Comment by gandesc** [comment]
If looking for a docker image with 7.4 maybe this could be useful: [chilio/laravel-dusk-ci:php-7.4](https://hub.docker.com/layers/chilio/laravel-dusk-ci/php-7.4/images/sha256-bece18547fed78cf6a82d0f5f5f88e9c9ac6a9d44717fd427c6880b78ad9d0fd?context=explore)

**Comment by whizzly** [comment]
my images work, thx a lot. Have one with postgresql and nginx.
Next point is this one:
it looks like the path structure is not entirely correct. After my yarn build i have the menus and when i click it, i always got the message that the json template for the table can not be found. A slash is missing between the permission group and the json file.
...Templates/Vsdogs.json -- should be ...Templates/Vs/dogs.json
Maybe a mistake in my config? But can not find where exacly. I have saved the config-session-file, you can find it in the attachement.

**Comment by whizzly** [comment]
it is your topic from #280:
- open the menu, check that the table is loading and displays no results.
I think that this is probably the point where i have to revert the migration and to fill all the templates

**Comment by whizzly** [comment]
have adapted all the paths and templates, but i still get a
"something" went wrong ...
is there a logfile or something like that where i can controll the message?

**Comment by whizzly** [comment]
ok, i have found the laravel log with:
[2020-03-09 15:56:36] local.ERROR: chmod(): Operation not permitted {"userId":1,"exception":"[object] (ErrorException(code: 0): chmod(): Operation not permitted at /var/www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:198)

**Comment by whizzly** [comment]
ok, corrected.

**Comment by whizzly** [comment]
lastly i hang with a problem with enums
But the main problem is soluted
Thx a lot
