### ISSUE TITLE
Fresh installation, PHP syntax error(s)

### ISSUE THREAD

**Issue by kplgr** [laravel-enso/enso#284]
This is  a **bug (?)**.

### Prerequisites
* [ x] Are you running the latest version?
* [ x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x ] Did you check the documentation?
* [ x] Did you perform a cursory search?

### Description

I am following the documentation at https://docs.laravel-enso.com/ , trying to setup a fresh install.
When I try to open the website, I get a PHP error that says 

Symfony\Component\Debug\Exception\FatalThrowableError
syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST) 

The problem seems to be at vendor/laravel-enso/calendar/src/UserServiceProvider.php:14

Is this some kind of PHP related problem ? I don't see anything wrong with line :14 in that file... 
If I comment that line out for debugging, then I get another error at some point where anonymous functions are used.
Maybe some configuration steps are required but not explicitly stated in the documentation, in order for enso to work out of the box?

**Comment by heyner29** [comment]
What version of PHP do you have installed?
