### ISSUE TITLE
is it possible to use for one table an individual dtRowId?

### ISSUE THREAD

**Issue by whizzly** [laravel-enso/enso#286]
This is  a **feature request**.

is it possible to use for one table an individual dtRowId?
for overwrite the central one in config/enso/tables.php ...
commented out and wrote "as "dtRowId" " in app/Tables/Builders .." but that does not seem to work
thx for a hint

**Comment by aocneanu** [comment]
You can customize it in the template.

**Comment by whizzly** [comment]
in which template? in app/Tables/Templates?
I tried:
```
{
            "label": "rasse_id",
            "name": "rasse_id",
            "data": "vs_rasses.rasse_id as dtRowId",
            "meta": [
                "searchable",
                "sortable"
            ]
        },
```
that leads to a syntax error in the laravel.log ->
... from \"vs_rasses\" order by \"vs_rasses\".\"rasse_id\" as \"dtRowI...

**Comment by whizzly** [comment]
just in this moment: found it
            "data": "rasse_id as dtRowId",
works, followed by the 4 php artisan clear commands: cache:clear, config:clear,route:clear,view:clear
thx

**Comment by aocneanu** [comment]
Actually, that works only by accident.

What you should do is add `"dtRowId": "rasse_id"` at the root level of your json.

**Comment by whizzly** [comment]
that works, thx a lot
