### ISSUE TITLE
How to get current authenticated user id to be the default value in  enso-select -filter

### ISSUE THREAD

**Issue by kitcChu** [laravel-enso/enso#288]
This is  a feature request.

### Prerequisites
* [x] Are you running the latest version?
* [x ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ x] Did you check the documentation?
* [x ] Did you perform a cursory search?

### Description
How to get current authenticated user id to be the default value in  enso-select-filter

**Comment by aocneanu** [comment]
Extract it from the local store (Vuex). It’s in the root.

**Comment by kitcChu** [comment]
It works very well like this:
computed:{
   ...mapState(['user'])
   current user(){ return this.user.id}
},  

<enso-select-filter>
....
    value="currentUser"

**Comment by aocneanu** [comment]
Can we close this?

**Comment by kitcChu** [comment]
Sure, Thanks for you help! Very Good Application
