### ISSUE TITLE
error when creating CRUD struncture

### ISSUE THREAD

**Issue by itarafath** [laravel-enso/enso#289]
I tried to create CRUD structure using enso:cli, but always I'm getting this error
Please check the attached G-DRIVE link
The menu's route does not match the configured permissions
[video](https://drive.google.com/file/d/1zaisHvgPlp7VgfozGOpsI7Cmnx-yz4O3/view?usp=sharing)

Thanks in advance

**Comment by heyner29** [comment]
The documentation is not up to date yet I think, but it is no longer necessary to add the permission group, just the path as such. In your case you should just write `index ` in the menu path.

**Comment by heyner29** [comment]
And for future consultations on the same topic, I think it would be appropriate for you to do so on the package [repository](https://github.com/laravel-enso/cli), for organizational reasons :)

**Comment by aocneanu** [comment]
@gandesc please review the docs for cli

**Comment by aocneanu** [comment]
@itarafath please use the issue template from now on.

**Comment by itarafath** [comment]
Thanks, @heyner29 @aocneanu 
Administration routes do not working except the new one, after CRUD structure created

**Comment by heyner29** [comment]
Yes, that was also discussed here in [this thread](https://github.com/laravel-enso/cli/issues/30)

**Comment by itarafath** [comment]
@heyner29 
Could you please describe this little more.
This is confusing me
Thanks
