### ISSUE TITLE
show-button - is there a default template for this action?

### ISSUE THREAD

**Issue by whizzly** [laravel-enso/enso#290]
A final holdover of the results of my experiments/test is that point:
the show button at the left hand side (the eye)
![grafik](https://user-images.githubusercontent.com/24956733/77578071-2e7a9c00-6ed8-11ea-8ae7-8ad4de41b121.png)
does not show anything even if i configure all the points that i found in the documentation or in the tipps of the super nice answer from mihai.
I dug a little deeper and into the standard enso the only place i found a show component was there:
`~/enso/client/node_modules/@enso-ui/ui/src/bulma/pages/administration/users/components/UserProfile.vue`
is there a standard config for that, that i can take or should i only remove the show button ... i think i dont need it really (what exactly have i to do for removing?)
Not shure for the moment what i should do.
Sincerely yours

**Comment by aocneanu** [comment]
If you don't need a show route then don't generate it with the cli.

From the table json template just remove the show button.

Does that answer the question?

**Comment by whizzly** [comment]
Thank you for the answer.
In principle, yes, but the real question was hidden in the title:
Is there a piece of documentation or any default template/example like for the json-template (--> https://docs.laravel-enso.com/backend/forms.html#usage) .

**Comment by aocneanu** [comment]
I'm afraid there is no default template for this action because.

The show page would be a presentation page for a model, when you need it.

**Comment by whizzly** [comment]
Ok, thx for the info ...
