### ISSUE TITLE
dtRowId does not work

### ISSUE THREAD

**Issue by whizzly** [laravel-enso/enso#291]
I can't get it straight. I have a table with a special "dtRowId" in the json template. Everything is displayed correctly in the table overview. 
But create and edit fails with "SQLSTATE [42703]: Undefined column: 7 ERROR: column \" id \ "does not exist" in the laravel log. I've already cleared the cache. And yarn build.
Everything is searched with grep -ri id *, but cannot find a place where the id is still located.
Could that be a bug? Or do you have a tip where I can still search.
Model name: vs_rasse
Maybe it's the underscore in the model name. But the files seems to be correct. See attachement please ...
[vs_rasse_files.tar.gz](https://github.com/laravel-enso/enso/files/4393449/vs_rasse_files.tar.gz)

**Comment by aocneanu** [comment]
Use the issue template.

Explain step by step what you're doing.

Posting screenshots may help
