### ISSUE TITLE
Company based privilege

### ISSUE THREAD

**Issue by subtain-haider** [laravel-enso/enso#296]
Hello again. 
Does enso provides company based privilege?
For example one company have many users and one Mandatory 
So when that Mandatory logins he should only see users from his own company and can manage users only from his own company 
And similarly when any user login he should only see his own team and his own team members.
Or he can see his own company mambers and can CRUD documents, discussions, comments, of only his own company

Does enso have such feature or we have to make it by own?

Sorry am not using template coz am on mobile and not have access to laptop now.
Thank/.

**Comment by aocneanu** [comment]
Nope, but you can do achieve this in multiple ways in your local project. Either create a local instance of the controller and point to a custom table builder. Or create a global scope for users and so on.

**Comment by subtain-haider** [comment]
so can u we use Multitenancy package of enso, to achieve this thing???

**Comment by aocneanu** [comment]
You can also create a local UserTable that extends the one in the package and bind that in an service provider then write your custom logic.

Multitenancy is built to handle separate databases for each tenant and is still experimental.

**Comment by subtain-haider** [comment]
thank you so much sir
