### ISSUE TITLE
login from mulitple tables

### ISSUE THREAD

**Issue by subtain-haider** [laravel-enso/enso#297]
This is  a ** feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
Hello Everyone,
Enso have provided following tables
People, Users
The user table has foreign key of people table and the use can be generated from people.

I have following my own tables which have email column.
Teachers, Students,     and I have also added teacher and students user_group
and am also using people table as Staff and am generating users from People tables.

Now I want tht whenever a new teacher or student is added a new user should be made with respective group_id and similarly I should be able to login using tht email id.

So how can I use same login form and same user table, as the user table have person_id foreign key so I cant add user through teachers controller coz it requires person_id

am struggling in the login and also in the implementation.
which is the best and easiest way to use it with enso?

and it will be greatttt if anyone reading this can help me building through this, I will be very great full of you and even I can pay some if you want. I really want some help for this project.
and am asking this here coz I havent seen any other forums where people are working with ENSO

THANKS...

**Comment by aocneanu** [comment]
Consider database normalization. Teachers, Students are all People.

Extend the people structure by adding either an Enum with a function (teacher, studend, other) or booleans like is_teacher, is_student.

That's exactly what we're doing in our apps.
