### ISSUE TITLE
multiple v-model binding in enso

### ISSUE THREAD

**Issue by subtain-haider** [laravel-enso/enso#298]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
I have following packages and there database tables respectively:

Companies:
https://github.com/subtain-haider/companies_backend
![companies](https://user-images.githubusercontent.com/60756535/78748837-6a0c7000-7986-11ea-9cfb-fd853d320c38.png)

Grades:
https://github.com/subtain-haider/vendor_sibtain/tree/master/grades/src
![grades](https://user-images.githubusercontent.com/60756535/78748874-7ee90380-7986-11ea-9029-df648edfd534.png)

Classrooms:
https://github.com/subtain-haider/vendor_sibtain/tree/master/classrooms
![classrooms](https://user-images.githubusercontent.com/60756535/78748866-7abce600-7986-11ea-818b-261d8e27ea5a.png)

now while creating a new class room I select a company and then a grade and after tht there is an input field named "abbreviation"
 I want that when I select the company: its **code**(database field of companies table ) should be displayed in the abbreviation text field.
and when I select the grade,: its **abbreviation**(database field of grades table ) should be written after the **code** in the abbreviation text field.

For example in above pictures, 
first company have **code**: OX1
first grade have **abbreviation**: 11MED

so when I select first company and then first grade, the abbreviation field should have this value: OX11MED

and similarly if I select another company or grade, it should change accordingly.
we can do this in vue by binding and using :value bt I dont know how to do it in enso? 
kindly give me some heading points or any example that I can refer to?

here is a video demonstration of my requirement.
https://drive.google.com/file/d/1l42RmM5wj3LPa_fzwff6R_VLggdXPEX_/view

Thanks.

**Comment by subtain-haider** [comment]
Anyone help???

**Comment by aocneanu** [comment]
>how to do it in enso

What do you mean by that?

Enso is a boilerplate, not a programming language so you would do it exactly how you do it in Vue.

If you are using forms, this issue belongs to the forms repo
```
- [ ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
```
(**no -> laravel-enso/forms / enso-ui/forms**)

If that is the case you will have to set your field as custom in meta (form template).

You have examples of almost everyting in Enso so if:

```
- [ ] Did you check the documentation?
```
([**no -> link**](https://docs.laravel-enso.com/frontend/forms.html#slots))
or
([**no -> link**](https://docs.laravel-enso.com/backend/forms.html#custom))
or
```
- [ ] Did you perform a cursory search?
```
([**no -> link**](https://github.com/laravel-enso/forms/issues/34))

You would find all answers.

Meanwhile use [this](https://github.com/laravel-enso/companies/blob/master/src/App/Forms/Templates/company.json#L21) and [this](https://github.com/laravel-enso/companies/blob/master/src/App/Forms/Templates/company.json#L21) as an inspiration.

If you don't have the time to search and explore yourself you can get anytime a support package from us and that will grant you monthly hours of priority support on any Enso related topic, including training, best practices and so on.

Please keep in mind that we use the github issues mainly for bug reporting and feature requests.

**Comment by subtain-haider** [comment]
yes I would like a support package from you,
how can I get it? can we discuss about tht?

**Comment by aocneanu** [comment]
Email me.

**Comment by subtain-haider** [comment]
Sent

**Comment by aocneanu** [comment]
Responded
