### ISSUE TITLE
upgraded to 3.9.1 lost the ability to remember table search value and last page position

### ISSUE THREAD

**Issue by kitcChu** [laravel-enso/enso#299]
This is  a **bug | feature request**.

### Prerequisites
* [x ] Are you running the latest version?
* [x ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x ] Did you check the documentation?
* [ ] Did you perform a cursory search?

### Actual behavior
upgraded to 3.9.1 lost the ability to remember 
table search value 
last page position
how table was last sorted 
IS there a place we can turn it back on?

**Comment by aocneanu** [comment]
run yarn upgrade again.

**Comment by kitcChu** [comment]
Great it works again. Thank you

**Comment by aocneanu** [comment]
Make sure you run composer update as well, the be api has changed too.

**Comment by kitcChu** [comment]
ok will do, thanks again
