### ISSUE TITLE
broken by Browsersync

### ISSUE THREAD

**Issue by neomobil** [laravel-enso/Enso#30]
when I use mix.browsersync('blabla.test'), I get the following error 
`TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (enso.js:50)
    at <anonymous>`
and the login box is not loading

**Comment by aocneanu** [comment]
We use async loading for vue components with implicit code splitting, and for this be compiled in a correct manner I had to add in webpack.mix.js the following lines.

```
mix.webpackConfig({
    output: {
        publicPath: '/',
    },
});
```

To use hot module reload just comment those lines and then `npm run hmr`.

Don't forget to uncomment the lines when you want to compile the assets without hmr.

There are many issues open in Jeffrey's laravel-mix repo on this topic but I'm not aware of a concrete solution.

If you find something better please let me know.

Cheers.

**Comment by neomobil** [comment]
Thanks for the Answer!

Takó Kornél

www.neomobil.hu



2018-01-23 14:15 GMT+01:00 Adrian Ocneanu <notifications@github.com>:

**Comment by aocneanu** [comment]
Np, if it solves the problem you can close the ticket :)

**Comment by neomobil** [comment]
It solves the problem partially. Anyway, this an Issue of laravel-mix, thatswhy I close it. 
Thanks for your help.
