### ISSUE TITLE
Cannot get EnumServiceProvider to populate enums to frontend state

### ISSUE THREAD

**Issue by kitcChu** [laravel-enso/enso#301]
This is  a **bug | feature request**.

### Prerequisites
* [x ] Are you running the latest version?
* [ x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ x] Did you check the documentation?
* [ ] Did you perform a cursory search?

### Steps to Reproduce
<!--
1. First Step
<?php

namespace App\Providers;

use LaravelEnso\Enums\EnumServiceProvider as ServiceProvider;

use App\Enums\QuotationStatus;

class EnumServiceProvider extends ServiceProvider
{
    public $register = [

        'quotationStatus' => QuotationStatus::class,
    ];
} 
--------------------------------------------------------------------------
namespace App\Enums;

use LaravelEnso\Enums\App\Services\Enum;

class QuotationStatus extends Enum
{

    public const new = 1;
    public const pending = 2;
    public const booked = 3;
    public const lost = 4;
    public const canceled = 5;

    protected static function data(): array
    {
        return [
            static::new => 'New',
            static::pending => 'Pending',
            static::booked => 'Booked' ,
            static::lost => 'Lost',
            static::canceled => 'Canceled',
        ];
    }
}

**Comment by aocneanu** [comment]
What steps did you take?

**Comment by kitcChu** [comment]
I created 2 files. 

 namespace App\Enums;

use LaravelEnso\Enums\App\Services\Enum;

class QuotationStatus extends Enum
{


    public const new = 1;
    public const pending = 2;
    public const booked = 3;
    public const lost = 4;
    public const canceled = 5;


    protected static function data(): array
    {
        return [
            static::new => 'New',
            static::pending => 'Pending',
            static::booked => 'Booked' ,
            static::lost => 'Lost',
            static::canceled => 'Canceled',
        ];
    }
} 
----------------------------------------------
<?php

namespace App\Providers;


use LaravelEnso\Enums\EnumServiceProvider as ServiceProvider;

use App\Enums\QuotationStatus;


class EnumServiceProvider extends ServiceProvider
{
    public $register = [

        'quotationStatus' => QuotationStatus::class,
    ];
}

**Comment by aocneanu** [comment]
Name your constants "New, Pending, Booked" etc and you don't need the data() method. You need that method only if the constants are different from the labels you want to display in places of the app.

What is the other file?

What is 
>QuotationStatus::class, ]; }

**Comment by kitcChu** [comment]
<?php

namespace App\Providers;


use LaravelEnso\Enums\EnumServiceProvider as ServiceProvider;

use App\Enums\QuotationStatus;


class EnumServiceProvider extends ServiceProvider
{
    public $register = [

        'quotationStatus' => QuotationStatus::class,
    ];
}

**Comment by kitcChu** [comment]
namespace App\Providers;


use LaravelEnso\Enums\EnumServiceProvider as ServiceProvider;

use App\Enums\QuotationStatus;


class EnumServiceProvider extends ServiceProvider
{
    public $register = [

        'quotationStatus' => QuotationStatus::class,
    ];
}

**Comment by aocneanu** [comment]
Did you register the service provider?

**Comment by kitcChu** [comment]
that is probably what I need to know. HOw to do that ?

**Comment by aocneanu** [comment]
[read the docs](https://laravel.com/docs/7.x/providers#registering-providers)

**Comment by kitcChu** [comment]
very good. It works now

**Comment by kitcChu** [comment]
Thanks for your help
