### ISSUE TITLE
yarn - error

### ISSUE THREAD

**Issue by arankar** [laravel-enso/enso#303]
Output:
**ERROR** Failed to apply patch for package bulma-rtl

  This happened because the patch file patches\bulma-rtl+0.7.1.patch could not be parsed.

  If you just upgraded patch-package, you can try running:

    cd patches\bulma-rtl+0.7.1.patc
    patch -p1 -i h
    npx patch-package bulma-rtl
    cd ../..

  Otherwise, try manually creating the patch file again.

  If the problem persists, please submit a bug report:

    https://github.com/ds300/patch-package/issues/new?title=Patch+file+parse+error&body=%3CPlease+attach+the+patch+file+in+question%3E

error Command failed with exit code 1.
child_process.js:650
    throw err;
    ^

Error: Command failed: yarn run postinstall

**ERROR** Failed to apply patch for package bulma-rtl

  This happened because the patch file patches\bulma-rtl+0.7.1.patch could not be parsed.

  If you just upgraded patch-package, you can try running:

    cd patches\bulma-rtl+0.7.1.patc
    patch -p1 -i h
    npx patch-package bulma-rtl
    cd ../..

  Otherwise, try manually creating the patch file again.

  If the problem persists, please submit a bug report:

    https://github.com/ds300/patch-package/issues/new?title=Patch+file+parse+error&body=%3CPlease+attach+the+patch+file+in+question%3E

error Command failed with exit code 1.

    at checkExecSyncError (child_process.js:607:13)
    at execSync (child_process.js:647:13)
    at Object.<anonymous> (D:\paradox\Programming\OpenServer\domains\enso\CLIENT\node_modules\postinstall-postinstall\run.js:15:5)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)

**Comment by lucacalcaterra** [comment]
same issue here

**Comment by arankar** [comment]
> 
> 
> same issue here

?

**Comment by lucacalcaterra** [comment]
> > same issue here
> 
> ?

I've the same problem.. probably npm packages issues..

**Comment by lucacalcaterra** [comment]
> Output:
> **ERROR** Failed to apply patch for package bulma-rtl
> 
> This happened because the patch file patches\bulma-rtl+0.7.1.patch could not be parsed.
> 
> If you just upgraded patch-package, you can try running:
> 
> ```
> cd patches\bulma-rtl+0.7.1.patc
> patch -p1 -i h
> npx patch-package bulma-rtl
> cd ../..
> ```
> 
> Otherwise, try manually creating the patch file again.
> 
> If the problem persists, please submit a bug report:
> 
> ```
> https://github.com/ds300/patch-package/issues/new?title=Patch+file+parse+error&body=%3CPlease+attach+the+patch+file+in+question%3E
> ```
> 
> error Command failed with exit code 1.
> child_process.js:650
> throw err;
> ^
> 
> Error: Command failed: yarn run postinstall
> 
> **ERROR** Failed to apply patch for package bulma-rtl
> 
> This happened because the patch file patches\bulma-rtl+0.7.1.patch could not be parsed.
> 
> If you just upgraded patch-package, you can try running:
> 
> ```
> cd patches\bulma-rtl+0.7.1.patc
> patch -p1 -i h
> npx patch-package bulma-rtl
> cd ../..
> ```
> 
> Otherwise, try manually creating the patch file again.
> 
> If the problem persists, please submit a bug report:
> 
> ```
> https://github.com/ds300/patch-package/issues/new?title=Patch+file+parse+error&body=%3CPlease+attach+the+patch+file+in+question%3E
> ```
> 
> error Command failed with exit code 1.
> 
> ```
> at checkExecSyncError (child_process.js:607:13)
> at execSync (child_process.js:647:13)
> at Object.<anonymous> (D:\paradox\Programming\OpenServer\domains\enso\CLIENT\node_modules\postinstall-postinstall\run.js:15:5)
> at Module._compile (module.js:653:30)
> at Object.Module._extensions..js (module.js:664:10)
> at Module.load (module.js:566:32)
> at tryModuleLoad (module.js:506:12)
> ```

Are you on Windows ? In linux seems to be ok.

**Comment by arankar** [comment]
yes on windows

**Comment by curtisdelicata** [comment]
I had the same error ages ago on Windows. On Linux it works fine for me though.

**Comment by aocneanu** [comment]
Unfortunately in our team we have 0 experience with developing on Windows.

Will leave this open until somebody can help.

**Comment by subtain-haider** [comment]
I had the same problem in beginning  when I started working with laravel enso
I solved this by using 'rimraf'.
In `client/package.on` file replace these lines
"build": "rimraf ../public/{js,themes,themes-rtl,images} && vue-cli-service build --no-clean --modern",
"dev": "rimraf ../public/{js,themes,themes-rtl,images} && vue-cli-service build --no-clean --mode development",
and am using node as yarn is not recommended for windows

**Comment by lucacalcaterra** [comment]
> I had the same problem in beginning when I started working with laravel enso
> I solved this by using 'rimraf'.
> In `client/package.json` file replace these lines
> `"build": "rimraf ../public/{js,themes,themes-rtl,images} && vue-cli-service build --no-clean --modern",`
> `"dev": "rimraf ../public/{js,themes,themes-rtl,images} && vue-cli-service build --no-clean --mode development",`
> and am using node as yarn is not recommended for windows

thanks !

**Comment by arankar** [comment]
OS Windows
fixed the error:
**patches \ bulma-rtl + 0.7.1.patch
patches \ bulma-extensions + 2.2.2.patch**
CRLF-> LF

**eslintrc.js**
add
rules: {
    "linebreak-style": 0,
}

**Comment by aocneanu** [comment]
@arankar can we close this?

**Comment by arankar** [comment]
yes

**Comment by lucacalcaterra** [comment]
fixed. Thanks !
