### ISSUE TITLE
localisation error

### ISSUE THREAD

**Issue by ybaddi** [laravel-enso/enso#305]
This is  a bug.

### Prerequisites
* [y] Are you running the latest version?
* [y] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [y] Did you check the documentation?
* [y] Did you perform a cursory search?

### Description

The localisation is not working, I also checked with the demo hosted application, the language is still always the default (en), the RTL mode is changed but not the translation.

**Comment by aocneanu** [comment]
You are right. Apparently at some point in time somebody did a PR to the localisation repo and broke stuff.

Will look into it.

**Comment by aocneanu** [comment]
@ybaddi with the latest version you should be ok.

Please close this if everything works now.
