### ISSUE TITLE
hideTab and tabVisibility function has no effect

### ISSUE THREAD

**Issue by kitcChu** [laravel-enso/enso#306]
This is  a **bug | feature request**.

### Prerequisites
* [x ] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x ] Did you check the documentation?
* [ ] Did you perform a cursory search?

### Description
hideTab and tabVisibility function has no effect, How it works

### Steps to Reproduce

class SomeForm
public function create()
{
  return $this->form
   ->hideTab('SomeTab')
   ->tabVisibility('SomeTab',true)
   ->create();
}
----------------
create.vue
....
methods:{
   showSomeTab: function(event){
       this.$ref.form.tab('SomeTab').tabVisibility = true;
}

### Actual behavior
hideTab and tabVisibility function has no effect

**Comment by aocneanu** [comment]
@kitcChu this belongs to the forms repo. Please reopen there.
