### ISSUE TITLE
Possibility to change logo

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/Enso#31]
At the moment the logo is overwritten everytime when I push the assets.
Would be nice if you can provide a possibility to define another logo.

**Comment by aocneanu** [comment]
Good point

**Comment by mauthi** [comment]
Additional feature request in combination with this:
- Add application name to title 
document.title = to.meta.title + " - " + XX_APPLICATION_TITLE_XX;

**Comment by aocneanu** [comment]
About the logo, I was thinking about a new option in enso config, but then I started wondering,
why don't you overwrite the current logo?

For the the second request it's a bit tricky. I have a pretty wide monitor, but when I have 20+ tabs open in my browser the "Permission Groups" label does not fit entirely.

But this is why we have favicon, to give a visual identity to the app. The favicon can be also overwritten.

I suppose that this is what you are doing with the favicon, right?

**Comment by mauthi** [comment]
Because if I overwrite it it gets overwrited by update (I think because of publishing it from your package). Second point: would be nice if we can use png as well, don't have a svg of our logo?

According to title: Thats right, but for other points like bookmarking, sending or real big screens it is fine to have the app name in title (quick research: bitbucket, asana, harvest - three tools I use daily - have the name at end of title)

**Comment by aocneanu** [comment]
Ah, right, they publish from the resources folder. I will remove both the logo and the favicon from resources at the next commit / version / very soon.

**Comment by mauthi** [comment]
Tested this now - here is my feedback:

1) Logo
Works as expected!

2) Document Title General
- If you open login page (new incognito browser) title is not working
![screenshot 2018-01-31 10 06 02](https://user-images.githubusercontent.com/7204559/35614215-98c544c2-066e-11e8-964a-e58a43caa4e9.png)
- After login its the same
![screenshot 2018-01-31 10 06 21](https://user-images.githubusercontent.com/7204559/35614224-9ecd0512-066e-11e8-8eff-ae5567f02de2.png)
- Title starts working after you click on first menu item

3) Document Title Pre/Postfix
- I tried to formulate with my description (document.title = to.meta.title + " - " + XX_APPLICATION_TITLE_XX;) to add the application title as POSTfix, not PREfix (then the width of the tabs is not so important because application title is at the end) - maybe we can add a second configuration value if we want the extended title as pre or postfix OR just add it as postfix

**Comment by mauthi** [comment]
BTW to the 3rd screenshot above: The DOT in the title of right tab (Stapler & ...) means that there is a new notification in this app (maybe an idea for a future improvement)

**Comment by aocneanu** [comment]
Let's break this into separate tickets, with clear descriptions, labels etc. Please help me with this when you have the time. We don't want to track bugs or good ideas in closed tickets that are refering to something else.

1. Feature, Done, no need to open anything.
2. BUG Will be fixed when I will refactor the auth flow.
3. BUG Once we login, we need to click a link first for the title display
4. Feature, add post / pre ...
5. Feature, show bullet on new notifications, good ideea.

Thanks.

**Comment by mauthi** [comment]
Done - created the following issues:
- #39 
- #38 
- #40
