### ISSUE TITLE
Changes to support building on Windows that I have been working on

### ISSUE THREAD

**Issue by curtisdelicata** [laravel-enso/enso#312]
This is  a **bug and feature request**.

### Prerequisites
* [X ] Are you running the latest version?
* [X ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [X ] Did you check the documentation?
* [X ] Did you perform a cursory search?

### Description
composer can be fixed using:

       "platform": {
            "ext-pcntl": "7.4",
            "ext-posix": "7.4"
        }

under config part of the file which was working on some tests but when it didn't running composer install --ignore-platform-reqs always worked.

bulma-rtl.patch can be fixed by deleting the trailing line at the end and saving again. I couldn't commit so renamed after then renamed back. Tested on my Ubuntu server and the patch still applies. This fixes yarn install.

yarn build can be fixed by running different commands based on operating system using npx run-script-os. I developed this set of commands:
  "build": "npx-run-script-os",
  "build:default": "rm -rf ..\\/public/{js,themes,themes-rtl,images} && vue-cli-service build --no-clean --modern",
        "build:windows": "cd ..\\public && if exist js rd \/s \/q js && if exist themes rd \/s \/q themes && if exist themes-rtl rd \/s \/q themes-rtl && if exist images rd \/s \/q images && cd client & node_modules\\.bin\\eslint * --fix & node_modules\\.bin\\vue-cli-service build --no-clean --modern --skip-plugins thread-loader",
        "dev": "npx-run-script-os",
        "dev:default": "rm -rf ../public/{js,themes,themes-rtl,images} && vue-cli-service build --no-clean --mode development",
        "dev:windows": "cd ..\\public && if exist js rd \/s \/q js && if exist themes rd \/s \/q themes && if exist themes-rtl rd \/s \/q themes-rtl && if exist images rd \/s \/q images && cd client & node_modules\\.bin\\eslint * --fix & node_modules\\.bin\\vue-cli-service build --no-clean --mode development --skip-plugins thread-loader",
 

Now the install steps should work on Windows hosts as soon as I manage to debug why it it is not continuing along the commands running in Windows. Anyone know why it it isn't running the next command in the list?

### Steps to Reproduce
composer install fails because of pcntl or posix
yarn install fails because of line ending on the bulma-rtl patch but other patches were fine
yarn build fails as it relies on Linux style commands such as rm

### Expected behavior
I expected it to fail as not been designed for Windows.

### Actual behavior
It did not work.

**Comment by curtisdelicata** [comment]
I got the build script for yarn build to work using this on Windows:

> "scripts": {
        "serve": "vue-cli-service serve",
        "build": "npx run-script-os",
        "build:default": "rm -rf ..\\/public/{js,themes,themes-rtl,images} && vue-cli-service build --no-clean --modern",
        "build:windows": "cd ..\/public && rd \/s \/q js & rd \/s \/q themes & rd \/s \/q themes-rtl & rd \/s \/q images & cd ..\/client && node_modules\\.bin\\eslint * --fix & node_modules\\.bin\\vue-cli-service build --no-clean --modern --skip-plugins thread-loader",
        "dev": "npx-run-script-os",
        "dev:default": "rm -rf ../public/{js,themes,themes-rtl,images} && vue-cli-service build --no-clean --mode development",
        "dev:windows": "cd ..\/public && rd \/s \/q js & rd \/s \/q themes & rd \/s \/q themes-rtl & rd \/s \/q images & cd ..\/client && node_modules\\.bin\\eslint * --fix & node_modules\\.bin\\vue-cli-service build --no-clean --mode development --skip-plugins thread-loader",
        "lint": "vue-cli-service lint",
        "postinstall": "opencollective-postinstall && patch-package",
        "prod": "npm run build"
    },

**Comment by curtisdelicata** [comment]
Full working changes can be seen at https://github.com/modularsoftware/genealogy/blob/master/client/package.json

**Comment by raftx24** [comment]
@curtisdelicata  has it been solved?

**Comment by curtisdelicata** [comment]
It could be closed if you don't want it included but it might be useful for you so others can be building on Windows.
