### ISSUE TITLE
Docker needs to be upgraded to use php7.4-apache rather than php7.3-apache

### ISSUE THREAD

**Issue by curtisdelicata** [laravel-enso/enso#313]
This is  a **bug | feature request**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description

Docker needs to be upgraded to use php7.4-apache rather than php7.3-apache

### Steps to Reproduce

Composer install inside Docker instance confirms PHP 7.3 is installed and I know for browsing changes to files that PHP 7.4 is required.

**Comment by curtisdelicata** [comment]
I successfully got it working by first changing php7.3-apache to php7.4-apache.

Then removing the -dir part of jpeg and freetype for gd. Then I add to change xdebug to 2.9.5 for it to support PHP 7.4. I also changed Node to version 14 instead of 8 but don't know if you wanted that.

**Comment by curtisdelicata** [comment]
I also tested changing docker-compose to use mysql rather than mysql5.7 and everything works as expected so far.

**Comment by curtisdelicata** [comment]
@raftx24 I explained what I changed but it can be seen here: https://github.com/modularsoftware/genealogy/blob/master/docker/Dockerfile

**Comment by raftx24** [comment]
@curtisdelicata, I created a PR for this, please look at this

**Comment by curtisdelicata** [comment]
Looks better than what I did actually. I forgot about redis also. Thanks for your help.
