### ISSUE TITLE
Unable to build.

### ISSUE THREAD

**Issue by shah-aadil** [laravel-enso/enso#314]
error C:\xampp\htdocs\enso\client\node_modules\postinstall-postinstall: Command failed.
Exit code: 1
Command: node ./run.js
Arguments:
Directory: C:\xampp\htdocs\enso\client\node_modules\postinstall-postinstall
Output:
**ERROR** Failed to apply patch for package bulma-rtl

  This happened because the patch file patches\bulma-rtl+0.7.1.patch could not be parsed.

  If you just upgraded patch-package, you can try running:

    cd patches\bulma-rtl+0.7.1.patc
    patch -p1 -i h
    npx patch-package bulma-rtl
    cd ../..

  Otherwise, try manually creating the patch file again.

  If the problem persists, please submit a bug report:

    https://github.com/ds300/patch-package/issues/new?title=Patch+file+parse+error&body=%3CPlease+attach+the
+patch+file+in+question%3E

error Command failed with exit code 1.
child_process.js:669
    throw err;
    ^

Error: Command failed: yarn run postinstall

**ERROR** Failed to apply patch for package bulma-rtl

  This happened because the patch file patches\bulma-rtl+0.7.1.patch could not be parsed.

  If you just upgraded patch-package, you can try running:

    cd patches\bulma-rtl+0.7.1.patc
    patch -p1 -i h
    npx patch-package bulma-rtl
    cd ../..

  Otherwise, try manually creating the patch file again.

  If the problem persists, please submit a bug report:

    https://github.com/ds300/patch-package/issues/new?title=Patch+file+parse+error&body=%3CPlease+attach+the
+patch+file+in+question%3E

error Command failed with exit code 1.

    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at Object.<anonymous> (C:\xampp\htdocs\enso\client\node_modules\postinstall-postinstall\run.js:15:5)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer 79 61 72 6e 20 72 75 6e 20 76 31 2e 32 32 2e 34 0a 24 20 6f 70 65 6e 63 6f 6c 6c 65 63 74 69 76
65 2d 70 6f 73 74 69 6e 73 74 61 6c 6c 20 26 26 20 70 ... 356 more bytes>,
    <Buffer 0a 2a 2a 45 52 52 4f 52 2a 2a 20 46 61 69 6c 65 64 20 74 6f 20 61 70 70 6c 79 20 70 61 74 63 68
20 66 6f 72 20 70 61 63 6b 61 67 65 20 62 75 6c 6d 61 ... 565 more bytes>
  ],
  pid: 16332,
  stdout: <Buffer 79 61 72 6e 20 72 75 6e 20 76 31 2e 32 32 2e 34 0a 24 20 6f 70 65 6e 63 6f 6c 6c 65 63 74
69 76 65 2d 70 6f 73 74 69 6e 73 74 61 6c 6c 20 26 26 20 70 ... 356 more bytes>,

I tried the commands shown in the error but was unable to fix. Could someone guide me how do I fix this.
Thank You

**Comment by curtisdelicata** [comment]
See my issue for building on Windows. The patch file can be fixed by opening it then deleting the empty line and saving.

**Comment by shah-aadil** [comment]
@curtisdelicata I did edit patches\bulma-rtl+0.7.1.patch file and removed the last empty line 
![image](https://user-images.githubusercontent.com/27730678/86003127-068c5e80-ba1a-11ea-97ef-656b94031aaa.png)
Enven tried to clear the cache using `yarn cache clean` but the issue remains the same.

**Comment by curtisdelicata** [comment]
@shah-aadil when I had this issue when I was making my Enso based project. I just had to save again in PHP Storm and it seemed to convert it. I don't know why this patch has issues, as when I created my own patch for branding with patch-package it works on Windows and Linux fine.
