### ISSUE TITLE
The demo page is not working

### ISSUE THREAD

**Issue by heyner29** [laravel-enso/enso#317]
This is  a **bug**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description

The demo was broken with the latest update. In the frontend it doesn't show any error but I think it has to do with the attribute [`device_name`](https://github.com/laravel-enso/core/blob/147333ae2dbd143630239e5ede0f26017e329502/src/Http/Controllers/Auth/LoginController.php#L82) that is not sent and it seems mandatory.

**Comment by raftx24** [comment]
Hi @heyner29.
it was solved.
thank you for reporting.

**Comment by heyner29** [comment]
Hello, could you tell me how you solved it?
I am updating a project and I have the same error, I followed the update steps and I am stuck in that error: '(
