### ISSUE TITLE
Guest middleware still requiring login

### ISSUE THREAD

**Issue by curtisdelicata** [laravel-enso/enso#318]
This is  a **bug **.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description

Using the below route, with a new controller directory and Index controller and copy and pasted modified Vue route and Vue page file with just content it makes me login before being able to view my about page. The only thing I've changed is adding AppFooter to every page, but that wouldn't break anything would it?
```
     Route::middleware(['guest'])->group(
         function() {

        Route::namespace('About')
            ->prefix('about')
            ->as('about.')
            ->group(function () {
                Route::get('about', 'Index')->name('index');
    });
});
```

**Comment by curtisdelicata** [comment]
Tested by removing my appfooter patch and same behaviour.

**Comment by aocneanu** [comment]
@curtisdelicata we're releasing today 4.0.1, please try again.

If the problem persists please create an enso fork where you can add the minimum files to reproduce your problem and we'll help you solve it asap.

**Comment by curtisdelicata** [comment]
Thank you. I will update you once done @aocneanu

**Comment by curtisdelicata** [comment]
https://github.com/modularsoftware/enso is the test repository. I'm just committing the basic files now.

**Comment by curtisdelicata** [comment]
I spotted this in one of the core routes js meta...

        guestGuard: true,

I am building now to see if it fixes it.

**Comment by curtisdelicata** [comment]
That fixed it. Sorry for the bother.
