### ISSUE TITLE
Errors after fontawsome icon update

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/Enso#32]
I did the icon update as described but as you can see in screenshots not all icons are working.
Some are for my new menu items this is ok, I have to change them manually but some are from the default items like tachometer in dashboard.

![screenshot 2018-01-24 18 47 20](https://user-images.githubusercontent.com/7204559/35348083-43455460-0137-11e8-86b6-038864912194.png)
![screenshot 2018-01-24 18 47 15](https://user-images.githubusercontent.com/7204559/35348092-47ab5a68-0137-11e8-908d-bc6baece7630.png)

Did I forgot something?
Additionally the spaces between the cards are also missing. This can be a problem in combination with the missing icons?

**Comment by aocneanu** [comment]
Are you sure that everything is published?

**Comment by mauthi** [comment]
I hope so, which publish commands to I have to use for the icon update?
I used:

php artisan vendor:publish --tag='enso-assets' --force
php artisan vendor:publish --tag=enso-config --force
php artisan vendor:publish --tag=enso-update --force

**Comment by aocneanu** [comment]
> php artisan vendor:publish --tag='enso-assets' --force
for the js / scss assets. This would normally be published automatically if you have a recent composer.json

> php artisan vendor:publish --tag=enso-config --force
for the vue dt and vue forms config, with the new classes for fa5

php artisan vendor:publish --tag=enso-update --force
this one is deprecated, and usable only on the admilte branch. Did you find this in the publish list somewhere?

(you can run `php artisan vendor:publish --force` and press enter, and you cand select the options from the contextual menu)

Are you sure that `package.json` and `webpack.min.js` are synced too? and did you run `npm install` after merging?

Everything compiles ok?

BTW, online is the latest version and everything seems to be ok.

**Comment by mauthi** [comment]
> php artisan vendor:publish --tag=enso-update --force
> this one is deprecated, and usable only on the admilte branch. Did you find this in the publish list somewhere?
Yes in documentation.
![screenshot 2018-01-24 19 20 22](https://user-images.githubusercontent.com/7204559/35349586-a4b1994e-013b-11e8-8ada-fc3ea67a75cd.png)

**Comment by aocneanu** [comment]
Ok, that needs to be removed.

**Comment by mauthi** [comment]
To the main problem:
I did everything you described but I use my own theme
The following line was commented in webpack.mix.js:
`// .sass('resources/assets/sass/themes/netwerker.scss', 'public/themes/netwerker/bulma.min.css');`
I removed the comment and compiled it once, now it works

BTW did you change the colour of selected menu item? I use the following code:
`$primary: #FF0066 !default;
$navbar-item-hover-color: $primary;
$navbar-item-active-color: $primary;`
But now its blue and not #FF0066

**Comment by mauthi** [comment]
BTW the dashboard icon is still not working.
Reason: In database its tachometer - it should be tachometer-alt (maybe you should add this to the fa command?)

**Comment by aocneanu** [comment]
The line that you are mentioning is not from Enso.

I didn't change the color, bulma upgraded:)

You're right with the dashboard icon. I missed that.

In conclusion, now everything works?

**Comment by mauthi** [comment]
Not really :(

1) I don't get the newest version of vuecomponents after update.
Reason: composer show -i shows me the following:
`laravel-enso/vuecomponents            2.1.5              Enso Vue Components`
Why or how is this 2.1.5? I reseted it manually to 2.1.2 and updated it again - now its 2.1.3 and everything works

2) Two additional necessary fixes in menu table:
- Icon for System should be: sliders-h
- Icon for Data Import should be: cloud-upload-alt

**Comment by aocneanu** [comment]
I'm working on a refactor for the fa5 use, will be ready soon.

have no idea about v2.1.5 for vuecomp but you can always check the existing versions on packagist:

https://packagist.org/packages/laravel-enso/vuecomponents

**Comment by mauthi** [comment]
yes I know that but somehow in my repo v2.1.5 was installed, don’t know how :)
But I solved it manually - was just a hint for the case you get a question from anybody else.

**Comment by aocneanu** [comment]
@mauthi please read the changelog on the current update :)

Can this be closed?

**Comment by mauthi** [comment]
Thx!
