### ISSUE TITLE
Gravatar support question - feature request

### ISSUE THREAD

**Issue by pongraczi** [laravel-enso/enso#324]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

### Description
Is that possible to support gravatar and get the avatar by default from gravatar?  

### Expected behavior
After setting up an email for a user/people, it would be useful to get the avatar from gravatar.  
The user should be able to upload his/her own new avatar as option and use that image instead of gravatar.

### Actual behavior
It seems only avatar uploaded by the user supported.

**Comment by aocneanu** [comment]
It is but someone will have to make a pr for it.
