### ISSUE TITLE
adminlte branch

### ISSUE THREAD

**Issue by shapito27** [laravel-enso/enso#325]
Here https://github.com/laravel-enso/enso/blob/master/README.md I see 
> For the v1.x / adminlte version, take a look at the adminlte branch.

but adminlte link refer to 404 page.
Doesn't it exist anymore?

**Comment by aocneanu** [comment]
Nobody in our team has used the adminlte branch since a few years ago so I really don't know.

It's not maintained anymore, that's for sure.

**Comment by shapito27** [comment]
then it's better to update README.md
