### ISSUE TITLE
Laravel Enso CLI aborted issue.

### ISSUE THREAD

**Issue by biholaindrasinh** [laravel-enso/enso#327]
This is a **bug request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Steps to reproduce
1. php artisan enso:cli

### Expected behavior
wait for input from the user

### Actual behavior
Aborted.

**Comment by raftx24** [comment]
Hi @biholaindrasinh 
could you explain more about `reproduce`, because I cloned the repository and I ran `php artisan enso:cli` and it worked!

**Comment by biholaindrasinh** [comment]
Actually it was PHP 5.4.0 issue. I have updated to PHP 5.4.1 and Issue resolved.
