### ISSUE TITLE
Hey I am running a latest version of laravel-enso where it add laravel santrum for the authentication.. when i try to run /api/core/home from chrome it redirect me to /api/login but it works with the axios in vue components ... can you please help me?

### ISSUE THREAD

**Issue by Sweetlegs** [laravel-enso/enso#329]
This is  a **bug | feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

**Comment by raftx24** [comment]
Hi @Sweetlegs 
did you add `SANCTUM_STATEFUL_DOMAINS` to your .env?

**Comment by Sweetlegs** [comment]
Yes I did

**Comment by raftx24** [comment]
@Sweetlegs Aha I guess I understand the issue.
You cannot directly open `/api/core/home` right?
this is because sanctum will check the referer in the header request, If you want to use it as an API you should create a token and connect with the token.

**Comment by Sweetlegs** [comment]
I don't know how to do that ... can you help me how to create a token and connect with the token

**Comment by raftx24** [comment]
Yes, sure, first you should go to administration/users, and then select a user, then you can create a token there,
![image](https://user-images.githubusercontent.com/10864136/92130459-02196300-ee1a-11ea-9466-4cff9dd306ef.png)

**Comment by Sweetlegs** [comment]
Thank you so much I am able to generate the token how can i use that in api in chrome /api/core/home/?token=1|P9x44PHhzApy95IiV6lQoWZQdlWT8XZ1kA4DktBChQkyYkdFq5VbhiZoNjSACZfBjNJ3Ap6Oj6W67yiX
it still redirect me to /api/login page

**Comment by raftx24** [comment]
I assumed you want to use it as API, why do you need to open /api/core/home in chrome directly?

**Comment by Sweetlegs** [comment]
its easy to debugging

**Comment by raftx24** [comment]
Aha, anyway if you want to open in chrome you can change `vendor/laravel-enso/core/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php` in this way

```
class EnsureFrontendRequestsAreStateful extends Middleware
{
    public static function fromFrontend($request)
    {
        return true;
    }
}
```
It can help you for debugging :)
_it is only a very raw idea I'm sure you can find a much better idea like using web authentication instead of sanctum_

**Comment by Sweetlegs** [comment]
Perfect it work... Thank you so much
