### ISSUE TITLE
Icon in custom renderer

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/Enso#33]
I have a table where I use a renderer for a column. The renderer is defined as:

```
customRender(row, column) {
	            switch (column.name) {
		            case 'document_url':
		                return row[column.name] ? `<a href="${row[column.name]}" target="_blank" class="button is-small is-table-button is-primary"><span class="icon is-small"><fa icon="cloud-upload-alt"></fa></span>`
		                    : ``;
		            default:
		                toastr.warning(`render for column ${column.name} is not defined.`);
		                return this.__(row[column.name]);
	            }
	        }
```

At the moment the icon is not displayed correctly (and in dom its still `<fa icon="cloud-upload-alt"></fa>` instead of svg tag.

If I use the icon anywhere else on the same page it works (means it is imported correctly)

**Comment by aocneanu** [comment]
`fa` is a vue component.

You can't render vue components from javascript strings.

I will enhance the vuedatatable to be able to render fa5 icons when a custom meta tag is provided in the template, in the near future.

What you cand do until then:

- you can include fa5 js globally and use `<i class="fas fa-icon"></i>`. fa5 js will auto replace the icon with the svg.
- you can include fa4 and use `<i class="fa fa-icon"></i>`.

**Comment by mauthi** [comment]
ok, I think importing it globally is too much overload for one icon

but, if I would like to do that where is the best place to import it globally?

**Comment by aocneanu** [comment]
in `resources/assets/js/enso.js` at line 15 we import `./app.` (app.js). This file is not a part of the core, so will always be local to you project.

This is where you should add what you need extra.

**Comment by mauthi** [comment]
thx

**Comment by aocneanu** [comment]
@mauthi you can check laravel-enso/vuedatatable@dfbd4cc17d75a3584d4f0caa143172974cec276a

and if you like it don't forget to star the vdt package :P

**Comment by mauthi** [comment]
Star: Done - don’t know how I could forget this!

Icon: It’s fine if I just like to display an icon in cell, but in my use-case I need a button with an icon which links to an url (I did this with a custom renderer but after looking on code its either possible to set column as icon or to set column with custom render function?)
I know that I can do this with an row action button but in my case I would like to have the download icon next to the document number.

**Comment by aocneanu** [comment]
I suppose that I could add another attribute in meta, something like `pressable` that would emit an event `pressed` togheter with the column name and the whole row. And maybe underline this with dotted line, and set the pointer cursor on it...

**Comment by mauthi** [comment]
Sounds good - but to make it useable for more use cases it would be fine to use icons in custom renderer as well, but I don’t know a solution for this since it is a component now.

**Comment by aocneanu** [comment]
`linkable` and `icon` would work together :)

**Comment by mauthi** [comment]
yes but not „My super interesting text <icon> end of my text“ - but I don’t know if we need this :)

**Comment by aocneanu** [comment]
There will always be some idea not covered (or not coverable in an elegant manner) ;)

**Comment by aocneanu** [comment]
the new meta attribute is `clickable`, and the event is `clicked`. It passes both `column` & `row`.

**Comment by mauthi** [comment]
looks good!

Improvement:
- can we remove icon if row value of this column is ‚'

If ok, I can add this change?

**Comment by aocneanu** [comment]
I suppose you are refering at a falsy `row[column.name]`. If so yes, go ahead.

P.S. This is enso's repo, not vdt ;)

**Comment by mauthi** [comment]
Not needed, no error appears if value for :icon="row[column.name]“ is empty

**Comment by mauthi** [comment]
sorry, is it possible to move the issue to vdt?
