### ISSUE TITLE
Laravel 8 and PHP 8 question

### ISSUE THREAD

**Issue by curtisdelicata** [laravel-enso/enso#333]
This is  a **question**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description

When Laravel 8 is released will Enso be upgraded? I have the same question for PHP 8 too.

**Comment by aocneanu** [comment]
Not immediately but yes (few days)
