### ISSUE TITLE
The new installation is not working

### ISSUE THREAD

**Issue by heyner29** [laravel-enso/enso#335]
This is  a **bug**.

### Prerequisites
* [X] Are you running the latest version?
* [X] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [X] Did you check the documentation?
* [X] Did you perform a cursory search?

### Description
I just did a fresh installation of enso locally and it doesn't allow me to login. In the front it does not present anything but in developer tools it gives the following error.

![image](https://user-images.githubusercontent.com/12703614/94843404-46c8f780-03e2-11eb-92ef-4497e9f8a678.png)

### Steps to Reproduce
To reproduce the error, just do the readme installation steps, and create a new installation locally.

**Comment by raftx24** [comment]
Hi @heyner29 
You need to set your domain in `.env` for `SANCTUM_STATEFUL_DOMAINS`.
for example, if your domain is enso.test you should have this in your `.env`.  `
SANCTUM_STATEFUL_DOMAINS=localhost,127.0.0.1,127.0.0.1:8000,localhost:8080,::1,enso.test`

**Comment by Guirande** [comment]
I did the installation according to the documentation steps, but I get an error "index not found - Are you sure that the preview exists and is a .blade.php file?"

**Comment by raftx24** [comment]
@Guirande I guess you didn't open the web client URL.
please do it again and this time open localhost:8080 instead

**Comment by Guirande** [comment]
@heyner29  

It had the same error, it seems that the variable device_name is null, in the file vendor **/ laravel-enso / core / src / Http / Controllers / Auth / LoginController.php** in the **validateLogin** method

![enso error](https://user-images.githubusercontent.com/31559270/96328000-d60b1780-103e-11eb-9f89-7f68928b3b24.PNG)

For my solution, I removed the required field, according to the images below

![enso error 2](https://user-images.githubusercontent.com/31559270/96328057-60537b80-103f-11eb-8981-5dd0c879d28e.PNG)


![enso error 3](https://user-images.githubusercontent.com/31559270/96328062-73fee200-103f-11eb-8255-9bd1a65d2e85.PNG)

**This solution is temporary, for application security criteria I would like developers to pay more attention to this problem**

**Comment by aocneanu** [comment]
@heyner29 can this be closed?
