### ISSUE TITLE
Multiple select-filter missing values due to failed collection merging

### ISSUE THREAD

**Issue by adithewonderboy** [laravel-enso/enso#340]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
When loading customized options for a multiple select-filter, some values are missing. This behavior was seen when I used a custom query inside options and  the select-filter was loaded for the first time, so no items were selected

### Steps to Reproduce

1. Define a select-filter component which allow for multiple selections:
![image](https://user-images.githubusercontent.com/58045802/96375461-cb0cd000-1181-11eb-82fa-d68c25e05b56.png)

2. Build a custom query inside options (I needed some extra joins and checks in there..):
![image](https://user-images.githubusercontent.com/58045802/96375489-f1327000-1181-11eb-882c-aa2ab4d2c204.png)
 
3. Initially load the filter without making any selections:
![image](https://user-images.githubusercontent.com/58045802/96375553-571ef780-1182-11eb-9cd6-eb9a45c87b94.png)

4.Check to see if the values loaded inside the select-filter are correct. In my case some of them were missing

### Expected behavior
The values loaded by select-filter should match with the query provided inside options:
![image](https://user-images.githubusercontent.com/58045802/96375666-0065ed80-1183-11eb-8d6c-3b3479038475.png)

### Actual behavior
Instead, I got a truncated response:
![image](https://user-images.githubusercontent.com/58045802/96375642-e62c0f80-1182-11eb-82e8-9f2536a00e58.png)

### Extra information
After some debugging I saw that this was caused by merging the empty collection contained inside `$this->selected` from Services\Options get() method:
![image](https://user-images.githubusercontent.com/58045802/96375746-7bc79f00-1183-11eb-8918-0b4327ee0b7c.png)

When first-load the select-filter, nothing being selected, $this->selected is of course empty:
![image](https://user-images.githubusercontent.com/58045802/96375953-df060100-1184-11eb-8f42-df1f6c0f57b9.png)
![image](https://user-images.githubusercontent.com/58045802/96375961-e927ff80-1184-11eb-86e7-b37976d71f96.png)

Apparently merging an empty collection ($this->selected) with a non-empty collection (the one return by the `this->query->whereNotIn($this->trackBy, $this->value)->get()` gives unexpected results.

Some references I found about this issue:
[https://github.com/laravel/framework/issues/22626](url)
[https://github.com/laravel/framework/issues/19784](url)

### Proposed solution
Calling `toBase()` before `merge` should fix the issue, and all the items are returned:

Initial code:
![image](https://user-images.githubusercontent.com/58045802/96376228-58eaba00-1186-11eb-8e7b-4cab34fdd9b7.png)
![image](https://user-images.githubusercontent.com/58045802/96376233-656f1280-1186-11eb-858b-b14c365deae6.png)

With fix added:
![image](https://user-images.githubusercontent.com/58045802/96376259-7881e280-1186-11eb-8e4b-3f416270c5d2.png)
![image](https://user-images.githubusercontent.com/58045802/96376267-859ed180-1186-11eb-9493-691dd04f2d85.png)

Please review this fix and I hope you will include it in the next release,
Thanks!

**Comment by aocneanu** [comment]
Thanks for the well documented issue.

Btw, it should belongs to the [select repo](https://github.com/laravel-enso/select).

Fixing it now.

**Comment by adithewonderboy** [comment]
Thank you too for the fix!
