### ISSUE TITLE
Errors after Laravel 8 Upgrade - Slow build and **ERROR** Failed to apply patch for package bulma-rtl

### ISSUE THREAD

**Issue by kinger251285** [laravel-enso/enso#341]
This is  a bug/error.

### Prerequisites
* [Y] Are you running the latest version?
* [Y] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [Y] Did you check the documentation?
* [Y] Did you perform a cursory search?

### Description
All since upgrading to Laravel 8. Yarn build has gone from 100 seconds to over 30 minutes on an existing build. 

A fresh install encounters this error and i cannot fix it - **ERROR** Failed to apply patch for package bulma-rtl.

We sometimes also hit an innefective mark-compacts near heap limit allocation failed - although opening up 8gb

It seems like there may be a data leak somewhere or an issue within the js.maps, thats just a feeling. 

Ive tried every googling and tried all suggestions and nothing fixes this.

Ive tried a local homestead, a wamp server and a live LAMP Ubuntu stack and all produce the same results. 

Please let me know if you would like to see any code or files, not sure entirely what is causing this so not sure what code will be needed.

### Expected behavior
Build successfully

### Actual behavior
Build Fails

**Comment by kinger251285** [comment]
Have also just tried the rimraf option with an npm run build and i get the FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

This is on a local homestead dev on windows. This error occurs also with a yarn build on linux too though

**Comment by aocneanu** [comment]
@kinger251285 I was not able to reproduce this in any of our projects, nor a fresh clone.
