### ISSUE TITLE
May I know how do I show homepage instead of login page?

### ISSUE THREAD

**Issue by biholaindrasinh** [laravel-enso/enso#343]
### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
It's the most simple thing I find hard to customize:

How do I show the home page instead of the login page? How to replace the login component with my homepage component?

**Comment by aocneanu** [comment]
Pretty much the same way you would do in any other Laravel project.

- make sure the backend home route ('/') does not require auth.
- create your frontend home page

extra: create your home route in the frontend
