### ISSUE TITLE
Error using enso: cli

### ISSUE THREAD

**Issue by Guirande** [laravel-enso/enso#345]
This is  a **bug | feature request**.

### Prerequisites
- [x]  Are you running the latest version?

- [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
- [x] Did you check the documentation?
- [x] Did you perform a cursory search?

### Description

Using the instructions provided on the website **https://docs.laravel-enso.com/guide/development.html**, regarding the package and the CLI command.

After completing all steps I encounter the following error in the initialization of the created package:
**We're sorry but the frontend doesn't work properly without JavaScript enabled. Please enable it to continue.**

When calling initTable.

**To facilitate the use of the library, I suggest making some illustrative videos .**

**Comment by aocneanu** [comment]
Hi @Guirande ,

Apparently the route is not correctly defined. You can debug it like you would debug any laravel route.

I've just realeased 4.0.3 that updates the route creation, you can try again using it.

Thanks for the suggestion, if we would have time for creating videos believe we would. Maybe you can contribute to that once you get it running ;).

**Comment by raftx24** [comment]
fixed with this [PR](https://github.com/laravel-enso/cli/pull/48)
