### ISSUE TITLE
After update to 4.4.0 /api/broadcasting/auth is called twice, second call fails with a status 403

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/enso#351]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Tested on https://www.laravel-enso.com/ `/api/broadcasting/auth` is called twice - second call fails

### Steps to Reproduce

1. Login to https://www.laravel-enso.com/

### Expected behavior

No error

### Actual behavior

Error 403 on 2nd auth call
![image](https://user-images.githubusercontent.com/7204559/99146018-5a6bad00-2674-11eb-9eeb-bf67e0d91664.png)

**Comment by raftx24** [comment]
Hi @mauthi.
Yes, you are right, it was fixed, in the next deployment, we shouldn't see this issue.
thank you for reporting.
