### ISSUE TITLE
Slow performance with yarn serve and yarn build after Enso 4.4.0

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/enso#352]
This is  a **question**.

### Prerequisites
* [4.4.0] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
Not sure how you guys run your environments and what OS you are using, but we noticed a slower performance in yarn build and yarn serve - especially in yarn serve with the new Enso 4.4.0 on *Windows 10 Pro* machines.

This makes it much more slower to observe changes in page when any line change will trigger a ~100 seconds rebuild, mostly hanging on 40%:

![image](https://user-images.githubusercontent.com/16973022/99979038-598ef580-2daf-11eb-8add-d0fc208875d6.png)

I've noticed some Vue files had some local styles defined, and thought by removing them will help - but was no significant performance change (at least for one correction).

If you have some ideas we're glad to have a starting point of investigation

**Comment by robbykrlos** [comment]
Not saying this is from 4.4.0 code changes - it might be from yarn + windows and triggered not because of recent changes.

In the same time I'm trying: https://stackoverflow.com/questions/40566222/yarn-5x-slower-on-windows

_

> Disabling windows search indexing on your work folder and yarn cache folder as well as disabling windows defender completely or on a folder should give you significant performance boost. I've got 30-50% decrease on similar system with SSD drive, originally timings were as yours.
> 
> Disabling it on Yarn cache folder would also give you some speedup. Its location is shown by yarn cache dir command, %USERPROFILE%\Local Settings\Yarn\cache by default.
> 
> To disable search indexing on a folder, find it in Explorer, right click, then Properties - General - Advanced, uncheck the "Allow files in this folder to have contents indexed in addition to file properties" checkbox, then Apply the changes.
> 
> This performance issue already exists on yarn github (Oct'2016) and is still open to the moment: https://github.com/yarnpkg/yarn/issues/990

_

**Comment by robbykrlos** [comment]
Oh... this ain't looking good. Can be from AV:

https://github.com/yarnpkg/yarn/issues/990

![image](https://user-images.githubusercontent.com/16973022/99989258-13d82a00-2dbb-11eb-9ed3-e7c10f4c863c.png)

**Comment by aocneanu** [comment]
Hi @robbykrlos,

We're only using linux & mac so we don't have any helpful input for W... other than switch it:)

**Comment by robbykrlos** [comment]
Ok, good. Will close this one. Will return with updates in case we find a solution for windows - may be useful for somebody with the same issue.

**Comment by robbykrlos** [comment]
Some updates on this issue : after some days, I had to clean-up node_modules, because of some corrupted files, and some weird errors, and using:

**Clean-up yarn cache:**
`yarn cache clean`

Delete all node_modules inner folders. Use Fast delete node_modules 👍 
https://stackoverflow.com/questions/28175200/how-to-delete-node-modules-deep-nested-folder-in-windows 

Install RimRaf:
`npm install rimraf -g`
And in the project folder delete the node_modules folder with:
`rimraf node_modules`

Install again all node_modules:
```
yarn install
yarn build
yarn serve
```

Build and Serve are now working normally.
