### ISSUE TITLE
Bug Found - Enzo Project Broke When We Composer Update

### ISSUE THREAD

**Issue by JashanKhela** [laravel-enso/enso#357]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

When we deleted our composer.lock file and ran composer install today our whole app broke because of the upgrade to laravael-enso/io to 2.2.2. When we tried to run composer update and/or install we get the latest version of this package which causes the backend of our app to break with an error persisting to the WebsocketServiceProvider.php file. For now, we have saved our composer.lock file with version 2.0.2 of laravel-enso/io which doesn't cause the app to break. How can we update our app to work and compile with the new /io package?
<img width="1440" alt="Screen Shot 2020-12-14 at 1 35 32 PM" src="https://user-images.githubusercontent.com/25163420/102138673-90d24e80-3e11-11eb-99db-382d07003120.png">
<img width="1077" alt="Screen Shot 2020-12-14 at 1 37 10 PM" src="https://user-images.githubusercontent.com/25163420/102138680-9465d580-3e11-11eb-97ab-6cb8645064bf.png">

**Comment by aocneanu** [comment]
What's the error reported by the linter?
