### ISSUE TITLE
Environment setup/configuration/optimizations

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/enso#359]
This is  a **question**.

Hi,

Are you guys willing to share your https://www.laravel-enso.com/ environment configuration?

I mean here:
- OS distro/version
- Hardware : CPU, RAM, Storage
- web-server(s)
- php ( fpm?)
- cache
- any other opcache/accelarators/optimizations?

I'm doing some research on the best performance we can get our of an Enso based application, and it seems that your demo test is quite fast compared to our test env. We have a RH7. No caching httpd2.4, php-fpm.

We have this initial "slowness" where if you don't login for 24h, the first login is very slow, and unresponsive. and even more the second action you try (ex, changing the menu will wait for ~4-5 seconds without anything changing). 

After a while, things move faster, and actions are instant.

My feeling, after some performance profiling is that something on UI - loading js files. is slow. Because the API calls and DB results are usually fast. This is still WIP

Thank you,

**Comment by aocneanu** [comment]
We have never encountered problems with Enso's performance.

We're using (as min config): 
- 2 cores (virtual) on any 8th generation or up intel with virtualization
- 4gb ram
- 40gb ssd
- ubuntu 20 (use used 14, 16, 18 on prev versions)
- fpm / opcache activated

You should get with that config < 35 ms per request (w/o heavy db activity).

On the demo server we have 4 cores i7-8700 and 50 gb ssd.

Note that we provision & manage all of our servers with forge.laravel.com, one of the best decisions we ever made. And deploy with envoyer.

**Comment by aocneanu** [comment]
recommendation from @dorincarsin who is our sysadmin.

https://www.hetzner.com/cloud -> go for the one that is 5.68 monthly.

**Comment by robbykrlos** [comment]
Hi, Thank you so much for your inside info. That will definitely help!
Thanks @aocneanu, @dorincarsin

**Comment by robbykrlos** [comment]
For everyone else having performance problems with Laravel Enso - out of the box configuration - a huge boost will be using Redis caching, instead of "file" as it comes by default:
```ini
CACHE_DRIVER=file
```
To:
```ini
CACHE_DRIVER=redis
```
Of course this does not work by just changing the configuration, you'll need to install Redis and php_redis extension for your environment. 

For a low traffic and limited usage, Apache is still OK. nginx is fast but at this scale the performance improvements are very light.
