### ISSUE TITLE
Missing "beforeMigration" option?

### ISSUE THREAD

**Issue by adithewonderboy** [laravel-enso/enso#360]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
I just started to update to the latest version and following the update steps, I got an error when I execute
"php artisan enso:upgrade --beforeMigration"

![image](https://user-images.githubusercontent.com/58045802/102623128-b41b3780-414a-11eb-8de3-457992251399.png)

Am I doing something wrong here? Thanks!

**Comment by heyner29** [comment]
Yes, the option is `--before-migration`

**Comment by adithewonderboy** [comment]
Thanks,
Then please update the upgrade steps too:
![image](https://user-images.githubusercontent.com/58045802/102623759-ae722180-414b-11eb-861f-c7bcbb84c40b.png)
