### ISSUE TITLE
How to override default login page with custom login page

### ISSUE THREAD

**Issue by jlaboy22** [laravel-enso/enso#362]
I'm new to this, so hope this is the right forum for this.
How can one override laravel-enso login page with custom login page? 
Any info/resources/help would be greatly appreciated.

Thank you

**Comment by aocneanu** [comment]
Did you search about this before creating the issue?

**Comment by jlaboy22** [comment]
I looked thru Laravel-enso docs, but I’m fairly new to this and not sure if it’s the correct place. Do you have recommended URL link(s) to search on?

Thank you in advance

**Comment by aocneanu** [comment]
Hi Jose, I did not recognize you :)

If you just want to replace the login view you should start [here](https://github.com/enso-ui/auth/)

Use patch-package to replace or customize whatever you want.

**Comment by jlaboy22** [comment]
Happy New year.

Thank you for the link.
