### ISSUE TITLE
White screen 

### ISSUE THREAD

**Issue by jjmontalban** [laravel-enso/Enso#37]
Hello!

I have cloned this project and followed install steps but I only have a white screen. Debugbar dont throw any info.

How I can proceed to solve it?

My repository is here: https://github.com/jjmontalban/Enso

Any advice will be well received

Best regards!

**Comment by mauthi** [comment]
Do the PHP/Webserver Error logs display anything?

**Comment by jjmontalban** [comment]
I have installed the project in a XAMPP server. I can see this:

[php7:error] [pid 15996:tid 1636] [client ::1:59364] PHP Fatal error:  Class 'App\\Http\\Controllers\\Controller' not found in C:\\xampp\\htdocs\\enso\\app\\Http\\Controllers\\Auth\\LoginController.php on line 12, referer: http://localhost/enso/app/Http/Controllers/Auth/

?¿

**Comment by jjmontalban** [comment]
I see this post: 
https://laracasts.com/discuss/channels/general-discussion/class-apphttpcontrollerscontroller-not-found

And finally obtain this:

FatalErrorException (E_UNKNOWN)
Class 'App\Http\Controllers\Controller' not found

Its a small step, but its a step...

**Comment by gandesc** [comment]
Hi, 

I'm using Linux so haven't had this issue, but from the error log, it could be some sort of environment configuration issue, affecting autoloading.

What php version do you have?
What composer version?
Are there any issues when running `composer check-platform-reqs` ?
Does a brand new `laravel new` created project work ok?

**Comment by jjmontalban** [comment]
I have 7.2.0 PHP version

1.4.2 Composer version

With the command "composer check-platform-reqs" console throw: " Command "check-platform-reqs" is not defined."

I havent any problem with others projects

**Comment by aocneanu** [comment]
it seems like the namespace is not resolved. If you try `php artisan` you get the same rror?

**Comment by jjmontalban** [comment]
Hi

When I throw: php artisan I get the error:

PHP Fatal error:  Class 'LaravelEnso\TutorialManager\app\Http\Controllers\Controller' not found in C:\xampp\htdocs\enso\vendor\laravel-enso\tutorialmanager\src\app\Http\Controllers\RouteTutorialController.php on line 10

?¿

**Comment by aocneanu** [comment]
For sure it's something related to namespace resolving.

`LaravelEnso\TutorialManager\app\Http\Controllers\Controller` is in fact `App\Http\Controllers\Controller` as you can see in the file:

https://github.com/laravel-enso/TutorialManager/blob/master/src/app/Http/Controllers/RouteTutorialController.php

Also the the line should be 8, not 10. Please paste here line nr 10 from `RouteTutorialController.php`

**Comment by jjmontalban** [comment]
I got this error when I thrown:

namespace App\Http\Controllers\Auth;

I have restored RouteTutorialCOntroller.php with your link but I continue with the same error...


PHP Fatal error:  Class 'App\Http\Controllers\Controller' not found in C:\xampp\htdocs\enso\vendor\laravel-enso\tutorialmanager\src\app\Http\Controllers\RouteTutorialController.php on line 8

**Comment by aocneanu** [comment]
There you go :) If you git clone the repo and follow the installation steps, you should have `RouteTutorialController.php` (and everything else) as an exact mirror from the repos.

If you had line 8 at line 10, it means that the files are somehow changed. You fixed one file, but the project has tens of thousand.

I would suggest to do a clean reinstall of xampp and start over. I have no experience with XAMPP, but for sure you problem is not related to Enso.

**Comment by jjmontalban** [comment]
Sure!

I have chaged some files because I had a white screen after install.

I will reinstall everything and I tell you...

**Comment by aocneanu** [comment]
Regarding `1071 Specified key was too long; max key length is 767 bytes`, did you migrate fresh after fixing adding `Schema::defaultStringLength(191)` ?

**Comment by aocneanu** [comment]
Either way, I don't think it's supposed to work with `localhost/enso/public`. It should be something like `enso.dev`.

Did you added the project path to your `etc/hosts` file?

**Comment by jjmontalban** [comment]
Xampp doesnt work like Vagrant.

I run every project here witohut problems.

**Comment by aocneanu** [comment]
Sorry, I have 0 experience with XAMPP :)

Your XAMPP installation is not similar to this ?

https://www.5balloons.info/how-to-install-laravel-5-5-with-xampp/

They seem to use `.dev` also.

(first googled tutorial on L5.5)

**Comment by jjmontalban** [comment]
Last step its not neccesary to run a project in xampp. You can use http://localhost/nameProject

**Comment by aocneanu** [comment]
'We need to configure XAMPP Virtual Host to set the document root to correct directory of laravel project' => to me sounds like exactly your problem.

**Comment by aocneanu** [comment]
I understand. Unfortunately, I have no other idea. Enso runs in different environments w/o problems, but I don't think that anybody tested in your setup.

We'll leave this open, maybe someone has another idea.

Sorry.

**Comment by mauthi** [comment]
I run Enso with MAMP and everything works fine.

**Comment by y0net** [comment]
It works on xampp windows:

![image](https://user-images.githubusercontent.com/19207797/35739963-020b0f6a-083c-11e8-8146-5bc492b66590.png)

I just folowed the tutorial posted above, including last step with virtual hosts.

apache/conf/extra/httpd.vhosts:
```
<VirtualHost enso.test:80>
DocumentRoot "C:\xampp\htdocs\Enso\public"
ServerAdmin enso.test
<Directory "C:\xampp\htdocs\Enso">
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>
</VirtualHost>
```
windows/system32/drives/etc/hosts:
`127.0.0.1	enso.test`

**Comment by jjmontalban** [comment]
Run!

All of you were right and my problem was the configuration of the vhost.

I do not understand why in all my previous projects it was not necessary to do this ...

Problem solved.

Thank you all!

**Comment by aocneanu** [comment]
No problem, glad that you fixed it.
