### ISSUE TITLE
Illuminate\Broadcasting\BroadcastException: Failed to connect to Pusher (after click on Excel Export)

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/enso#371]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

For one table it's not possible to export to excel anymore.
Other tables are working fine.
If I switch broadcasting from pusher to logs it's also working for this table.
Connection to pusher also works (I get other messages in pusher)

Do you have any idea?
Below you can find screenshots from sentry. If you need more details from sentry please ask.

![image](https://user-images.githubusercontent.com/7204559/106353356-3cfcc580-62ea-11eb-9fb8-8fe33508d00a.png)

![image](https://user-images.githubusercontent.com/7204559/106353377-60c00b80-62ea-11eb-9bbb-a24d9276269d.png)

**Comment by raftx24** [comment]
Hi @mauthi, it seems there is a problem between the pusher and your application.
