### ISSUE TITLE
SSO auth option (SAML)

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/enso#377]
This is  a **feature request**.

We are starting implementing a new login option using simpleSAMLphp for SSO (Single Sign On).
We were wondering if you consider this in the future, or you have already support for such login option.

If you are interested, I can change my implementation so it goes in the same direction with your vision, so later we will PR for everyone.

Just an idea...

**Comment by mauthi** [comment]
+1

**Comment by robbykrlos** [comment]
OK, so if this is not needed here's how I did / will do (still in progress) this:
- used https://github.com/aacotroneo/laravel-saml2 (which is using https://github.com/onelogin/php-saml)
- followed the instructions, published vendor, configured settings
Env configuration used: 
```
SAML2_XXX_SP_ENTITYID=xxx-dev
SAML2_XXX_IDP_HOST=https://myidp.com
SAML2_XXX_IDP_ENTITYID=myidp.com
SAML2_XXX_IDP_SSO_URL=https://myidp.com/SingleSignOnService
SAML2_XXX_IDP_x509=myidp.com.crt
```
- created patch files for /@enso-ui/auth/src/bulma/pages/auth/components/AuthForm.vue in order to inject new "SSO Login" button that redirects to ``{routesPrefix}/{idpName}/login``

![image](https://user-images.githubusercontent.com/16973022/109682949-89585100-7b87-11eb-82c5-42a7f1b06fd0.png)

- implemented the Event listener for "Saml2LoginEvent" so that the returned IdP data is handled.

Until this point everything is working fine. Tested the response, got the user from DB.

Now the tricky part - integrating with Laravel Enso + Sanctum

**_WIP. To be continued..._**

------------------------------------------------------

**@enso-team - any hints on this matter? I have some questions:**

I tried following the same behavior as the LoginController does:
```
        if ($request->attributes->get('sanctum')) {
            Auth::guard('web')->login($this->user, $request->input('remember'));
        }

        Login::dispatch($this->user, $request->ip(), $request->header('User-Agent'));
```
**Q:** is the $request->ip and header user-agent important for authentication ? (I only saw this in LoginListener used for PasswordExpiresSoon - and I hope it is not used in some way for actual Authentication - Sanctum)

But I believe there are still parts to be handled on UI(and on UI I'm a bit lost, still a beginner in Vue...) - but I see that some things that were handled by UI on normal login might be needed to be still handled - ex:
@enso-ui/auth/src/store/auth.js
```
    login(state) {
        state.isAuth = true;
        localStorage.setItem('isAuth', true);
    },
```
**Q:** Do you see an elegant way to enter the same /login flow coming from the IdP with extra information? Atm I'm reluctant to use tricks to bypass stuff and also do not want to use workarounds - and this keeps me a bit busy at this step.

As always, any suggestion, is welcomed.

Thank you,
