### ISSUE TITLE
Installation problem the latest version

### ISSUE THREAD

**Issue by ShekhSaifuddin007** [laravel-enso/enso#379]
### Prerequisites
- [x] Are you running the latest version?
- [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
- [x] Did you check the documentation?
- [x] Did you perform a cursory search?

### Description
After clone the repo `git clone https://github.com/laravel-enso/enso.git --depth 1` then I run the `composer install`
and then I got this error you can see the image below, how to resolve this..?

### Actual behavior

![enso](https://user-images.githubusercontent.com/48278861/109206932-b47f2100-77d2-11eb-8f3c-5afdd72bda2c.PNG)

**Comment by vmcvlad** [comment]
Hi!

Are you sure you didn't run `composer update`? This shouldn't happen on `composer install` since
`artisan enso:upgrade:status` only runs on update.

Nonetheless, you could do `php artisan migrate` and then everything should be fine.

**Comment by ShekhSaifuddin007** [comment]
@vmcvlad No I didn't run `composer update` I just run `composer install`

**Comment by vmcvlad** [comment]
I can't reproduce this locally. Are you using windows? If so, we can't really offer much support since nobody uses windows in our team.

There have been windows related issues in the past, perhaps you might find something which helps you here:

https://github.com/laravel-enso/enso/issues/312

https://github.com/laravel-enso/enso/issues/352

**Comment by ShekhSaifuddin007** [comment]
@vmcvlad Opps! My bad 😢after deleting these scripts now I'm able to install packages

```json
"post-update-cmd": [
   "php artisan enso:localisation:merge",
   "php artisan telescope:publish",
   "php artisan horizon:publish",
   "php artisan enso:upgrade:status"
]
```

but now I'm facing a new issue see the pic below

![enso2](https://user-images.githubusercontent.com/48278861/109333644-e69f8a00-7889-11eb-8976-fa3e3218d8fd.PNG)

everything is compile by run `yarn serve` and I set my url properly
here is my env files

#### root env

```js
APP_URL=http://localhost:8000
```

#### client env

```js
API_URL=http://localhost:8080
```
