### ISSUE TITLE
vue.config.js chunks configuration

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/enso#381]
This is  a **question**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
I have a question regarding the js/chunks generated by enso's  default configuration:
JS files generated on our side are 138. We do not use (require) other yarn packages except fontawesome-pro.

I see that on your demo site (https://www.laravel-enso.com/) there are ~58 chunks loaded inside index file.

Is there different configuration used for this demo site, compared to laravel-enso/enso?

I tried playing around with configureWebpack optimization.splitChunks but had no result comparing to https://www.laravel-enso.com/. I also thought maybe my yarn is messy and started fresh with no yarn.lock file, and no node_modules, but still no improvement.

Any ideas/suggestions you have are recommended.

**Comment by robbykrlos** [comment]
An interesting read about Js speed optimization - https://www.diva-portal.org/smash/get/diva2:1318692/FULLTEXT01.pdf

**Comment by robbykrlos** [comment]
Difference:

**https://www.laravel-enso.com/**
![image](https://user-images.githubusercontent.com/16973022/112511646-4a3ea980-8d9b-11eb-9d7d-e572fa002c77.png)


*Local*
![image](https://user-images.githubusercontent.com/16973022/112511694-53c81180-8d9b-11eb-9ae1-36ca061ec684.png)

**Comment by robbykrlos** [comment]
I found the reasons why this happens. I'll document this here later.

**Comment by aocneanu** [comment]
@robbykrlos thanks!

**Comment by robbykrlos** [comment]
The reason why I had so many files was because on top of node_modules there were the internal (local, custom made) vue/js files that generated chunks. many of them, very small ones.

This on a test environment that had 2 CPU cores and 4GB RAM running Apache was a bit overwhelming and had a delay loading all this parallel requests.

My solution was to optimize chunks and merge some together.

Ex:
```js
configureWebpack: {
        devtool: inProduction ? 'hidden-source-map' : 'source-map',
        optimization: {
            nodeEnv: 'production',
            splitChunks: {
                cacheGroups: {
                    vendor: {
                        test: /[\\/]node_modules[\\/]/,
                        name(module) {
                            // get the name. E.g. node_modules/packageName/not/this/part.js
                            // or node_modules/packageName
                            const packageName = module.context.match(/[\\/]node_modules[\\/](.*?)([\\/]|$)/)[1];

                            // npm package names are URL-safe, but some servers don't like @ symbols
                            return `vendor.${packageName.replace('@', '')}`;
                        },
                    },  
                  ...
```

Which in my case generated slightly bigger chunks, which in the ends reduces the number or requests which loads faster.

I also did the same (still WIP) with local files, which can be easily merged into one small file.

My latest tests generated ~30 files, instead of 140.

**Comment by robbykrlos** [comment]
Bonus:

We also found that chunk files were not cached (browser cache). This was because on Apache mod_deflate.so is interfering with the ETag and generates a bug which makes the JS files flagged as "changed" and won't let the broswer see it as "the same"

Here is the Apache issue : https://bz.apache.org/bugzilla/show_bug.cgi?id=45023#c22

Here is the workaround after mod_deflate is used:
```
          #This fixes some Apache issues and was recommended in several posts.
          FileETag MTime Size
	  
          #THIS IS THE FIX 
          RequestHeader edit "If-None-Match" '^"((.*)-gzip)"$' '"$1", "$2"'
	  
          AddOutputFilterByType DEFLATE text/plain
	  AddOutputFilterByType DEFLATE text/html
	  AddOutputFilterByType DEFLATE text/xml
	  AddOutputFilterByType DEFLATE text/css
	  AddOutputFilterByType DEFLATE application/xml
	  AddOutputFilterByType DEFLATE application/xhtml+xml
	  AddOutputFilterByType DEFLATE application/rss+xml
	  AddOutputFilterByType DEFLATE application/javascript
	  AddOutputFilterByType DEFLATE application/x-javascript
	  
          BrowserMatch ^Mozilla/4 gzip-only-text/html
          BrowserMatch ^Mozilla/4\.[0678] no-gzip
          BrowserMatch \bMSIE\s(7|8)  !no-gzip !gzip-only-text/html

          Header set Vary Accept-Encoding
```

The difference can be seen if you refresh (soft-refresh, not hard) the login page. Initially all js files will be loaded with a 200 OK status.

Second refresh, it will load faster, because 
```
200 (from disk cache)
or
200 (from memory cache)
```
