### ISSUE TITLE
composer.json PHP >=8.0 ?

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/enso#397]
Shouldn't composer.json be updated with php >= 8.0?

https://github.com/laravel-enso/enso/blob/cf0cc156d43af4c0f0e5515f8b7d9f642408bd69/composer.json#L29

Code updated to 8 will not work with 7.4.

**Comment by robbykrlos** [comment]
I can do PR, but feel you had a reason of letting this one like this.

**Comment by aocneanu** [comment]
Is this issue still relevant?

**Comment by robbykrlos** [comment]
> Is this issue still relevant?

Isn't it? Php 7.4 in not compatible anymore with Laravel-enso. Am I missing something?

**Comment by aocneanu** [comment]
Ah lol, sorry

@GITmanuela, when you release v5 update [this](https://github.com/laravel-enso/enso/blob/master/composer.json#L29) as well
