### ISSUE TITLE
Show bullet in document title if there is a new notification

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/Enso#40]
According to the screenshot below: The DOT in the title of right tab (Stapler & ...) means that there is a new notification in this app (maybe an idea for a future improvement)

![screenshot 2018-01-31 10 12 14](https://user-images.githubusercontent.com/7204559/35632293-8b9d6c06-06a6-11e8-9ae6-e580861d20ba.png)

**Comment by aocneanu** [comment]
;)
