### ISSUE TITLE
Login component rendered after login on homepage

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/Enso#401]
This is  a **bug**.

### Description
We are using Enso without the Quotes screen (between Login and Home). Our landing page after login is an `/about` static page

Sometimes, not yet sure what triggers it, the login control is rendered on the `/about` page, after login.

(representation edited image of what happens, I don't have an actual image yet of the real issue)
![image](https://user-images.githubusercontent.com/16973022/138463991-63b77f72-39e6-44ab-9453-48ef0fd7f4ee.png)

There is no console error, and by switching the page and back to About everything is back to normal.

I wanted to ask you if this happens to you too? or if you have some ideas?

Thanks,

**Comment by aocneanu** [comment]
You can also do the PR for auth.

Thank you.

**Comment by robbykrlos** [comment]
Will do.

**Comment by robbykrlos** [comment]
Done
