### ISSUE TITLE
Git: Ignore .js/.js.map Files in public folder

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/Enso#41]
Is it really necessary that we have the js files in public folder under version control? It increases the diff of PR and I think we don't need them since we create them with npm? Or did I understand anything wrong?

**Comment by aocneanu** [comment]
If we don't have those file the the project won't work with git clone unless we do `npm install` and after compile.

I understand the struggle, but it's pretty easy to overcome this. Before pulling the new version of the project just do a `git checkout public/`

**Comment by aocneanu** [comment]
Can this be closed?

**Comment by mauthi** [comment]
for the moment yes, maybe we find a better solution in future

**Comment by aocneanu** [comment]
I'm afraid that this is a caveat that we must live with.

This is the source repo for laravel-enso.com. The demo would never work if the files would not be compiled.

Sorry.

**Comment by mauthi** [comment]
I unterstand you - is there a „best practice“ how other projects do this? I can’t believe that the combiled js files are in repo there? But I can’t be wrong...

**Comment by aocneanu** [comment]
Laravel Enso is packed as a boilerplate ready to go.

The optimal flow (what we use in our business projects, and the way we built it) would be:

1 Repo cloning, follow setup steps
2 Play
3 If you find Enso suited for building a project with it, delete the .git folder an run git init, and have a dedicated repo for the custom project.
4. Develop.
5. Whenever you need updates, just run composer update / npm update compile.

6. Need another new project ? Step 1.

We structured everything in packages, so there's almost never any need to update something in the root of the project, or in the cases when there is, it's trivial.

First thing that you will replace, for sure, is the dashboard. This mean that you already break the base. The dashboard structure is only an example, is there for you to modify it.

If you look with attention, basically what we update in the laravel-enso/enso repo on every version is composer.json, package.json, republish resources on every update (this would happen to you private repo too after composer update), compile / change the public folder and so on.

Only recently we added the new examples structure, but soon we will have a command like `php artisan enso:clear-examples` to leave everything clean for any new project.

Hope that helps.

**Comment by mauthi** [comment]
ok, thanks for the explanation - everything is clear.
My point war that the combiled js files have a lot of changes after each js change therefore you get a lot of lines in PR.
But thats a minor problem.
