### ISSUE TITLE
Component emitted event "edit" but it is neither declared in the emits option nor as an "onEdit" prop.

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/enso#414]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

After click on edit button e.g. in userGroups table I get the following warning after update to Vue 3:
<img width="504" alt="image" src="https://user-images.githubusercontent.com/7204559/155846708-83569068-eedd-46f4-bac0-9f520a59c424.png">

I tried to add `emits: ['edit'],` to `@enso-ui/user-groups/src/bulma/pages/userGroups/Index.vue` but it did not remove the warning.

### Steps to Reproduce

1. Log in
2. Open developer console
3. Go to Administration -> User Groups
4. Click on edit on one row

### Expected behavior

No warning

### Actual behavior

Warning

**Comment by aocneanu** [comment]
The warning is caused by vue3, which recommends documenting all events in the component that emits them.

Unfortunately, dynamic event names is not supported yet, but don't worry, you won't have any problems with it.

Meanwhile you can follow https://github.com/vuejs/rfcs/issues/204

**Comment by mauthi** [comment]
Thx - in that case I will close this.
