### ISSUE TITLE
"export 'Url' was not found in './Url.vue' || Uncaught TypeError: route is undefined

### ISSUE THREAD

**Issue by robbykrlos** [laravel-enso/enso#418]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
Hi,

Just update today 2022.03.03 - 19:16.

Yarn serve has this warning

```
"export 'Url' was not found in './Url.vue'
```

and

Application is not working anymore (build or serve):

![image](https://user-images.githubusercontent.com/16973022/156616756-76a7c14b-5931-4f2d-8e81-9f091083ad1a.png)

```
Uncaught TypeError: route is undefined
    match routeBuilder.js:23
    process routeBuilder.js:23
    add routeBuilder.js:10
    add routeBuilder.js:10
    handle routeBuilder.js:16
    node_modules chunk-vendors.js:5612
```

Any hints for us?

Thanks!

**Comment by robbykrlos** [comment]
Investigation:

https://github.com/laravel-enso/enso/blob/master/client/package.json
is using 
```
"@enso-ui/ui": "^5.0",
```

And 

"@enso-ui/ui": "^5.0",
is using 
```
"@enso-ui/users@^2.0"
```

But it seems that there are references in yarn.lock to multiple versions after this update :

`@enso-ui/ui": "^5.0` and `@enso-ui/ui": "^6.0` 
`@enso-ui/users@^2.0` and `@enso-ui/users@^3.0`
`@enso-ui/users-groups@^2.0` and `@enso-ui/users-groups@^3.0`

**I managed to fix the error by setting my package.json to** 
```
"@enso-ui/ui": "^6.0",
```

& yarn install && yarn build.

Can you confirm this is the fix?

**Comment by aocneanu** [comment]
hi @robbykrlos 

We will release this week v5.0 that has breaking changes on both BE & FE.

You should not use UI 6.0 until the release and upgrade steps are public.

Meanwhile, use yarn why and determine what is requiring users@3.0 / ui@6.0

**Comment by robbykrlos** [comment]
> hi @robbykrlos
> 
> We will release this week v5.0 that has breaking changes on both BE & FE.
> 
> You should not use UI 6.0 until the release and upgrade steps are public.
> 
> Meanwhile, use yarn why and determine what is requiring users@3.0 / ui@6.0

Hi, thanks for the reply, meanwhile we reverted yarn.lock to previous version. 

Thanks for the explanation.
