### ISSUE TITLE
Blank screen with loader

### ISSUE THREAD

**Issue by nikhilgyan** [laravel-enso/Enso#42]
Hello!

I have cloned this project and followed install steps but I only have a blank green screen with loader. Debugger shows some Queries as follow:
----------------------------------------------------
select * from `users` where `id` = '1' limit 1
43.77ms/vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php:51

select * from `owners` where `owners`.`id` = '1' limit 1
480μsmiddleware::verify-active-state:12

insert into `action_logs` (`user_id`, `url`, `route`, `action`, `updated_at`, `created_at`) values ('1', 'http://enso.dev/api/core', 'core.index', 'GET', '2018-02-02 12:22:30', '2018-02-02 12:22:30')
76.97ms/vendor/laravel/framework/src/Illuminate/Support/helpers.php:1038

select * from `roles` where `roles`.`id` = '1' limit 1
61.46ms/vendor/laravel-enso/permissionmanager/src/AuthServiceProvider.php:13

select `permissions`.*, `permission_role`.`role_id` as `pivot_role_id`, `permission_role`.`permission_id` as `pivot_permission_id`, `permission_role`.`created_at` as `pivot_created_at`, `permission_role`.`updated_at` as `pivot_updated_at` from `permissions` inner join `permission_role` on `permissions`.`id` = `permission_role`.`permission_id` where `permission_role`.`role_id` = '1' and `name` = 'core.index' limit 1
----------------------------------------------------

And by passing this "/api/core" to the browser, getting the following message with errors:
----------------------------------------------------
 Symfony \ Component \ HttpKernel \ Exception \ AccessDeniedHttpException
You are not authorized to perform this action
----------------------------------------------------

How I can proceed to solve it?

Best regards!

**Comment by aocneanu** [comment]
Hi,

`composer install` ran ok?

**Comment by nikhilgyan** [comment]
Yes.

After inserting 2 records in two table, its working fine for me. Those are as follows:

INSERT INTO `permissions` (`permission_group_id`, `name`, `description`, `type`, `default`, `created_at`, `updated_at`) VALUES (1, 'core.index', 'Welcome Page', 0, 1, '2018-02-02 04:53:00', '2018-02-02 04:53:00');

INSERT INTO `permission_role` (`permission_id`, `role_id`, `created_at`, `updated_at`) VALUES ('143', '1', '2018-02-02 10:24:37', '2018-02-02 10:24:37');

**Comment by aocneanu** [comment]
I'm not sure that I follow, didn't you use the `php artisan migrate` ?

**Comment by nikhilgyan** [comment]
yes I did. But by looking into the debugger, I got this SQL query:

select permissions.*, permission_role.role_id as pivot_role_id, permission_role.permission_id as pivot_permission_id, permission_role.created_at as pivot_created_at, permission_role.updated_at as pivot_updated_at from permissions inner join permission_role on permissions.id = permission_role.permission_id where permission_role.role_id = '1' and name = 'core.index' limit 1

and this returns empty result set. Hence I've added those 2 records into the DB and everything is ok for now. 

There is no any records which contains "'core.index'" while one of the query inserted into the log table. Hence I've just tried to manually insert these records. And luckily errors has been resolved.

Please correct me if I'm doing anything wrong

**Comment by aocneanu** [comment]
Please tell me how many entries you have in the permissions table.

After running `php artisan migrate` the database initialises with everything needed. In the permissions table for instance you should have 142 entries.

I just checked now with a fresh git clone and everything worked ok.

**Comment by nikhilgyan** [comment]
yes, exactly I've 142 records into this table. But after adding 1 record manually, now its been 143

**Comment by aocneanu** [comment]
You are right, something it's wrong.

I'll get back in a few minutes.

**Comment by aocneanu** [comment]
It's fixed now. We did a refactor and missed and old route. `core.init` is not used anymore, it has been replaced with `core.index`.

Sorry about that.

Everything else works ok?

**Comment by nikhilgyan** [comment]
Thanks for your kind and quick response, 
Yes, everything is working fine for now. 

Thanks a lot

**Comment by aocneanu** [comment]
For nothing, thanks for finding a bug.
