### ISSUE TITLE
Please integrate with y-js.org

### ISSUE THREAD

**Issue by COLABORATI** [laravel-enso/Enso#43]
Not many people seem to recognize that we now have a solution for collaborative editing - it would be great to have that working with your great project: https://github.com/y-js/yjs

**Comment by aocneanu** [comment]
Could you please elaborate?

**Comment by COLABORATI** [comment]
https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type

**Comment by aocneanu** [comment]
I was expecting for something more specific.
