### ISSUE TITLE
I am getting 500 error

### ISSUE THREAD

**Issue by ShresthaPrerana** [laravel-enso/enso#436]
This is  a **bug | feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

**Comment by AbdullahiAbdulkabir** [comment]
Kindly include a proper description of your error and a screenshot.
