### ISSUE TITLE
"options" meta parameter for field "menu_id" must be an array a collection or an Enum

### ISSUE THREAD

**Issue by Web-System-Create** [laravel-enso/enso#439]
This is  a **bug**.

### Description

On the edit pages for Permissions/Roles/Menus, I'm encountering this warning, and the form is not visible as a result.
*It's a clean project based on the latest version of Enso.

![image](https://github.com/laravel-enso/enso/assets/127747806/09ebd1f0-b265-4cab-a135-8e5ce95e2840)

Thank you!

**Comment by vmcvlad** [comment]
@Web-System-Create, the latest forms version should fix this issue

**Comment by Web-System-Create** [comment]
Fixed. Thank you :)
