### ISSUE TITLE
Class "LaravelEnso\DataExport\Enums\Status" not found

### ISSUE THREAD

**Issue by alexbucur-dev** [laravel-enso/enso#440]
This is  a **bug**.

### Description
This error is present in every export action on every page.
I'm running latest version of Enso clean.
![image](https://github.com/laravel-enso/enso/assets/65996369/0dba605c-8570-4fb5-ac30-33283298bf37)

**Comment by vmcvlad** [comment]
should be fixed in the latest "tables" release
