### ISSUE TITLE
These credentials do not match our records

### ISSUE THREAD

**Issue by SerhiiZahuba** [laravel-enso/enso#441]
This is  a **bug **.

### Prerequisites
* [* ] Are you running the latest version?
* [ *] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ *] Did you check the documentation?
* [ *] Did you perform a cursory search?

### Description

After installation, when entering the project, the error "These credentials do not match our records"

LOG.warning: Creation of dynamic property LaravelEnso\Core\Http\Controllers\Auth\LoginController::$maxAttempts is deprecated in /opt/mt6/enso/vendor/laravel-enso/core/src/Http/Controllers/Auth/LoginController .php on line 29
### Steps to Reproduce

my env
debian 12
php 8.3

![image](https://github.com/laravel-enso/enso/assets/36307887/283d1ea1-eab3-4bce-b866-c62216920726)

**Comment by AbdullahiAbdulkabir** [comment]
Hi @SerhiiZahuba are you able to resolve it?
