### ISSUE TITLE
Place to define global helper functions

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/Enso#47]
Sorry for this "easy" question but I would like to now where the right place to define JS helper functions is.

Example:
- I format my date in VueTable like d.m.Y
- To use the date in functions (like compare) I have to convert the date to a real Date Object (and I need the same converting function many times)

Is there a best practice to define such global helpers? If yes, where and how should I define them.

Thx.

**Comment by aocneanu** [comment]
@mauthi ,

`resources/assets/js/app.js` is the file where you can bootstrap any global js code to the project - this file is imported in `enso.js`.

You can take a look at the way the `enso/modules` are imported in `enso.js`, and if you like the approach you can build a parallel structure that will be loaded from `app.js`.

Regarding dates in `vue-table` you have two options provided by the package:

- you can use the `date` meta attribute for columns, and that will format the date in BE according to the `config('enso.datatable.dateFormat')` value.
- you can use a `customRender` function and do the mutation on the FE.

Take into consideration that we use [date-fns](https://date-fns.org/v2.0.0-alpha.7/docs/format) in Enso. This is a modular lib with all kind of helper functions for formatting, converting and comparing dates. You can import only the needed function where you use it (search date-fns in the whole project for examples).

**Comment by mauthi** [comment]
Hi,

thx for your answer.
The function I need is only available in date-fns version 2
So I will have to wait.

According to the global function stuff:
How can I define global functions in app.js? Sorry for this question but 

function testXX() {
	console.log("test");
}

is not working :)

**Comment by aocneanu** [comment]
If you update the project to the latest version you will have `date-fns@2.0.0-alpha.7` ;)

What you are looking for is `window.testXX = (value) => console.log(value)`. This will register a function to the window global scope, and will allow you to call `testXX(value)` globally.

**Comment by mauthi** [comment]
thx and thx
