### ISSUE TITLE
Show message if we try to edit a non-existent object

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/Enso#48]
(not sure if this is core or datatable or formbuilder ?)

Example: If you call 
`administration/owners/1034240/edit`
you get an empty screen. It would be better if you get a message and you get redirected to last / overview screen?

Second question (was to reason to find this error):
- It would be nice if we can to something like this:

```
public function edit(Owner $owner, OwnerForm $form)
    {
        if ($owner.xx != yy) {
            // return redirect to table and show message
        }
        return ['form' => $form->edit($owner)];
    }
```
I could not manage this?

**Comment by aocneanu** [comment]
it's related to the `errorHandler`. I will take care of it.

**Comment by mauthi** [comment]
thx, can you check my second question for a second pls?

**Comment by aocneanu** [comment]
Please open a new ticket on `formbuilder` and give me some details about what you're trying to achieve and what the context is. There might be already something in place that you can use for this.
