### ISSUE TITLE
Make footer customizable

### ISSUE THREAD

**Issue by aocneanu** [laravel-enso/enso#52]
First, remove the footer from the core package. Then, the footer becomes customizable because it will not be overwritten at every update

**Comment by dahabit** [comment]
Thanks for that fix , I faced that problem with every update :)

**Comment by aocneanu** [comment]
In the future just open an issue :)

**Comment by dbtinoyapp** [comment]
Hi @aocneanu I'm also encountering this with the Navbar file as well on every `npm run prod` command :)

**Comment by aocneanu** [comment]
Hi,

The navbar is part of the core app. At some point we will improve notifications, add new icons and so on. The navbar will have to remain in the core package.

**Comment by dbtinoyapp** [comment]
Hi @aocneanu thanks for the prompt reply. 

Is there any chance to override the logo to make it wider and remove the `appName` part?

**Comment by aocneanu** [comment]
The logo can be replaced (logo.svg).

I guess we can have a config option to enable / disable the appName. Wanna give it a try?

**Comment by robbykrlos** [comment]
Hi,
Sorry, I'm new in Enso and Laravel world. but i'm trying out Laravel Enso for one of my projects. I want to customize the footer, and i find it hard to achieve what you suggested "First, remove the footer from the core package. Then, the footer becomes customizable because it will not be overwritten at every update"

Can you be more explicit? Where is the core footer? where the footer becomes customizable?

Thank you!

**Comment by aocneanu** [comment]
please link me to that part of the doc because it's outdated.

The way you can customize the footer is by editing `node_modules/@enso-ui/ui/src/bulma/components/AppFooter.vue` and then by running `yarn patch-package @enso-ui/ui`. From now on after every `yarn upgrade` you have to run `yarn` to apply the patch. [docs](https://docs.laravel-enso.com/guide/development.html#changing-front-end-pages)

**Comment by robbykrlos** [comment]
> please link me to that part of the doc because it's outdated.
> 
> The way you can customize the footer is by editing `node_modules/@enso-ui/ui/src/bulma/components/AppFooter.vue` and then by running `yarn patch-package @enso-ui/ui`. From now on after every `yarn upgrade` you have to run `yarn` to apply the patch. [docs](https://docs.laravel-enso.com/guide/development.html#changing-front-end-pages)

It's here, int his issue, the top comment, it's your comment;)

Thanks. I did found before the node_modules AppFooter.vue, but though this might be a wrong approach to edit the file there. I didn't know about the yarn patch-pachage... Thank you for your help
