### ISSUE TITLE
Quote is shown again after reload

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/Enso#56]
Normally the quote was only shown after login, now it is shown after every reload in browser.

**Comment by aocneanu** [comment]
This is the expected behaviour.

When you refresh the browser the state needs to be reloaded. This happens while the home screen is shown.

(being a SPA, you don't need to refresh the browser)

**Comment by mauthi** [comment]
not in regular use - but often during coding :)

**Comment by aocneanu** [comment]
I know the feeling ;)

**Comment by mauthi** [comment]
Would it be possible to change this that the user is redirected automatically after everything was loaded? It's a little bitte irritating if I have for example links to customers in a document and if I open them I have to click on the button in every tab.

**Comment by aocneanu** [comment]
Yes, I will definitely do something about this.
