### ISSUE TITLE
Exception, token mismatch

### ISSUE THREAD

**Issue by pongraczi** [laravel-enso/Enso#58]
Enso 2.1.35 + Postgresql 9.6   
Since I upgraded to the latest version, I got strange behavior when I want to create new user.  
I got the following exception:  
```
Illuminate\Session\TokenMismatchException
/var/www/clients/client1/web7/web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php#70
```

After that, I am not able to logout or making actions (Update, Save etc.), because I got this exception.  
Did I miss something?

**Comment by aocneanu** [comment]
Are you sure that you are logged in?

The last version is 2.2.x.

**Comment by pongraczi** [comment]
Ok, Enso is 2.2.1 now.  Postgresql 9.6. php 7.2
* php artisan cache:clear happened after git pull (and set user:group).   
* New browser started, visit the url of enso.
* Login ok -> enter to user profile.
* Click on logout -> nothing happens.
* Exception visible:  
```
Illuminate\Session\TokenMismatchException
/var/www/clients/client1/web7/web/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php#70
```

**Comment by aocneanu** [comment]
I'll look into it

**Comment by pongraczi** [comment]
What is the proper way to upgrade, after git pull?
* I fix the owners of the files.
* I issue: php artisan migrate.
* I issue: php artisan cache:clear

Sometimes I left login during the upgrade, sometimes not.

**Comment by aocneanu** [comment]
you will have to read the changelog with attention.

**Comment by aocneanu** [comment]
take a look also here
https://github.com/laravel-enso/Enso/issues/41#issuecomment-362379365

**Comment by pongraczi** [comment]
Ok, in postgresql, the situation is better.  
* composer update happened

With mysql, I still have issue, I double check.

**Comment by pongraczi** [comment]
With Postgresql: it seems it was an inappropriate upgrade process.
