### ISSUE TITLE
Password settings are gone?

### ISSUE THREAD

**Issue by pongraczi** [laravel-enso/Enso#60]
Enso 2.2.1 + Postgresql 9.6
I do not find, where a logged user can change his/her password.  

Even, Forgot password sends a reser password link, but when I click on it, I got the login page, and there is no change password screen.

**Comment by aocneanu** [comment]
I fixed it already. please run composer update and then compile

**Comment by pongraczi** [comment]
ahh, ok, thanks.  
I have no idea, how to compile :)

**Comment by aocneanu** [comment]
:)

`npm install`

`npm run dev`

**Comment by pongraczi** [comment]
I guess I need to install npm, too :)

**Comment by pongraczi** [comment]
Is it really necessary to install nodejs or whatever is npm?  
I have emotional problems with nodejs....  

Otherwise, is it your dev. environment, right?

**Comment by pongraczi** [comment]
I completely lost.  
I did composer update; npm install; npm run dev; login and still I cannot see any changes. There is no password related things.  
![kijeloles_663](https://user-images.githubusercontent.com/5891983/36936298-d7a3c6fc-1f03-11e8-9db3-f01be092e611.png)

**Comment by aocneanu** [comment]
I'm not sure I know what you mean. To reset pass you need to logout first, and from the login form press "forgot password"

**Comment by pongraczi** [comment]
Ok, reset password link is working now.  

I just try to find out, where can I change my password after I login into the application. I did not find any password set screens.

**Comment by aocneanu** [comment]
https://github.com/laravel-enso/Core/issues/38

**Comment by pongraczi** [comment]
:))))))))  
Ok, got it.

Anyway, you should create a label called: postgresql
