### ISSUE TITLE
Upgrade guide for v2.3.0.

### ISSUE THREAD

**Issue by aocneanu** [laravel-enso/Enso#62]
This issue will guide you for upgrading Enso to v2.3.0. We'll keep this open and edit/add information if necessary.

We decided to move the User & Owner structures from the core package to the main project. This way everybody will have the freedom to modify these structures to better fit their custom projects.

The guide was used for upgrading one of our projects, and the estimate time of upgrade should be ~ 15 mins

Below you will find the upgrade steps:

1. make a new clone of the project

2. copy the following files from the clean copy to your custom project.
- App/Forms/Builders/OwnerForm.php
- App/Forms/Builders/UserForm.php
- App/Forms/Templates/owner.json
- App/Forms/Templates/user.json
- App/Http/Controllers/Administration/Owner/OwnerController.php
- App/Http/Controllers/Administration/Owner/OwnerSelectController.php
- App/Http/Controllers/Administration/Owner/OwnerTableController.php
- App/Http/Controllers/Administration/User/UserController.php
- App/Http/Controllers/Administration/User/UserSelectController.php
- App/Http/Controllers/Administration/User/UserTableController.php
- App/Http/Requests/ValidateOwnerRequest.php
- App/Http/Requests/ValidateUserRequest.php
- App/Tables/owners.json
- App/Tables/users.json

3. add to the `api.php` route file the following:
```
Route::middleware(['auth', 'core'])
    ->group(function () {
        Route::namespace('Administration')
            ->prefix('administration')->as('administration.')
            ->group(function () {
                Route::namespace('Owner')
                    ->prefix('owners')->as('owners.')
                    ->group(function () {
                        Route::get('initTable', 'OwnerTableController@init')
                            ->name('initTable');
                        Route::get('getTableData', 'OwnerTableController@data')
                            ->name('getTableData');
                        Route::get('exportExcel', 'OwnerTableController@excel')
                            ->name('exportExcel');

                        Route::get('selectOptions', 'OwnerSelectController@options')
                            ->name('selectOptions');
                    });

                Route::resource('owners', 'Owner\OwnerController', ['except' => ['show']]);

                Route::namespace('User')
                    ->prefix('users')->as('users.')
                    ->group(function () {
                        Route::get('initTable', 'UserTableController@init')
                            ->name('initTable');
                        Route::get('getTableData', 'UserTableController@data')
                            ->name('getTableData');
                        Route::get('exportExcel', 'UserTableController@excel')
                            ->name('exportExcel');
                        Route::get('selectOptions', 'UserSelectController@options')
                            ->name('selectOptions');
                    });

                Route::resource('users', 'User\UserController');
            });
    });
```

4. update your `composer.json` to require `laravel-enso/core": "2.2*`

5. make sure that the `scripts` object in your `composer.json` does not have any reference to previous enso commands in the `post-update-cmd` or `post-install-cmd` hooks.

6. run composer update

7. compile

8. delete the cloned repo.

**Comment by mauthi** [comment]
App/Http/Controllers/Owner/OwnerController.php
App/Http/Controllers/Owner/OwnerSelectController.php
App/Http/Controllers/Owner/OwnerTableController.php
App/Http/Controllers/User/UserController.php
App/Http/Controllers/User/UserSelectController.php
App/Http/Controllers/User/UserTableController.php

should be

App/Http/Controllers/**Administration/**Owner/OwnerController.php
App/Http/Controllers/**Administration/**Owner/OwnerSelectController.php
App/Http/Controllers/**Administration/**Owner/OwnerTableController.php
App/Http/Controllers/**Administration/**User/UserController.php
App/Http/Controllers/**Administration/**User/UserSelectController.php
App/Http/Controllers/**Administration/**User/UserTableController.php

**Comment by aocneanu** [comment]
@mauthi have you encounterd any other problems?

**Comment by mauthi** [comment]
no, rest worked like expected

**Comment by cosimolemma** [comment]
Hi,
I can't find this files into the repository:
App/Http/Requests/ValidateOwnerRequest.php
App/Http/Requests/ValidateUserRequest.php

Where are they?

**Comment by aocneanu** [comment]
WTF have I done ?!

They are back in 3046ab1

Sorry about that.

**Comment by cosimolemma** [comment]
Thank you @aocneanu :+1: don't worry, it's ok now :smiley:

**Comment by afonsogpedro** [comment]
@aocneanu Hi... i have a issue, the excel export on the view "users" only show a message... i'm new with laravel and i trying to use this tables on my project... you can help me? thanks
