### ISSUE TITLE
select control cannot filter

### ISSUE THREAD

**Issue by shonhor22** [laravel-enso/Enso#66]
1.After update select fields type letter can not filter options.

**Comment by aocneanu** [comment]
@shonhor22 share more details

**Comment by shonhor22** [comment]
in select control user type start letter but options don't filtered .
![image](https://user-images.githubusercontent.com/8970793/37129241-eb875a22-22b8-11e8-903a-29e26d23df83.png)


![image](https://user-images.githubusercontent.com/8970793/37129650-f13bb0d8-22ba-11e8-8095-a18cad9b0e73.png)


sorry my english not well.

**Comment by shonhor22** [comment]
changed :v-model="query" to v-model="query" but not fixed same as previous.

**Comment by aocneanu** [comment]
run composer update to have the new package, then compile
