### ISSUE TITLE
Problem "horizon" on Windows

### ISSUE THREAD

**Issue by Kolovrat19** [laravel-enso/Enso#68]
Problem 1
    - Installation request for laravel/horizon v1.2.2 -> satisfiable by laravel/horizon[v1.2.2].
    - laravel/horizon v1.2.2 requires ext-pcntl * -> the requested PHP extension pcntl is missing from your system.

**Comment by aocneanu** [comment]
Hi,

The error message is pretty self explanatory, you need the `pcntl` extenstion, it's a horizon requirement.

**Comment by Kolovrat19** [comment]
Ok. Windows has problem with pcntl. https://github.com/laravel/horizon/issues/78 
How regester new user in enso app?

**Comment by aocneanu** [comment]
The app does not offer user registration. Just create a new user from the Administration / User / Create. The user will receive a reset link by email.

**Comment by Kolovrat19** [comment]
Thank you.

**Comment by aocneanu** [comment]
You’re welcome.

**Comment by metrey** [comment]
After install pcntl, another issue with posix

```
Problem 1
    - Installation request for laravel/horizon v1.3.1 -> satisfiable by laravel/horizon[v1.3.1].
    - laravel/horizon v1.3.1 requires ext-posix * -> the requested PHP extension posix is missing from your system.
```
