### ISSUE TITLE
export excel possible direct download

### ISSUE THREAD

**Issue by shonhor22** [laravel-enso/Enso#73]
is there any way direct download table data to excel file without recieve in email

**Comment by aocneanu** [comment]
Currently no.

**Comment by shonhor22** [comment]
give me hint please.
Enso's default tables such as owner, user etc exported but my own created tables datatable export throw bellow exception.

![image](https://user-images.githubusercontent.com/8970793/37876374-14233708-307e-11e8-9797-daa4d769bd4b.png)

**Comment by aocneanu** [comment]
It's a but, i''ll fix it tomorrow.
