### ISSUE TITLE
Meta information missing after update to 2.3.x

### ISSUE THREAD

**Issue by cosimolemma** [laravel-enso/Enso#75]
Hi, I'm facing problems with meta information after updating to 2.3.x version. 
In particular, meta.appName is blank and I'm getting authentication errors related to CSRF token (this is the message gotten after a successful authentication: "can't assign to property "csrfToken in enso.js line 323").

From where can I set meta tags? Thanks

**Comment by aocneanu** [comment]
Is this on a clean project?

**Comment by cosimolemma** [comment]
No, un update from 2.1.23 version

**Comment by aocneanu** [comment]
Are you sure that you followed the Changelog?

**Comment by cosimolemma** [comment]
Yes, all followed but nothing happens. It seems a problem to missing meta tags

**Comment by aocneanu** [comment]
please run `composer info | grep core` and tell me the version you get

**Comment by cosimolemma** [comment]
This is the result:
laravel-enso/core                     2.2.9

**Comment by aocneanu** [comment]
did you compiled the js assets?

**Comment by cosimolemma** [comment]
Yes, I executed `npm run dev` from terminal too

**Comment by aocneanu** [comment]
![image](https://user-images.githubusercontent.com/16073274/37671294-1617e83c-2c74-11e8-9bec-71e7046471fe.png)

?

**Comment by cosimolemma** [comment]
I updated the routes but meta.appName is still undefined in login page.
CSRF token problem is now solved instead

**Comment by aocneanu** [comment]
look in the console under the network tab. What is the error returned by the request for appName?

**Comment by cosimolemma** [comment]
There isn't an error because the `getMeta` request gives me 200 as response code. 
But `meta.appName` is still undefined in the login page

**Comment by cosimolemma** [comment]
It seems just a lag problem because if I add this code, everything is working:
```
mounted() {
        console.log(this.meta.appName); // Result "undefined"
    }
```

**Comment by aocneanu** [comment]
Maybe you should just get the latest version clean, and manually move your files to the clean project.

It should take you something like 3 minutes and everything should work well.

**Comment by cosimolemma** [comment]
I'll try to do in this way, it should be better.
Thanks

**Comment by aocneanu** [comment]
Can we close this?

**Comment by cosimolemma** [comment]
Yes, at the moment. Thank you :+1:
