### ISSUE TITLE
You are not authorized to perform this action -  attempt of crud

### ISSUE THREAD

**Issue by outthesystem** [laravel-enso/Enso#77]
hello, thanks for this great contribution, I was testing to create a crud own, the problem is that when I try to access the index of this crud gives me this error: You are not authorized to perform this action.

https://imgur.com/a/FfRHo

https://imgur.com/a/kFoek

I've already assigned the permissions, I defined the routes, I do not know where I'm failing, I'm probably skipping a step to declare somewhere, if you can give me a hand it would be great! Greetings and great work!

**Comment by aocneanu** [comment]
Hi,

So you already
- defined the name route in the routes file
- created the permission
- added the permission to you role

Right? If so, it should work

line 13 in the `VerifyRouteAccess` does this check:

`$request->user()->can('access-route', $request->route()->getName())`

and the `access-route` gate is

```
\Gate::define('access-route', function ($user, $route) {
     return !is_null(
          $user->role->permissions()
                    ->whereName($route)
                    ->first()
      );
});
```

**Comment by outthesystem** [comment]
The truth is that I feel idota, I had to add the other permissions! Thank you! Great project, a super solution

**Comment by aocneanu** [comment]
Thank you.
