### ISSUE TITLE
menu scroll down not working

### ISSUE THREAD

**Issue by shonhor22** [laravel-enso/Enso#79]
i created many menu items. but bottom menus not shown and cannot scroll down.

![image](https://user-images.githubusercontent.com/8970793/37871996-b5ae8946-302f-11e8-94c9-e111aed5577c.png)

**Comment by shonhor22** [comment]
and following error on console always after update enso 2.5

![image](https://user-images.githubusercontent.com/8970793/37872032-bb53725c-3030-11e8-9959-01f62993b69b.png)

**Comment by aocneanu** [comment]
Regarding the error in the console, you may not have the latest core version.

Regarding scroll I'm fixing it now.

**Comment by aocneanu** [comment]
I think that this is fixed already, and the only problem is your core version

`composer info | grep core` should return 2.4.7

**Comment by shonhor22** [comment]
returned    laravel-enso/core                     2.4.8

**Comment by aocneanu** [comment]
2.4.8 should be ok too.

after composer update did you compile the js assets?

**Comment by shonhor22** [comment]
yes npm run watch always.

**Comment by aocneanu** [comment]
please check if this file is identical to what you have in `/resources`..

https://github.com/laravel-enso/Enso/blob/master/resources/assets/js/pages/layout/settings/MenuState.vue

**Comment by aocneanu** [comment]
wait.. did you deleted the old records in the `preferences` table after the upgrade?

**Comment by shonhor22** [comment]
Thank you, after deleted record from prefences table error disappeared.

**Comment by aocneanu** [comment]
The last line of the Changelog for 2.5.0 :)

![image](https://user-images.githubusercontent.com/16073274/37874116-362f4abe-3031-11e8-921f-a581bafe1f16.png)

**Comment by shonhor22** [comment]
Is there any changes. Menu scroll not working now

**Comment by aocneanu** [comment]
Please update the core to v2.5.8
