### ISSUE TITLE
"Cannot GET /" from localhost:8080 on npm run hot/hrm

### ISSUE THREAD

**Issue by tylerjheslop** [laravel-enso/Enso#8]
Followed intro steps of documentation. 
I get this error on the 1.1.0 version. 
On the most recent branch, I get:

```
 WARNING  Compiled with 1 warnings                                                                                                                                         9:56:33 PM
 warning  in ./resources/assets/js/vendor/laravel-enso/components/select/VueSelect.vue
(Emitted value instead of an instance of Error) the "scope" attribute for scoped slots have been deprecated and replaced by "slot-scope" since 2.5. The new "slot-scope" attribute can also be used on plain elements in addition to <template> to denote scoped slots.
```

Running different npm scripts, I can get it to run the script without it terminating early. Still end up with the same output at localhost:8080. 

What I've tried:
Running with homestead
Running through valet 

The warning output shouldn't prevent the script from running as it is caused by a non-breaking change in Vue 2.5. 

This may be a simple fix but I can't seem to get it. Any help? Everything is default. If this is a simple fix, could you add a clarification step in the doc between steps 4 and 5? This project looks great and I'd contribute if I can it working.

**Comment by aocneanu** [comment]
I just updated all the packages with the new syntax, including this project.
You can clone it again and start from scratch or just do `composer update` & `npm update` (in this case don't forget to update the vue-template-compiler too).
Everything should be fine now.

**Comment by tylerjheslop** [comment]
Thank you! Testing this now, will confirm.

**Comment by tylerjheslop** [comment]
Still no luck, facing the same issue. Tried with a fresh copy of the repo as well as the copy I was working on. 
Terminal and Safari output: https://imgur.com/a/jHyRe

**Comment by tylerjheslop** [comment]
Finally got it working. OS X console showed safari didn't have permission to access localhost. Repaired disk permissions, reinstalled valet.
```
1) Clone fresh copy of repo.
2) composer install
3) npm install
4) cp .env.example .env; vim .env
5) php artisan key:generate
6) npm run dev
7) cd /root-of-project/
8) valet link enso; valet open
```

**Comment by aocneanu** [comment]
I’m glad that you sorted it all out.
