### ISSUE TITLE
How to edit the appearance of the view start session?

### ISSUE THREAD

**Issue by outthesystem** [laravel-enso/Enso#81]
Hello! I wanted to know how I could do to modify the theme that appears by default in the login of the application. regards

**Comment by aocneanu** [comment]
Once you clone the project, edit the appropriate files.

Beware that when you do composer update all the core asset publish with --force, so you will have to manage this yourself.

**Comment by mauthi** [comment]
Maybe we should add something like config(‚app.theme‘)

**Comment by outthesystem** [comment]
Thanks for the answers, in fact what I'm looking for is where are the css or scss to edit the theme that is predetermined for the frontend, since I am preparing a blog module, and all the logic is prepared in backend, the only thing that I need to do is the frontend, and I would like to know what file is used to execute the styles.

**Comment by outthesystem** [comment]
https://imgur.com/a/ET9k4

for example, to edit the background color, in which part is this color declared?

**Comment by aocneanu** [comment]
Almost nothing is custom in Enso at the css level. It's all plain Bulma, and the themes from bulmaswatch. 

The theme is set here https://github.com/laravel-enso/Core/blob/master/src/resources/views/index.blade.php#L7.

Maybe you will make a custom theme and add it to the repo ;)

**Comment by outthesystem** [comment]
yes! Actually that is the goal, prepare a public module with blog features and a blog style theme, I saw that Enso is super powerful in the administrative part, that's why I wanted to create a frontend example and publish it, I know someone is going to serve it!
