### ISSUE TITLE
How deploy application?

### ISSUE THREAD

**Issue by outthesystem** [laravel-enso/Enso#82]
feature request

I have finished my application, but I do not know how to do the deploy, I am trying to upload it to azure, the problem is that it works entering the public directory, I can not run php artisan serve and therefore Enso does not work, can you give me a guide how to do it?

**Comment by aocneanu** [comment]
Please use the issue template form now on. I have 0 experience with azure.

1st google search https://medium.com/@coderonfleek/hosting-a-laravel-application-on-azure-web-app-b55e12514c46
