### ISSUE TITLE
formbuilder Input Prefix and Suffix

### ISSUE THREAD

**Issue by shonhor22** [laravel-enso/Enso#85]
This is  a ** feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository? (enso is made up of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

If formbuilder contain input's prefix suffix config from template would be nice
### Actual behavior

there is no option here

**Comment by aocneanu** [comment]
Please elaborate

**Comment by shonhor22** [comment]
![image](https://user-images.githubusercontent.com/8970793/38067231-1579b920-333e-11e8-8276-8552212bbc28.png)

**Comment by aocneanu** [comment]
Apparently in Bulma, fields with prefix / suffix (.has-addons) don't play nice with labels.

https://github.com/jgthms/bulma/issues/1294

**Comment by aocneanu** [comment]
Also, this issue does not belong to this repo.
