### ISSUE TITLE
Money amount input field required

### ISSUE THREAD

**Issue by shonhor22** [laravel-enso/Enso#86]
This is  a **feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository? (enso is made up of many specialized packages: https://github.com/laravel-enso)
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

### Description

input number not used for money amount field. 
### Steps to Reproduce

formbuilder input field

### Expected behavior

 input must shown as 120,000,000 $
### Actual behavior

such as 1200000000

**Comment by aocneanu** [comment]
On a second though I think that this will be a great addition, so now we have a new input for `money`.
The input uses [accounting-js](http://openexchangerates.github.io/accounting.js/) so make sure you install it.

In your template.json add a column like this
```
{
            "label": "Price",
            "name": "price",
            "value": 12321.12,
            "meta": {
                "type": "input",
                "content": "money"
            }
 }
```

Optional meta attributes are: `symbol`, `precision`, `thousand`, `positive`, `negative`, `zero`

Format of the meta attributes can be seen on the accounting-js documentation.

@gandesc please update the docs

**Comment by aocneanu** [comment]
closed with laravel-enso/formbuilder@797fa24

**Comment by mauthi** [comment]
can you help me do install accounting-js?
added `"accounting": "^0.4.1",` to package.json and called `npm i accounting` - but system doesn't compile:

`Module not found: Error: Can't resolve 'accounting-js' in '/Users/mauthi/coding/Enso/resources/assets/js/components/enso/vuedatatable'`

**Comment by mauthi** [comment]
I think problem is `import accounting from 'accounting-js';` 
Should be `import accounting from 'accounting';`

**Comment by aocneanu** [comment]
@mauthi `npm install --save accounting-js`

**Comment by mauthi** [comment]
thx, done!
