### ISSUE TITLE
Datatable how add multiple selected values in 1 column

### ISSUE THREAD

**Issue by shonhor22** [laravel-enso/Enso#87]
This is  a ** feature request**.

### Prerequisites
* [ ] Are you running the latest version?
* [ ] Are you reporting to the correct repository? (enso is made up of many specialized packages: https://github.com/laravel-enso)
* [ ] Did you check the documentation?
* [ ] Did you perform a cursory search?

### Description

i have to add column that contain multiple options. 
i used group_concat. but datatable's total value changed wrong cause of group by 
### Steps to Reproduce

If possible add a column to menus index datatable show which roles selected.

**Comment by aocneanu** [comment]
This is not a issue for the Enso repo
