### ISSUE TITLE
Json input field

### ISSUE THREAD

**Issue by boing6000** [laravel-enso/Enso#88]
This is  a **bug | feature request**.

### Prerequisites
* [x ] Are you running the latest version?
* [ x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [ x] Did you check the documentation?
* [ x] Did you perform a cursory search?

### Description
Could be possible to add inputs to json field?

### Steps to Reproduce
Example:

"fields": [{
            "label": "First Name",
            "name": "first_name",
            "value": null,
            "meta": {
                "type": "input",
                "content": "text"
            }
        }, {
            "label": "Phones",
            "name": "phones",
            "value": null,
            "meta": {
                "type": "json",
                "fields": [{
                     "label": "Phone 1",
                     "name": "phone_1",
                     "value": null,
                     "meta": {
                          "type": "input",
                          "content": "text"
                     }
                 ]
            }
        }
]

**Comment by aocneanu** [comment]
@boing6000 , not the way you did, but I guess you could do something like:

```
{
    "routePrefix": "administration.users",
    "sections": [{
        "columns": "2",
        "fields": [{
            "label": "First Name",
            "name": "first_name",
            "value": null,
            "meta": {
                "type": "input",
                "content": "text"
            }
        }, {
            "label": "Last Name",
            "name": "last_name",
            "value": null,
            "meta": {
                "type": "input",
                "content": "text"
            }
        }, {
            "label": "Email",
            "name": "email",
            "value": null,
            "meta": {
                "type": "input",
                "content": "email"
            }
        }, {
            "label": "Entity",
            "name": "owner_id",
            "value": null,
            "meta": {
                "custom": true,
                "type": "select",
                "multiple": false,
                "options": [],
                "source": "administration.owners.selectOptions"
            }
        }]
    }, {
        "columns": 3,
        "divider": true,
        "title": "Phone numbers",
        "fields": [
        {
            "label": "",
            "name": "phone_one",
            "value": null,
            "meta": {
                "type": "input",
                "content": "text"
            }
        },{
            "label": "",
            "name": "phone_two",
            "value": null,
            "meta": {
                "type": "input",
                "content": "text"
            }
        },{
            "label": "",
            "name": "phone_three",
            "value": null,
            "meta": {
                "type": "input",
                "content": "text"
            }
        }]
    },
    {   
        "columns": 2,
        "divider": true,
        "fields": [
            {
            "label": "Role",
            "name": "role_id",
            "value": null,
            "meta": {
                "custom": true,
                "type": "select",
                "multiple": false,
                "options": [],
                "source": "system.roles.selectOptions"
            }
        }, {
            "label": "Branch",
            "name": "branch_id",
            "value": null,
            "meta": {
                "type": "select",
                "multiple": false,
                "options": [],
                "source": "administration.branches.selectOptions"
            }
        }, {
            "label": "Active",
            "name": "is_active",
            "value": false,
            "meta": {
                "type": "input",
                "content": "checkbox"
            }
        }]
    }]
}
```

that would result in:

![image](https://user-images.githubusercontent.com/16073274/38209597-8e6da184-36bd-11e8-9373-f180fc4635ec.png)

if this suits your need.

**Comment by aocneanu** [comment]
one more thing, this is for the formbuilder repo, not the current Enso.

**Comment by boing6000** [comment]
how i can save the phone_one phone_two in column phones, in the main table would be something like this: column phones: {phone_one : '4644646', phone_two: '649898489'}

**Comment by aocneanu** [comment]
I’m not sure I follow, but you would save like you would do with any other form
