### ISSUE TITLE
After Session has expired needs a redirect to login view.

### ISSUE THREAD

**Issue by dcastrili** [laravel-enso/Enso#9]
Hi, 

I experienced an issue when the session expires and therefore the calls to the api from axios does not return the data at all. I see it is because the user is not logged in, but still is in the admin-panel if browser window is not reloded manually.

**Comment by aocneanu** [comment]
fixed with https://github.com/laravel-enso/Core/commit/66ae3d594b1a86dddd630b52c4475962bad906f3. Will update the enso repo also today.

**Comment by mauthi** [comment]
I think the fix doesn't work - I found 2 issues here (after your update):

- Reloading table without session (with expired session)
![screenshot 2017-11-09 14 09 05](https://user-images.githubusercontent.com/7204559/32607019-c54af6e8-c557-11e7-9732-ad09e6593f47.png)

- Accessing a view without session (with expired session)
![screenshot 2017-11-09 14 09 34](https://user-images.githubusercontent.com/7204559/32607034-d9db9342-c557-11e7-8612-3740a99e3417.png)

**Comment by aocneanu** [comment]
v2.0.33 fixes both

**Comment by mauthi** [comment]
works - thx
