### ISSUE TITLE
Distance calculation

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/Enso#91]
This is  a question/feature request.

### Description
In my app I have implemented a drivers log for our company.
At the moment we are calculation distance between start and end of journey manually.
It would be nice if I have 2 input fields with
- suggestions from google places api
- automatic distance calculation

Do you know how I can start with this?
Do you know packages to use here, e.g. https://www.npmjs.com/package/vue2-google-maps?

Thx.

**Comment by aocneanu** [comment]
Hi @mauthi,

I have 0 experience with this. I would start with reading the Google api docs.

**Comment by shonhor22** [comment]
My next task have to work with google maps. So if Enso will have work with google api it will be very helpful.

**Comment by aocneanu** [comment]
I think that we can safely close this, it's not related to Enso in any way.
