### ISSUE TITLE
After every build all menu's disappeared

### ISSUE THREAD

**Issue by shonhor22** [laravel-enso/Enso#92]
This is  a **bug  request**.

### Description

First menu shows. But after update any .vue file npm run watch running and building and after refreshing page all menu's disappeared with following error
### Actual behavior

![image](https://user-images.githubusercontent.com/8970793/38530439-133ef98c-3c9d-11e8-945f-a2e57b4c5726.png)

**Comment by aocneanu** [comment]
Please click the link `Menus.vue?f47d:119` and post here the result.

Why don't you use `npm run hot` and don't reload the page (it will refresh automatically)

**Comment by shonhor22** [comment]
line 119 
=== `/${menu.link.split('.').slice(0, -1).join('/')}`

**Comment by aocneanu** [comment]
It seems that you have a menu that is not parent and also has a null link.

Is this the case?

**Comment by aocneanu** [comment]
We need a validation to prevent this situation in the future
