### ISSUE TITLE
how store vuetable filters value save

### ISSUE THREAD

**Issue by shonhor22** [laravel-enso/Enso#94]
This is  a **help request**.

### Description

I use many filter's in vuetable. filter's are working but when edit or show one row after back button or list menu clicked every filter's value cleared and all data shown. So have to filter again is hard for customer.
![image](https://user-images.githubusercontent.com/8970793/38855733-f58c9f2e-4256-11e8-95bd-94a0e104e306.png)

### Expected behavior

if user not logout previous filter's value saved
### Actual behavior

every time index page load it return all data

**Comment by vuongdinhngoc** [comment]
+1

**Comment by aocneanu** [comment]
We discussed internally and this is not a feature that we will add to soon.

You can solve this easily by doing something like this:

pageThatHasATable.vue

```
    watch: {
                filters: {
                    handler() {
                        localStorage.setItem('uniqueKey', JSON.stringify(this.filters));
                    },

                    deep: true
                }
            },

            created() {
                if (localStorage.hasOwnProperty('uniqueKey')) {
                    this.filters = JSON.parse(localStorage.getItem('uniqueKey'));
                }
            },
```

With this you will achieve saving the state of the filters even if the user logs out.

You can add watchers for `intervals` and `params` as well.

**Comment by shonhor22** [comment]
Is it possible open edit page in new tab without closing index page. There is'n 'open in new tab'

![image](https://user-images.githubusercontent.com/8970793/39761411-9a5b4370-530a-11e8-9ff9-9320dd91bf9b.png)

**Comment by aocneanu** [comment]
but... this is a SPA...

You can create a custom button and add logic for that button to do whatever you need. Check the docs.

**Comment by shonhor22** [comment]
Interval filter's value's are nested array. So JSON.parse not working. below error occuring.

> Error in render: "TypeError: Cannot read property 'min' of undefined"

**Comment by aocneanu** [comment]
console.log the JSON.parse and post here the result

**Comment by shonhor22** [comment]
Sorry. Interval working now. I missed something.
Thank you for answer
