### ISSUE TITLE
New Install - Testing failures

### ISSUE THREAD

**Issue by Aubrey-Robertson** [laravel-enso/Enso#97]
Fresh Enso install - following the documentation. Using Vagrant Homestead, latest Box 6.0.0

Trying to run tests and get many failures/errors.

![image](https://user-images.githubusercontent.com/3092255/39785784-0d4bd2fa-52e3-11e8-9148-fbb585f55444.png)

It seems that the dataTableIndex() test from the TestDataTable trait is the biggest offender - getting:
Expected status code 200 but received 500

I've tried to duplicate many of the tests to troubleshoot - but little success. Any insight would be appreciated.

**Comment by aocneanu** [comment]
![image](https://user-images.githubusercontent.com/16073274/39802381-86b4e8dc-5376-11e8-8a98-8319f658cd3c.png)

**Comment by aocneanu** [comment]
They are tagged now
