### ISSUE TITLE
Enso datatable create, passing extra data.

### ISSUE THREAD

**Issue by stevefrost** [laravel-enso/Enso#98]
### Description
I have a datatable on the url .../department/2 that lists staff roles for that department, when I click the create button, it navigates to .../department/2/staffrole/create and displays a form for adding new staff roles, but I cannot find a way to get the department_id (2) available to either the form (so I can store it as a form value) or the controller store method. I've tried several things, but I just cannot seem to pass the value in.

**Comment by aocneanu** [comment]
I'm not sure that I correctly understand...

Please share here your front-end code and reiterate the problem.

**Comment by aocneanu** [comment]
I got it now.

It seems that the `vue-form-ss` component was done in a hurry and somehow we missed the fact that `params` is a prop for the `vue-form` meant exactly for this purpose.

The clean way would be to have the `params` prop in `vue-form-ss` cascading its content to `vue-form`, and add a `route-params` prop to the `vue-form-ss` for the current purpose.

This will be a breaking change, and the whole project needs refactoring, but that's not a problem. I will do this in the following days.

**Comment by stevefrost** [comment]
Fantastic, I look forward to the fix :)
